// This file was auto-generated by Fern from our API Definition.

import type * as TurquoisehealthApi from "../../../index.js";

export type V3PricesQueryRequestPricing =
    | TurquoisehealthApi.V3PricesQueryRequestPricing.Cash
    | TurquoisehealthApi.V3PricesQueryRequestPricing.Negotiated;

export namespace V3PricesQueryRequestPricing {
    export interface Cash extends TurquoisehealthApi.V3PricingCash {
        type: "cash";
    }

    export interface Negotiated extends TurquoisehealthApi.V3PricingNegotiated {
        type: "negotiated";
    }
}
