// This file was auto-generated by Fern from our API Definition.

import type { BaseClientOptions, BaseRequestOptions } from "../../../../BaseClient.js";
import { type NormalizedClientOptionsWithAuth, normalizeClientOptionsWithAuth } from "../../../../BaseClient.js";
import { mergeHeaders } from "../../../../core/headers.js";
import * as core from "../../../../core/index.js";
import { toJson } from "../../../../core/json.js";
import * as errors from "../../../../errors/index.js";
import * as TurquoisehealthApi from "../../../index.js";

export declare namespace ConsumerPricingClient {
    export interface Options extends BaseClientOptions {}

    export interface RequestOptions extends BaseRequestOptions {}
}

export class ConsumerPricingClient {
    protected readonly _options: NormalizedClientOptionsWithAuth<ConsumerPricingClient.Options>;

    constructor(options: ConsumerPricingClient.Options) {
        this._options = normalizeClientOptionsWithAuth(options);
    }

    /**
     * List negotiated-rate networks, filterable by name (case-insensitive substring, matches network or payer name), payer_id (exact), relationships (provider_id/package_id — networks with at least one matching price), and one location mode: `location.near.*`, `location.within.*` (state/cbsa/zip_codes), or `location.zip`. Location scopes to networks with at least one price at an in-area provider, so `package_id` + location answers 'which networks price this package here' in one call. Results reflect networks Turquoise has priced. The network's payer is an {id, name} stub; the full entity lives at /v3/payers/{id}.
     *
     * @param {TurquoisehealthApi.V3ListNetworksRequest} request
     * @param {ConsumerPricingClient.RequestOptions} requestOptions - Request-specific configuration.
     *
     * @throws {@link TurquoisehealthApi.BadRequestError}
     * @throws {@link TurquoisehealthApi.NotFoundError}
     * @throws {@link TurquoisehealthApi.UnprocessableEntityError}
     * @throws {@link TurquoisehealthApi.TooManyRequestsError}
     * @throws {@link TurquoisehealthApi.InternalServerError}
     *
     * @example
     *     await client.consumerPricing.v3ListNetworks()
     */
    public v3ListNetworks(
        request: TurquoisehealthApi.V3ListNetworksRequest = {},
        requestOptions?: ConsumerPricingClient.RequestOptions,
    ): core.HttpResponsePromise<TurquoisehealthApi.V3ListEnvelopeNetwork> {
        return core.HttpResponsePromise.fromPromise(this.__v3ListNetworks(request, requestOptions));
    }

    private async __v3ListNetworks(
        request: TurquoisehealthApi.V3ListNetworksRequest = {},
        requestOptions?: ConsumerPricingClient.RequestOptions,
    ): Promise<core.WithRawResponse<TurquoisehealthApi.V3ListEnvelopeNetwork>> {
        const {
            name,
            payer_id: payerId,
            provider_id: providerId,
            package_id: packageId,
            search,
            min_score: minScore,
            page_size: pageSize,
            cursor,
            "location.near.lat": locationNearLat,
            "location.near.lng": locationNearLng,
            "location.near.radius_m": locationNearRadiusM,
            "location.within.state": locationWithinState,
            "location.within.cbsa": locationWithinCbsa,
            "location.within.zip_codes": locationWithinZipCodes,
            "location.zip": locationZip,
        } = request;
        const _queryParams: Record<string, string | string[] | object | object[] | null> = {};
        if (name !== undefined) {
            _queryParams.name = name;
        }

        if (payerId !== undefined) {
            _queryParams.payer_id = payerId;
        }

        if (providerId !== undefined) {
            _queryParams.provider_id = providerId;
        }

        if (packageId !== undefined) {
            _queryParams.package_id = packageId;
        }

        if (search !== undefined) {
            _queryParams.search = search;
        }

        if (minScore !== undefined) {
            _queryParams.min_score = minScore?.toString() ?? null;
        }

        if (pageSize != null) {
            _queryParams.page_size = pageSize.toString();
        }

        if (cursor !== undefined) {
            _queryParams.cursor = cursor;
        }

        if (locationNearLat !== undefined) {
            _queryParams["location.near.lat"] = locationNearLat?.toString() ?? null;
        }

        if (locationNearLng !== undefined) {
            _queryParams["location.near.lng"] = locationNearLng?.toString() ?? null;
        }

        if (locationNearRadiusM !== undefined) {
            _queryParams["location.near.radius_m"] = locationNearRadiusM?.toString() ?? null;
        }

        if (locationWithinState !== undefined) {
            _queryParams["location.within.state"] = locationWithinState;
        }

        if (locationWithinCbsa !== undefined) {
            _queryParams["location.within.cbsa"] = locationWithinCbsa;
        }

        if (locationWithinZipCodes !== undefined) {
            _queryParams["location.within.zip_codes"] = locationWithinZipCodes;
        }

        if (locationZip !== undefined) {
            _queryParams["location.zip"] = locationZip;
        }

        const _authRequest: core.AuthRequest = await this._options.authProvider.getAuthRequest();
        const _headers: core.Fetcher.Args["headers"] = mergeHeaders(
            _authRequest.headers,
            this._options?.headers,
            requestOptions?.headers,
        );
        const _response = await core.fetcher({
            url: core.url.join(
                (await core.Supplier.get(this._options.baseUrl)) ??
                    (await core.Supplier.get(this._options.environment)),
                "v3/networks",
            ),
            method: "GET",
            headers: _headers,
            queryParameters: { ..._queryParams, ...requestOptions?.queryParams },
            timeoutMs: (requestOptions?.timeoutInSeconds ?? this._options?.timeoutInSeconds ?? 60) * 1000,
            maxRetries: requestOptions?.maxRetries ?? this._options?.maxRetries,
            abortSignal: requestOptions?.abortSignal,
            fetchFn: this._options?.fetch,
            logging: this._options.logging,
        });
        if (_response.ok) {
            return {
                data: _response.body as TurquoisehealthApi.V3ListEnvelopeNetwork,
                rawResponse: _response.rawResponse,
            };
        }

        if (_response.error.reason === "status-code") {
            switch (_response.error.statusCode) {
                case 400:
                    throw new TurquoisehealthApi.BadRequestError(
                        _response.error.body as TurquoisehealthApi.V3ErrorResponse,
                        _response.rawResponse,
                    );
                case 404:
                    throw new TurquoisehealthApi.NotFoundError(
                        _response.error.body as TurquoisehealthApi.V3ErrorResponse,
                        _response.rawResponse,
                    );
                case 422:
                    throw new TurquoisehealthApi.UnprocessableEntityError(
                        _response.error.body as TurquoisehealthApi.V3ErrorResponse,
                        _response.rawResponse,
                    );
                case 429:
                    throw new TurquoisehealthApi.TooManyRequestsError(
                        _response.error.body as TurquoisehealthApi.V3ErrorResponse,
                        _response.rawResponse,
                    );
                case 500:
                    throw new TurquoisehealthApi.InternalServerError(
                        _response.error.body as TurquoisehealthApi.V3ErrorResponse,
                        _response.rawResponse,
                    );
                default:
                    throw new errors.TurquoisehealthApiError({
                        statusCode: _response.error.statusCode,
                        body: _response.error.body,
                        rawResponse: _response.rawResponse,
                    });
            }
        }

        switch (_response.error.reason) {
            case "non-json":
                throw new errors.TurquoisehealthApiError({
                    statusCode: _response.error.statusCode,
                    body: _response.error.rawBody,
                    rawResponse: _response.rawResponse,
                });
            case "body-is-null":
                throw new errors.TurquoisehealthApiError({
                    statusCode: _response.error.statusCode,
                    rawResponse: _response.rawResponse,
                });
            case "timeout":
                throw new errors.TurquoisehealthApiTimeoutError("Timeout exceeded when calling GET /v3/networks.");
            case "unknown":
                throw new errors.TurquoisehealthApiError({
                    message: _response.error.errorMessage,
                    rawResponse: _response.rawResponse,
                });
        }
    }

    /**
     * Fetch a single network by ID. Missing or unpermissioned IDs return a 404 with the standard error body.
     *
     * @param {TurquoisehealthApi.V3GetNetworkRequest} request
     * @param {ConsumerPricingClient.RequestOptions} requestOptions - Request-specific configuration.
     *
     * @throws {@link TurquoisehealthApi.BadRequestError}
     * @throws {@link TurquoisehealthApi.NotFoundError}
     * @throws {@link TurquoisehealthApi.UnprocessableEntityError}
     * @throws {@link TurquoisehealthApi.TooManyRequestsError}
     * @throws {@link TurquoisehealthApi.InternalServerError}
     *
     * @example
     *     await client.consumerPricing.v3GetNetwork({
     *         network_id: "2010265101"
     *     })
     */
    public v3GetNetwork(
        request: TurquoisehealthApi.V3GetNetworkRequest,
        requestOptions?: ConsumerPricingClient.RequestOptions,
    ): core.HttpResponsePromise<TurquoisehealthApi.V3Network> {
        return core.HttpResponsePromise.fromPromise(this.__v3GetNetwork(request, requestOptions));
    }

    private async __v3GetNetwork(
        request: TurquoisehealthApi.V3GetNetworkRequest,
        requestOptions?: ConsumerPricingClient.RequestOptions,
    ): Promise<core.WithRawResponse<TurquoisehealthApi.V3Network>> {
        const { network_id: networkId } = request;
        const _authRequest: core.AuthRequest = await this._options.authProvider.getAuthRequest();
        const _headers: core.Fetcher.Args["headers"] = mergeHeaders(
            _authRequest.headers,
            this._options?.headers,
            requestOptions?.headers,
        );
        const _response = await core.fetcher({
            url: core.url.join(
                (await core.Supplier.get(this._options.baseUrl)) ??
                    (await core.Supplier.get(this._options.environment)),
                `v3/networks/${core.url.encodePathParam(networkId)}`,
            ),
            method: "GET",
            headers: _headers,
            queryParameters: requestOptions?.queryParams,
            timeoutMs: (requestOptions?.timeoutInSeconds ?? this._options?.timeoutInSeconds ?? 60) * 1000,
            maxRetries: requestOptions?.maxRetries ?? this._options?.maxRetries,
            abortSignal: requestOptions?.abortSignal,
            fetchFn: this._options?.fetch,
            logging: this._options.logging,
        });
        if (_response.ok) {
            return { data: _response.body as TurquoisehealthApi.V3Network, rawResponse: _response.rawResponse };
        }

        if (_response.error.reason === "status-code") {
            switch (_response.error.statusCode) {
                case 400:
                    throw new TurquoisehealthApi.BadRequestError(
                        _response.error.body as TurquoisehealthApi.V3ErrorResponse,
                        _response.rawResponse,
                    );
                case 404:
                    throw new TurquoisehealthApi.NotFoundError(
                        _response.error.body as TurquoisehealthApi.V3ErrorResponse,
                        _response.rawResponse,
                    );
                case 422:
                    throw new TurquoisehealthApi.UnprocessableEntityError(
                        _response.error.body as TurquoisehealthApi.V3ErrorResponse,
                        _response.rawResponse,
                    );
                case 429:
                    throw new TurquoisehealthApi.TooManyRequestsError(
                        _response.error.body as TurquoisehealthApi.V3ErrorResponse,
                        _response.rawResponse,
                    );
                case 500:
                    throw new TurquoisehealthApi.InternalServerError(
                        _response.error.body as TurquoisehealthApi.V3ErrorResponse,
                        _response.rawResponse,
                    );
                default:
                    throw new errors.TurquoisehealthApiError({
                        statusCode: _response.error.statusCode,
                        body: _response.error.body,
                        rawResponse: _response.rawResponse,
                    });
            }
        }

        switch (_response.error.reason) {
            case "non-json":
                throw new errors.TurquoisehealthApiError({
                    statusCode: _response.error.statusCode,
                    body: _response.error.rawBody,
                    rawResponse: _response.rawResponse,
                });
            case "body-is-null":
                throw new errors.TurquoisehealthApiError({
                    statusCode: _response.error.statusCode,
                    rawResponse: _response.rawResponse,
                });
            case "timeout":
                throw new errors.TurquoisehealthApiTimeoutError(
                    "Timeout exceeded when calling GET /v3/networks/{network_id}.",
                );
            case "unknown":
                throw new errors.TurquoisehealthApiError({
                    message: _response.error.errorMessage,
                    rawResponse: _response.rawResponse,
                });
        }
    }

    /**
     * List service packages, filterable by name (case-insensitive substring), anchor billing code (exact, matches package base codes only), and relationships (provider_id, network_id, payer_id — packages with at least one matching price). When multiple relationship filters are combined, they must be satisfied by the same price row, so results are always fulfillable via GET /v3/prices. Results reflect packages Turquoise has priced.
     *
     * @param {TurquoisehealthApi.V3ListPackagesRequest} request
     * @param {ConsumerPricingClient.RequestOptions} requestOptions - Request-specific configuration.
     *
     * @throws {@link TurquoisehealthApi.BadRequestError}
     * @throws {@link TurquoisehealthApi.NotFoundError}
     * @throws {@link TurquoisehealthApi.UnprocessableEntityError}
     * @throws {@link TurquoisehealthApi.TooManyRequestsError}
     * @throws {@link TurquoisehealthApi.InternalServerError}
     *
     * @example
     *     await client.consumerPricing.v3ListPackages()
     */
    public v3ListPackages(
        request: TurquoisehealthApi.V3ListPackagesRequest = {},
        requestOptions?: ConsumerPricingClient.RequestOptions,
    ): core.HttpResponsePromise<TurquoisehealthApi.V3ListEnvelopePackage> {
        return core.HttpResponsePromise.fromPromise(this.__v3ListPackages(request, requestOptions));
    }

    private async __v3ListPackages(
        request: TurquoisehealthApi.V3ListPackagesRequest = {},
        requestOptions?: ConsumerPricingClient.RequestOptions,
    ): Promise<core.WithRawResponse<TurquoisehealthApi.V3ListEnvelopePackage>> {
        const {
            name,
            anchor_code: anchorCode,
            provider_id: providerId,
            network_id: networkId,
            payer_id: payerId,
            search,
            min_score: minScore,
            page_size: pageSize,
            cursor,
        } = request;
        const _queryParams: Record<string, string | string[] | object | object[] | null> = {};
        if (name !== undefined) {
            _queryParams.name = name;
        }

        if (anchorCode !== undefined) {
            _queryParams.anchor_code = anchorCode;
        }

        if (providerId !== undefined) {
            _queryParams.provider_id = providerId;
        }

        if (networkId !== undefined) {
            _queryParams.network_id = networkId;
        }

        if (payerId !== undefined) {
            _queryParams.payer_id = payerId;
        }

        if (search !== undefined) {
            _queryParams.search = search;
        }

        if (minScore !== undefined) {
            _queryParams.min_score = minScore?.toString() ?? null;
        }

        if (pageSize != null) {
            _queryParams.page_size = pageSize.toString();
        }

        if (cursor !== undefined) {
            _queryParams.cursor = cursor;
        }

        const _authRequest: core.AuthRequest = await this._options.authProvider.getAuthRequest();
        const _headers: core.Fetcher.Args["headers"] = mergeHeaders(
            _authRequest.headers,
            this._options?.headers,
            requestOptions?.headers,
        );
        const _response = await core.fetcher({
            url: core.url.join(
                (await core.Supplier.get(this._options.baseUrl)) ??
                    (await core.Supplier.get(this._options.environment)),
                "v3/packages",
            ),
            method: "GET",
            headers: _headers,
            queryParameters: { ..._queryParams, ...requestOptions?.queryParams },
            timeoutMs: (requestOptions?.timeoutInSeconds ?? this._options?.timeoutInSeconds ?? 60) * 1000,
            maxRetries: requestOptions?.maxRetries ?? this._options?.maxRetries,
            abortSignal: requestOptions?.abortSignal,
            fetchFn: this._options?.fetch,
            logging: this._options.logging,
        });
        if (_response.ok) {
            return {
                data: _response.body as TurquoisehealthApi.V3ListEnvelopePackage,
                rawResponse: _response.rawResponse,
            };
        }

        if (_response.error.reason === "status-code") {
            switch (_response.error.statusCode) {
                case 400:
                    throw new TurquoisehealthApi.BadRequestError(
                        _response.error.body as TurquoisehealthApi.V3ErrorResponse,
                        _response.rawResponse,
                    );
                case 404:
                    throw new TurquoisehealthApi.NotFoundError(
                        _response.error.body as TurquoisehealthApi.V3ErrorResponse,
                        _response.rawResponse,
                    );
                case 422:
                    throw new TurquoisehealthApi.UnprocessableEntityError(
                        _response.error.body as TurquoisehealthApi.V3ErrorResponse,
                        _response.rawResponse,
                    );
                case 429:
                    throw new TurquoisehealthApi.TooManyRequestsError(
                        _response.error.body as TurquoisehealthApi.V3ErrorResponse,
                        _response.rawResponse,
                    );
                case 500:
                    throw new TurquoisehealthApi.InternalServerError(
                        _response.error.body as TurquoisehealthApi.V3ErrorResponse,
                        _response.rawResponse,
                    );
                default:
                    throw new errors.TurquoisehealthApiError({
                        statusCode: _response.error.statusCode,
                        body: _response.error.body,
                        rawResponse: _response.rawResponse,
                    });
            }
        }

        switch (_response.error.reason) {
            case "non-json":
                throw new errors.TurquoisehealthApiError({
                    statusCode: _response.error.statusCode,
                    body: _response.error.rawBody,
                    rawResponse: _response.rawResponse,
                });
            case "body-is-null":
                throw new errors.TurquoisehealthApiError({
                    statusCode: _response.error.statusCode,
                    rawResponse: _response.rawResponse,
                });
            case "timeout":
                throw new errors.TurquoisehealthApiTimeoutError("Timeout exceeded when calling GET /v3/packages.");
            case "unknown":
                throw new errors.TurquoisehealthApiError({
                    message: _response.error.errorMessage,
                    rawResponse: _response.rawResponse,
                });
        }
    }

    /**
     * Fetch a single package by ID. Missing or unpermissioned IDs return a 404 with the standard error body.
     *
     * @param {TurquoisehealthApi.V3GetPackageRequest} request
     * @param {ConsumerPricingClient.RequestOptions} requestOptions - Request-specific configuration.
     *
     * @throws {@link TurquoisehealthApi.BadRequestError}
     * @throws {@link TurquoisehealthApi.NotFoundError}
     * @throws {@link TurquoisehealthApi.UnprocessableEntityError}
     * @throws {@link TurquoisehealthApi.TooManyRequestsError}
     * @throws {@link TurquoisehealthApi.InternalServerError}
     *
     * @example
     *     await client.consumerPricing.v3GetPackage({
     *         package_id: "GA002"
     *     })
     */
    public v3GetPackage(
        request: TurquoisehealthApi.V3GetPackageRequest,
        requestOptions?: ConsumerPricingClient.RequestOptions,
    ): core.HttpResponsePromise<TurquoisehealthApi.V3Package> {
        return core.HttpResponsePromise.fromPromise(this.__v3GetPackage(request, requestOptions));
    }

    private async __v3GetPackage(
        request: TurquoisehealthApi.V3GetPackageRequest,
        requestOptions?: ConsumerPricingClient.RequestOptions,
    ): Promise<core.WithRawResponse<TurquoisehealthApi.V3Package>> {
        const { package_id: packageId } = request;
        const _authRequest: core.AuthRequest = await this._options.authProvider.getAuthRequest();
        const _headers: core.Fetcher.Args["headers"] = mergeHeaders(
            _authRequest.headers,
            this._options?.headers,
            requestOptions?.headers,
        );
        const _response = await core.fetcher({
            url: core.url.join(
                (await core.Supplier.get(this._options.baseUrl)) ??
                    (await core.Supplier.get(this._options.environment)),
                `v3/packages/${core.url.encodePathParam(packageId)}`,
            ),
            method: "GET",
            headers: _headers,
            queryParameters: requestOptions?.queryParams,
            timeoutMs: (requestOptions?.timeoutInSeconds ?? this._options?.timeoutInSeconds ?? 60) * 1000,
            maxRetries: requestOptions?.maxRetries ?? this._options?.maxRetries,
            abortSignal: requestOptions?.abortSignal,
            fetchFn: this._options?.fetch,
            logging: this._options.logging,
        });
        if (_response.ok) {
            return { data: _response.body as TurquoisehealthApi.V3Package, rawResponse: _response.rawResponse };
        }

        if (_response.error.reason === "status-code") {
            switch (_response.error.statusCode) {
                case 400:
                    throw new TurquoisehealthApi.BadRequestError(
                        _response.error.body as TurquoisehealthApi.V3ErrorResponse,
                        _response.rawResponse,
                    );
                case 404:
                    throw new TurquoisehealthApi.NotFoundError(
                        _response.error.body as TurquoisehealthApi.V3ErrorResponse,
                        _response.rawResponse,
                    );
                case 422:
                    throw new TurquoisehealthApi.UnprocessableEntityError(
                        _response.error.body as TurquoisehealthApi.V3ErrorResponse,
                        _response.rawResponse,
                    );
                case 429:
                    throw new TurquoisehealthApi.TooManyRequestsError(
                        _response.error.body as TurquoisehealthApi.V3ErrorResponse,
                        _response.rawResponse,
                    );
                case 500:
                    throw new TurquoisehealthApi.InternalServerError(
                        _response.error.body as TurquoisehealthApi.V3ErrorResponse,
                        _response.rawResponse,
                    );
                default:
                    throw new errors.TurquoisehealthApiError({
                        statusCode: _response.error.statusCode,
                        body: _response.error.body,
                        rawResponse: _response.rawResponse,
                    });
            }
        }

        switch (_response.error.reason) {
            case "non-json":
                throw new errors.TurquoisehealthApiError({
                    statusCode: _response.error.statusCode,
                    body: _response.error.rawBody,
                    rawResponse: _response.rawResponse,
                });
            case "body-is-null":
                throw new errors.TurquoisehealthApiError({
                    statusCode: _response.error.statusCode,
                    rawResponse: _response.rawResponse,
                });
            case "timeout":
                throw new errors.TurquoisehealthApiTimeoutError(
                    "Timeout exceeded when calling GET /v3/packages/{package_id}.",
                );
            case "unknown":
                throw new errors.TurquoisehealthApiError({
                    message: _response.error.errorMessage,
                    rawResponse: _response.rawResponse,
                });
        }
    }

    /**
     * The package's composition: codes, fee types, and association rates at the current package version.
     *
     * @param {TurquoisehealthApi.V3ListPackageLineItemsRequest} request
     * @param {ConsumerPricingClient.RequestOptions} requestOptions - Request-specific configuration.
     *
     * @throws {@link TurquoisehealthApi.BadRequestError}
     * @throws {@link TurquoisehealthApi.NotFoundError}
     * @throws {@link TurquoisehealthApi.UnprocessableEntityError}
     * @throws {@link TurquoisehealthApi.TooManyRequestsError}
     * @throws {@link TurquoisehealthApi.InternalServerError}
     *
     * @example
     *     await client.consumerPricing.v3ListPackageLineItems({
     *         package_id: "GA002"
     *     })
     */
    public v3ListPackageLineItems(
        request: TurquoisehealthApi.V3ListPackageLineItemsRequest,
        requestOptions?: ConsumerPricingClient.RequestOptions,
    ): core.HttpResponsePromise<TurquoisehealthApi.V3ListEnvelopeLineItem> {
        return core.HttpResponsePromise.fromPromise(this.__v3ListPackageLineItems(request, requestOptions));
    }

    private async __v3ListPackageLineItems(
        request: TurquoisehealthApi.V3ListPackageLineItemsRequest,
        requestOptions?: ConsumerPricingClient.RequestOptions,
    ): Promise<core.WithRawResponse<TurquoisehealthApi.V3ListEnvelopeLineItem>> {
        const { package_id: packageId } = request;
        const _authRequest: core.AuthRequest = await this._options.authProvider.getAuthRequest();
        const _headers: core.Fetcher.Args["headers"] = mergeHeaders(
            _authRequest.headers,
            this._options?.headers,
            requestOptions?.headers,
        );
        const _response = await core.fetcher({
            url: core.url.join(
                (await core.Supplier.get(this._options.baseUrl)) ??
                    (await core.Supplier.get(this._options.environment)),
                `v3/packages/${core.url.encodePathParam(packageId)}/line_items`,
            ),
            method: "GET",
            headers: _headers,
            queryParameters: requestOptions?.queryParams,
            timeoutMs: (requestOptions?.timeoutInSeconds ?? this._options?.timeoutInSeconds ?? 60) * 1000,
            maxRetries: requestOptions?.maxRetries ?? this._options?.maxRetries,
            abortSignal: requestOptions?.abortSignal,
            fetchFn: this._options?.fetch,
            logging: this._options.logging,
        });
        if (_response.ok) {
            return {
                data: _response.body as TurquoisehealthApi.V3ListEnvelopeLineItem,
                rawResponse: _response.rawResponse,
            };
        }

        if (_response.error.reason === "status-code") {
            switch (_response.error.statusCode) {
                case 400:
                    throw new TurquoisehealthApi.BadRequestError(
                        _response.error.body as TurquoisehealthApi.V3ErrorResponse,
                        _response.rawResponse,
                    );
                case 404:
                    throw new TurquoisehealthApi.NotFoundError(
                        _response.error.body as TurquoisehealthApi.V3ErrorResponse,
                        _response.rawResponse,
                    );
                case 422:
                    throw new TurquoisehealthApi.UnprocessableEntityError(
                        _response.error.body as TurquoisehealthApi.V3ErrorResponse,
                        _response.rawResponse,
                    );
                case 429:
                    throw new TurquoisehealthApi.TooManyRequestsError(
                        _response.error.body as TurquoisehealthApi.V3ErrorResponse,
                        _response.rawResponse,
                    );
                case 500:
                    throw new TurquoisehealthApi.InternalServerError(
                        _response.error.body as TurquoisehealthApi.V3ErrorResponse,
                        _response.rawResponse,
                    );
                default:
                    throw new errors.TurquoisehealthApiError({
                        statusCode: _response.error.statusCode,
                        body: _response.error.body,
                        rawResponse: _response.rawResponse,
                    });
            }
        }

        switch (_response.error.reason) {
            case "non-json":
                throw new errors.TurquoisehealthApiError({
                    statusCode: _response.error.statusCode,
                    body: _response.error.rawBody,
                    rawResponse: _response.rawResponse,
                });
            case "body-is-null":
                throw new errors.TurquoisehealthApiError({
                    statusCode: _response.error.statusCode,
                    rawResponse: _response.rawResponse,
                });
            case "timeout":
                throw new errors.TurquoisehealthApiTimeoutError(
                    "Timeout exceeded when calling GET /v3/packages/{package_id}/line_items.",
                );
            case "unknown":
                throw new errors.TurquoisehealthApiError({
                    message: _response.error.errorMessage,
                    rawResponse: _response.rawResponse,
                });
        }
    }

    /**
     * List payers, filterable by name (case-insensitive substring), relationships (provider_id/package_id — payers with at least one matching price), and one location mode: `location.near.*`, `location.within.*` (state/cbsa/zip_codes), or `location.zip`. Location scopes to payers with at least one price at an in-area provider. Results reflect payers Turquoise has priced.
     *
     * @param {TurquoisehealthApi.V3ListPayersRequest} request
     * @param {ConsumerPricingClient.RequestOptions} requestOptions - Request-specific configuration.
     *
     * @throws {@link TurquoisehealthApi.BadRequestError}
     * @throws {@link TurquoisehealthApi.NotFoundError}
     * @throws {@link TurquoisehealthApi.UnprocessableEntityError}
     * @throws {@link TurquoisehealthApi.TooManyRequestsError}
     * @throws {@link TurquoisehealthApi.InternalServerError}
     *
     * @example
     *     await client.consumerPricing.v3ListPayers()
     */
    public v3ListPayers(
        request: TurquoisehealthApi.V3ListPayersRequest = {},
        requestOptions?: ConsumerPricingClient.RequestOptions,
    ): core.HttpResponsePromise<TurquoisehealthApi.V3ListEnvelopePayer> {
        return core.HttpResponsePromise.fromPromise(this.__v3ListPayers(request, requestOptions));
    }

    private async __v3ListPayers(
        request: TurquoisehealthApi.V3ListPayersRequest = {},
        requestOptions?: ConsumerPricingClient.RequestOptions,
    ): Promise<core.WithRawResponse<TurquoisehealthApi.V3ListEnvelopePayer>> {
        const {
            name,
            provider_id: providerId,
            package_id: packageId,
            page_size: pageSize,
            cursor,
            "location.near.lat": locationNearLat,
            "location.near.lng": locationNearLng,
            "location.near.radius_m": locationNearRadiusM,
            "location.within.state": locationWithinState,
            "location.within.cbsa": locationWithinCbsa,
            "location.within.zip_codes": locationWithinZipCodes,
            "location.zip": locationZip,
        } = request;
        const _queryParams: Record<string, string | string[] | object | object[] | null> = {};
        if (name !== undefined) {
            _queryParams.name = name;
        }

        if (providerId !== undefined) {
            _queryParams.provider_id = providerId;
        }

        if (packageId !== undefined) {
            _queryParams.package_id = packageId;
        }

        if (pageSize != null) {
            _queryParams.page_size = pageSize.toString();
        }

        if (cursor !== undefined) {
            _queryParams.cursor = cursor;
        }

        if (locationNearLat !== undefined) {
            _queryParams["location.near.lat"] = locationNearLat?.toString() ?? null;
        }

        if (locationNearLng !== undefined) {
            _queryParams["location.near.lng"] = locationNearLng?.toString() ?? null;
        }

        if (locationNearRadiusM !== undefined) {
            _queryParams["location.near.radius_m"] = locationNearRadiusM?.toString() ?? null;
        }

        if (locationWithinState !== undefined) {
            _queryParams["location.within.state"] = locationWithinState;
        }

        if (locationWithinCbsa !== undefined) {
            _queryParams["location.within.cbsa"] = locationWithinCbsa;
        }

        if (locationWithinZipCodes !== undefined) {
            _queryParams["location.within.zip_codes"] = locationWithinZipCodes;
        }

        if (locationZip !== undefined) {
            _queryParams["location.zip"] = locationZip;
        }

        const _authRequest: core.AuthRequest = await this._options.authProvider.getAuthRequest();
        const _headers: core.Fetcher.Args["headers"] = mergeHeaders(
            _authRequest.headers,
            this._options?.headers,
            requestOptions?.headers,
        );
        const _response = await core.fetcher({
            url: core.url.join(
                (await core.Supplier.get(this._options.baseUrl)) ??
                    (await core.Supplier.get(this._options.environment)),
                "v3/payers",
            ),
            method: "GET",
            headers: _headers,
            queryParameters: { ..._queryParams, ...requestOptions?.queryParams },
            timeoutMs: (requestOptions?.timeoutInSeconds ?? this._options?.timeoutInSeconds ?? 60) * 1000,
            maxRetries: requestOptions?.maxRetries ?? this._options?.maxRetries,
            abortSignal: requestOptions?.abortSignal,
            fetchFn: this._options?.fetch,
            logging: this._options.logging,
        });
        if (_response.ok) {
            return {
                data: _response.body as TurquoisehealthApi.V3ListEnvelopePayer,
                rawResponse: _response.rawResponse,
            };
        }

        if (_response.error.reason === "status-code") {
            switch (_response.error.statusCode) {
                case 400:
                    throw new TurquoisehealthApi.BadRequestError(
                        _response.error.body as TurquoisehealthApi.V3ErrorResponse,
                        _response.rawResponse,
                    );
                case 404:
                    throw new TurquoisehealthApi.NotFoundError(
                        _response.error.body as TurquoisehealthApi.V3ErrorResponse,
                        _response.rawResponse,
                    );
                case 422:
                    throw new TurquoisehealthApi.UnprocessableEntityError(
                        _response.error.body as TurquoisehealthApi.V3ErrorResponse,
                        _response.rawResponse,
                    );
                case 429:
                    throw new TurquoisehealthApi.TooManyRequestsError(
                        _response.error.body as TurquoisehealthApi.V3ErrorResponse,
                        _response.rawResponse,
                    );
                case 500:
                    throw new TurquoisehealthApi.InternalServerError(
                        _response.error.body as TurquoisehealthApi.V3ErrorResponse,
                        _response.rawResponse,
                    );
                default:
                    throw new errors.TurquoisehealthApiError({
                        statusCode: _response.error.statusCode,
                        body: _response.error.body,
                        rawResponse: _response.rawResponse,
                    });
            }
        }

        switch (_response.error.reason) {
            case "non-json":
                throw new errors.TurquoisehealthApiError({
                    statusCode: _response.error.statusCode,
                    body: _response.error.rawBody,
                    rawResponse: _response.rawResponse,
                });
            case "body-is-null":
                throw new errors.TurquoisehealthApiError({
                    statusCode: _response.error.statusCode,
                    rawResponse: _response.rawResponse,
                });
            case "timeout":
                throw new errors.TurquoisehealthApiTimeoutError("Timeout exceeded when calling GET /v3/payers.");
            case "unknown":
                throw new errors.TurquoisehealthApiError({
                    message: _response.error.errorMessage,
                    rawResponse: _response.rawResponse,
                });
        }
    }

    /**
     * Fetch a single payer by ID. Missing or unpermissioned IDs return a 404 with the standard error body.
     *
     * @param {TurquoisehealthApi.V3GetPayerRequest} request
     * @param {ConsumerPricingClient.RequestOptions} requestOptions - Request-specific configuration.
     *
     * @throws {@link TurquoisehealthApi.BadRequestError}
     * @throws {@link TurquoisehealthApi.NotFoundError}
     * @throws {@link TurquoisehealthApi.UnprocessableEntityError}
     * @throws {@link TurquoisehealthApi.TooManyRequestsError}
     * @throws {@link TurquoisehealthApi.InternalServerError}
     *
     * @example
     *     await client.consumerPricing.v3GetPayer({
     *         payer_id: "7001"
     *     })
     */
    public v3GetPayer(
        request: TurquoisehealthApi.V3GetPayerRequest,
        requestOptions?: ConsumerPricingClient.RequestOptions,
    ): core.HttpResponsePromise<TurquoisehealthApi.V3Payer> {
        return core.HttpResponsePromise.fromPromise(this.__v3GetPayer(request, requestOptions));
    }

    private async __v3GetPayer(
        request: TurquoisehealthApi.V3GetPayerRequest,
        requestOptions?: ConsumerPricingClient.RequestOptions,
    ): Promise<core.WithRawResponse<TurquoisehealthApi.V3Payer>> {
        const { payer_id: payerId } = request;
        const _authRequest: core.AuthRequest = await this._options.authProvider.getAuthRequest();
        const _headers: core.Fetcher.Args["headers"] = mergeHeaders(
            _authRequest.headers,
            this._options?.headers,
            requestOptions?.headers,
        );
        const _response = await core.fetcher({
            url: core.url.join(
                (await core.Supplier.get(this._options.baseUrl)) ??
                    (await core.Supplier.get(this._options.environment)),
                `v3/payers/${core.url.encodePathParam(payerId)}`,
            ),
            method: "GET",
            headers: _headers,
            queryParameters: requestOptions?.queryParams,
            timeoutMs: (requestOptions?.timeoutInSeconds ?? this._options?.timeoutInSeconds ?? 60) * 1000,
            maxRetries: requestOptions?.maxRetries ?? this._options?.maxRetries,
            abortSignal: requestOptions?.abortSignal,
            fetchFn: this._options?.fetch,
            logging: this._options.logging,
        });
        if (_response.ok) {
            return { data: _response.body as TurquoisehealthApi.V3Payer, rawResponse: _response.rawResponse };
        }

        if (_response.error.reason === "status-code") {
            switch (_response.error.statusCode) {
                case 400:
                    throw new TurquoisehealthApi.BadRequestError(
                        _response.error.body as TurquoisehealthApi.V3ErrorResponse,
                        _response.rawResponse,
                    );
                case 404:
                    throw new TurquoisehealthApi.NotFoundError(
                        _response.error.body as TurquoisehealthApi.V3ErrorResponse,
                        _response.rawResponse,
                    );
                case 422:
                    throw new TurquoisehealthApi.UnprocessableEntityError(
                        _response.error.body as TurquoisehealthApi.V3ErrorResponse,
                        _response.rawResponse,
                    );
                case 429:
                    throw new TurquoisehealthApi.TooManyRequestsError(
                        _response.error.body as TurquoisehealthApi.V3ErrorResponse,
                        _response.rawResponse,
                    );
                case 500:
                    throw new TurquoisehealthApi.InternalServerError(
                        _response.error.body as TurquoisehealthApi.V3ErrorResponse,
                        _response.rawResponse,
                    );
                default:
                    throw new errors.TurquoisehealthApiError({
                        statusCode: _response.error.statusCode,
                        body: _response.error.body,
                        rawResponse: _response.rawResponse,
                    });
            }
        }

        switch (_response.error.reason) {
            case "non-json":
                throw new errors.TurquoisehealthApiError({
                    statusCode: _response.error.statusCode,
                    body: _response.error.rawBody,
                    rawResponse: _response.rawResponse,
                });
            case "body-is-null":
                throw new errors.TurquoisehealthApiError({
                    statusCode: _response.error.statusCode,
                    rawResponse: _response.rawResponse,
                });
            case "timeout":
                throw new errors.TurquoisehealthApiTimeoutError(
                    "Timeout exceeded when calling GET /v3/payers/{payer_id}.",
                );
            case "unknown":
                throw new errors.TurquoisehealthApiError({
                    message: _response.error.errorMessage,
                    rawResponse: _response.rawResponse,
                });
        }
    }

    /**
     * Search prices at the provider × package × pricing grain.
     *
     * @param {TurquoisehealthApi.V3PricesQueryRequest} request
     * @param {ConsumerPricingClient.RequestOptions} requestOptions - Request-specific configuration.
     *
     * @throws {@link TurquoisehealthApi.BadRequestError}
     * @throws {@link TurquoisehealthApi.NotFoundError}
     * @throws {@link TurquoisehealthApi.UnprocessableEntityError}
     * @throws {@link TurquoisehealthApi.TooManyRequestsError}
     * @throws {@link TurquoisehealthApi.InternalServerError}
     *
     * @example
     *     await client.consumerPricing.v3QueryPrices({
     *         package_id: "RA007",
     *         provider_id: "2751",
     *         pricing: {
     *             type: "negotiated",
     *             network_id: "network_id"
     *         }
     *     })
     *
     * @example
     *     await client.consumerPricing.v3QueryPrices({
     *         package_id: "RA007",
     *         provider_id: "2751",
     *         pricing: {
     *             type: "cash"
     *         }
     *     })
     *
     * @example
     *     await client.consumerPricing.v3QueryPrices({
     *         package_id: "RA007",
     *         pricing: {
     *             type: "cash"
     *         },
     *         location: {
     *             near: {
     *                 lat: 41.8781,
     *                 lng: -87.6298,
     *                 radius_m: 40000
     *             }
     *         },
     *         sort: "distance"
     *     })
     *
     * @example
     *     await client.consumerPricing.v3QueryPrices({
     *         package_id: "RA007",
     *         pricing: {
     *             type: "cash"
     *         },
     *         location: {
     *             zip: "60644"
     *         }
     *     })
     *
     * @example
     *     await client.consumerPricing.v3QueryPrices({
     *         package_id: "RA007",
     *         pricing: {
     *             type: "negotiated",
     *             network_id: "network_id"
     *         },
     *         location: {
     *             within: {
     *                 state: "IL"
     *             }
     *         }
     *     })
     */
    public v3QueryPrices(
        request: TurquoisehealthApi.V3PricesQueryRequest,
        requestOptions?: ConsumerPricingClient.RequestOptions,
    ): core.HttpResponsePromise<TurquoisehealthApi.V3ListEnvelopeProviderPackagePrice> {
        return core.HttpResponsePromise.fromPromise(this.__v3QueryPrices(request, requestOptions));
    }

    private async __v3QueryPrices(
        request: TurquoisehealthApi.V3PricesQueryRequest,
        requestOptions?: ConsumerPricingClient.RequestOptions,
    ): Promise<core.WithRawResponse<TurquoisehealthApi.V3ListEnvelopeProviderPackagePrice>> {
        const _authRequest: core.AuthRequest = await this._options.authProvider.getAuthRequest();
        const _headers: core.Fetcher.Args["headers"] = mergeHeaders(
            _authRequest.headers,
            this._options?.headers,
            requestOptions?.headers,
        );
        const _response = await core.fetcher({
            url: core.url.join(
                (await core.Supplier.get(this._options.baseUrl)) ??
                    (await core.Supplier.get(this._options.environment)),
                "v3/prices/query",
            ),
            method: "POST",
            headers: _headers,
            contentType: "application/json",
            queryParameters: requestOptions?.queryParams,
            requestType: "json",
            body: request,
            timeoutMs: (requestOptions?.timeoutInSeconds ?? this._options?.timeoutInSeconds ?? 60) * 1000,
            maxRetries: requestOptions?.maxRetries ?? this._options?.maxRetries,
            abortSignal: requestOptions?.abortSignal,
            fetchFn: this._options?.fetch,
            logging: this._options.logging,
        });
        if (_response.ok) {
            return {
                data: _response.body as TurquoisehealthApi.V3ListEnvelopeProviderPackagePrice,
                rawResponse: _response.rawResponse,
            };
        }

        if (_response.error.reason === "status-code") {
            switch (_response.error.statusCode) {
                case 400:
                    throw new TurquoisehealthApi.BadRequestError(
                        _response.error.body as TurquoisehealthApi.V3ErrorResponse,
                        _response.rawResponse,
                    );
                case 404:
                    throw new TurquoisehealthApi.NotFoundError(
                        _response.error.body as TurquoisehealthApi.V3ErrorResponse,
                        _response.rawResponse,
                    );
                case 422:
                    throw new TurquoisehealthApi.UnprocessableEntityError(
                        _response.error.body as TurquoisehealthApi.V3ErrorResponse,
                        _response.rawResponse,
                    );
                case 429:
                    throw new TurquoisehealthApi.TooManyRequestsError(
                        _response.error.body as TurquoisehealthApi.V3ErrorResponse,
                        _response.rawResponse,
                    );
                case 500:
                    throw new TurquoisehealthApi.InternalServerError(
                        _response.error.body as TurquoisehealthApi.V3ErrorResponse,
                        _response.rawResponse,
                    );
                default:
                    throw new errors.TurquoisehealthApiError({
                        statusCode: _response.error.statusCode,
                        body: _response.error.body,
                        rawResponse: _response.rawResponse,
                    });
            }
        }

        switch (_response.error.reason) {
            case "non-json":
                throw new errors.TurquoisehealthApiError({
                    statusCode: _response.error.statusCode,
                    body: _response.error.rawBody,
                    rawResponse: _response.rawResponse,
                });
            case "body-is-null":
                throw new errors.TurquoisehealthApiError({
                    statusCode: _response.error.statusCode,
                    rawResponse: _response.rawResponse,
                });
            case "timeout":
                throw new errors.TurquoisehealthApiTimeoutError("Timeout exceeded when calling POST /v3/prices/query.");
            case "unknown":
                throw new errors.TurquoisehealthApiError({
                    message: _response.error.errorMessage,
                    rawResponse: _response.rawResponse,
                });
        }
    }

    /**
     * Summary statistics (count, min/max/avg/median/q1/q3 as Money) over the prices matching the same request shape as /query, minus sort and pagination.
     *
     * @param {TurquoisehealthApi.V3PricesCompareRequest} request
     * @param {ConsumerPricingClient.RequestOptions} requestOptions - Request-specific configuration.
     *
     * @throws {@link TurquoisehealthApi.BadRequestError}
     * @throws {@link TurquoisehealthApi.NotFoundError}
     * @throws {@link TurquoisehealthApi.UnprocessableEntityError}
     * @throws {@link TurquoisehealthApi.TooManyRequestsError}
     * @throws {@link TurquoisehealthApi.InternalServerError}
     *
     * @example
     *     await client.consumerPricing.v3ComparePrices({
     *         package_id: "RA007",
     *         provider_id: "2751",
     *         pricing: {
     *             type: "negotiated",
     *             network_id: "network_id"
     *         }
     *     })
     *
     * @example
     *     await client.consumerPricing.v3ComparePrices({
     *         package_id: "RA007",
     *         pricing: {
     *             type: "cash"
     *         },
     *         location: {
     *             within: {
     *                 state: "IL"
     *             }
     *         }
     *     })
     *
     * @example
     *     await client.consumerPricing.v3ComparePrices({
     *         package_id: "RA007",
     *         pricing: {
     *             type: "cash"
     *         },
     *         location: {
     *             near: {
     *                 lat: 41.8781,
     *                 lng: -87.6298,
     *                 radius_m: 40000
     *             }
     *         }
     *     })
     */
    public v3ComparePrices(
        request: TurquoisehealthApi.V3PricesCompareRequest,
        requestOptions?: ConsumerPricingClient.RequestOptions,
    ): core.HttpResponsePromise<TurquoisehealthApi.V3PriceComparison> {
        return core.HttpResponsePromise.fromPromise(this.__v3ComparePrices(request, requestOptions));
    }

    private async __v3ComparePrices(
        request: TurquoisehealthApi.V3PricesCompareRequest,
        requestOptions?: ConsumerPricingClient.RequestOptions,
    ): Promise<core.WithRawResponse<TurquoisehealthApi.V3PriceComparison>> {
        const _authRequest: core.AuthRequest = await this._options.authProvider.getAuthRequest();
        const _headers: core.Fetcher.Args["headers"] = mergeHeaders(
            _authRequest.headers,
            this._options?.headers,
            requestOptions?.headers,
        );
        const _response = await core.fetcher({
            url: core.url.join(
                (await core.Supplier.get(this._options.baseUrl)) ??
                    (await core.Supplier.get(this._options.environment)),
                "v3/prices/compare",
            ),
            method: "POST",
            headers: _headers,
            contentType: "application/json",
            queryParameters: requestOptions?.queryParams,
            requestType: "json",
            body: request,
            timeoutMs: (requestOptions?.timeoutInSeconds ?? this._options?.timeoutInSeconds ?? 60) * 1000,
            maxRetries: requestOptions?.maxRetries ?? this._options?.maxRetries,
            abortSignal: requestOptions?.abortSignal,
            fetchFn: this._options?.fetch,
            logging: this._options.logging,
        });
        if (_response.ok) {
            return { data: _response.body as TurquoisehealthApi.V3PriceComparison, rawResponse: _response.rawResponse };
        }

        if (_response.error.reason === "status-code") {
            switch (_response.error.statusCode) {
                case 400:
                    throw new TurquoisehealthApi.BadRequestError(
                        _response.error.body as TurquoisehealthApi.V3ErrorResponse,
                        _response.rawResponse,
                    );
                case 404:
                    throw new TurquoisehealthApi.NotFoundError(
                        _response.error.body as TurquoisehealthApi.V3ErrorResponse,
                        _response.rawResponse,
                    );
                case 422:
                    throw new TurquoisehealthApi.UnprocessableEntityError(
                        _response.error.body as TurquoisehealthApi.V3ErrorResponse,
                        _response.rawResponse,
                    );
                case 429:
                    throw new TurquoisehealthApi.TooManyRequestsError(
                        _response.error.body as TurquoisehealthApi.V3ErrorResponse,
                        _response.rawResponse,
                    );
                case 500:
                    throw new TurquoisehealthApi.InternalServerError(
                        _response.error.body as TurquoisehealthApi.V3ErrorResponse,
                        _response.rawResponse,
                    );
                default:
                    throw new errors.TurquoisehealthApiError({
                        statusCode: _response.error.statusCode,
                        body: _response.error.body,
                        rawResponse: _response.rawResponse,
                    });
            }
        }

        switch (_response.error.reason) {
            case "non-json":
                throw new errors.TurquoisehealthApiError({
                    statusCode: _response.error.statusCode,
                    body: _response.error.rawBody,
                    rawResponse: _response.rawResponse,
                });
            case "body-is-null":
                throw new errors.TurquoisehealthApiError({
                    statusCode: _response.error.statusCode,
                    rawResponse: _response.rawResponse,
                });
            case "timeout":
                throw new errors.TurquoisehealthApiTimeoutError(
                    "Timeout exceeded when calling POST /v3/prices/compare.",
                );
            case "unknown":
                throw new errors.TurquoisehealthApiError({
                    message: _response.error.errorMessage,
                    rawResponse: _response.rawResponse,
                });
        }
    }

    /**
     * Fetch a single price by its ID (the id returned by /query). `expand=line_items` attaches the package composition — this replaces v2's provider-breakdown endpoint.
     *
     * @param {TurquoisehealthApi.V3GetPriceRequest} request
     * @param {ConsumerPricingClient.RequestOptions} requestOptions - Request-specific configuration.
     *
     * @throws {@link TurquoisehealthApi.BadRequestError}
     * @throws {@link TurquoisehealthApi.NotFoundError}
     * @throws {@link TurquoisehealthApi.UnprocessableEntityError}
     * @throws {@link TurquoisehealthApi.TooManyRequestsError}
     * @throws {@link TurquoisehealthApi.InternalServerError}
     *
     * @example
     *     await client.consumerPricing.v3GetPrice({
     *         price_id: "prc_2751.RA007.8361580493441765265"
     *     })
     */
    public v3GetPrice(
        request: TurquoisehealthApi.V3GetPriceRequest,
        requestOptions?: ConsumerPricingClient.RequestOptions,
    ): core.HttpResponsePromise<TurquoisehealthApi.V3ProviderPackagePrice> {
        return core.HttpResponsePromise.fromPromise(this.__v3GetPrice(request, requestOptions));
    }

    private async __v3GetPrice(
        request: TurquoisehealthApi.V3GetPriceRequest,
        requestOptions?: ConsumerPricingClient.RequestOptions,
    ): Promise<core.WithRawResponse<TurquoisehealthApi.V3ProviderPackagePrice>> {
        const { price_id: priceId, expand } = request;
        const _queryParams: Record<string, string | string[] | object | object[] | null> = {};
        if (expand !== undefined) {
            _queryParams.expand = toJson(expand);
        }

        const _authRequest: core.AuthRequest = await this._options.authProvider.getAuthRequest();
        const _headers: core.Fetcher.Args["headers"] = mergeHeaders(
            _authRequest.headers,
            this._options?.headers,
            requestOptions?.headers,
        );
        const _response = await core.fetcher({
            url: core.url.join(
                (await core.Supplier.get(this._options.baseUrl)) ??
                    (await core.Supplier.get(this._options.environment)),
                `v3/prices/${core.url.encodePathParam(priceId)}`,
            ),
            method: "GET",
            headers: _headers,
            queryParameters: { ..._queryParams, ...requestOptions?.queryParams },
            timeoutMs: (requestOptions?.timeoutInSeconds ?? this._options?.timeoutInSeconds ?? 60) * 1000,
            maxRetries: requestOptions?.maxRetries ?? this._options?.maxRetries,
            abortSignal: requestOptions?.abortSignal,
            fetchFn: this._options?.fetch,
            logging: this._options.logging,
        });
        if (_response.ok) {
            return {
                data: _response.body as TurquoisehealthApi.V3ProviderPackagePrice,
                rawResponse: _response.rawResponse,
            };
        }

        if (_response.error.reason === "status-code") {
            switch (_response.error.statusCode) {
                case 400:
                    throw new TurquoisehealthApi.BadRequestError(
                        _response.error.body as TurquoisehealthApi.V3ErrorResponse,
                        _response.rawResponse,
                    );
                case 404:
                    throw new TurquoisehealthApi.NotFoundError(
                        _response.error.body as TurquoisehealthApi.V3ErrorResponse,
                        _response.rawResponse,
                    );
                case 422:
                    throw new TurquoisehealthApi.UnprocessableEntityError(
                        _response.error.body as TurquoisehealthApi.V3ErrorResponse,
                        _response.rawResponse,
                    );
                case 429:
                    throw new TurquoisehealthApi.TooManyRequestsError(
                        _response.error.body as TurquoisehealthApi.V3ErrorResponse,
                        _response.rawResponse,
                    );
                case 500:
                    throw new TurquoisehealthApi.InternalServerError(
                        _response.error.body as TurquoisehealthApi.V3ErrorResponse,
                        _response.rawResponse,
                    );
                default:
                    throw new errors.TurquoisehealthApiError({
                        statusCode: _response.error.statusCode,
                        body: _response.error.body,
                        rawResponse: _response.rawResponse,
                    });
            }
        }

        switch (_response.error.reason) {
            case "non-json":
                throw new errors.TurquoisehealthApiError({
                    statusCode: _response.error.statusCode,
                    body: _response.error.rawBody,
                    rawResponse: _response.rawResponse,
                });
            case "body-is-null":
                throw new errors.TurquoisehealthApiError({
                    statusCode: _response.error.statusCode,
                    rawResponse: _response.rawResponse,
                });
            case "timeout":
                throw new errors.TurquoisehealthApiTimeoutError(
                    "Timeout exceeded when calling GET /v3/prices/{price_id}.",
                );
            case "unknown":
                throw new errors.TurquoisehealthApiError({
                    message: _response.error.errorMessage,
                    rawResponse: _response.rawResponse,
                });
        }
    }

    /**
     * Fetch provider types
     *
     * @param {ConsumerPricingClient.RequestOptions} requestOptions - Request-specific configuration.
     *
     * @throws {@link TurquoisehealthApi.BadRequestError}
     * @throws {@link TurquoisehealthApi.NotFoundError}
     * @throws {@link TurquoisehealthApi.UnprocessableEntityError}
     * @throws {@link TurquoisehealthApi.TooManyRequestsError}
     * @throws {@link TurquoisehealthApi.InternalServerError}
     *
     * @example
     *     await client.consumerPricing.v3GetProviderTypes()
     */
    public v3GetProviderTypes(
        requestOptions?: ConsumerPricingClient.RequestOptions,
    ): core.HttpResponsePromise<string[]> {
        return core.HttpResponsePromise.fromPromise(this.__v3GetProviderTypes(requestOptions));
    }

    private async __v3GetProviderTypes(
        requestOptions?: ConsumerPricingClient.RequestOptions,
    ): Promise<core.WithRawResponse<string[]>> {
        const _authRequest: core.AuthRequest = await this._options.authProvider.getAuthRequest();
        const _headers: core.Fetcher.Args["headers"] = mergeHeaders(
            _authRequest.headers,
            this._options?.headers,
            requestOptions?.headers,
        );
        const _response = await core.fetcher({
            url: core.url.join(
                (await core.Supplier.get(this._options.baseUrl)) ??
                    (await core.Supplier.get(this._options.environment)),
                "v3/providers/types",
            ),
            method: "GET",
            headers: _headers,
            queryParameters: requestOptions?.queryParams,
            timeoutMs: (requestOptions?.timeoutInSeconds ?? this._options?.timeoutInSeconds ?? 60) * 1000,
            maxRetries: requestOptions?.maxRetries ?? this._options?.maxRetries,
            abortSignal: requestOptions?.abortSignal,
            fetchFn: this._options?.fetch,
            logging: this._options.logging,
        });
        if (_response.ok) {
            return { data: _response.body as string[], rawResponse: _response.rawResponse };
        }

        if (_response.error.reason === "status-code") {
            switch (_response.error.statusCode) {
                case 400:
                    throw new TurquoisehealthApi.BadRequestError(
                        _response.error.body as TurquoisehealthApi.V3ErrorResponse,
                        _response.rawResponse,
                    );
                case 404:
                    throw new TurquoisehealthApi.NotFoundError(
                        _response.error.body as TurquoisehealthApi.V3ErrorResponse,
                        _response.rawResponse,
                    );
                case 422:
                    throw new TurquoisehealthApi.UnprocessableEntityError(
                        _response.error.body as TurquoisehealthApi.V3ErrorResponse,
                        _response.rawResponse,
                    );
                case 429:
                    throw new TurquoisehealthApi.TooManyRequestsError(
                        _response.error.body as TurquoisehealthApi.V3ErrorResponse,
                        _response.rawResponse,
                    );
                case 500:
                    throw new TurquoisehealthApi.InternalServerError(
                        _response.error.body as TurquoisehealthApi.V3ErrorResponse,
                        _response.rawResponse,
                    );
                default:
                    throw new errors.TurquoisehealthApiError({
                        statusCode: _response.error.statusCode,
                        body: _response.error.body,
                        rawResponse: _response.rawResponse,
                    });
            }
        }

        switch (_response.error.reason) {
            case "non-json":
                throw new errors.TurquoisehealthApiError({
                    statusCode: _response.error.statusCode,
                    body: _response.error.rawBody,
                    rawResponse: _response.rawResponse,
                });
            case "body-is-null":
                throw new errors.TurquoisehealthApiError({
                    statusCode: _response.error.statusCode,
                    rawResponse: _response.rawResponse,
                });
            case "timeout":
                throw new errors.TurquoisehealthApiTimeoutError(
                    "Timeout exceeded when calling GET /v3/providers/types.",
                );
            case "unknown":
                throw new errors.TurquoisehealthApiError({
                    message: _response.error.errorMessage,
                    rawResponse: _response.rawResponse,
                });
        }
    }

    /**
     * List providers, filterable by name (case-insensitive substring), npi/type (exact), relationships (package_id/network_id/payer_id — providers with at least one matching price; combined relationship filters must be satisfied by the same price row, so results are always fulfillable via GET /v3/prices), and one location mode: `location.near.*` (ranked by distance), `location.within.*` (state/cbsa/zip_codes), or `location.zip` (ZIP centroid + default 25km radius). Results reflect providers Turquoise has priced services for.
     *
     * @param {TurquoisehealthApi.V3ListProvidersRequest} request
     * @param {ConsumerPricingClient.RequestOptions} requestOptions - Request-specific configuration.
     *
     * @throws {@link TurquoisehealthApi.BadRequestError}
     * @throws {@link TurquoisehealthApi.NotFoundError}
     * @throws {@link TurquoisehealthApi.UnprocessableEntityError}
     * @throws {@link TurquoisehealthApi.TooManyRequestsError}
     * @throws {@link TurquoisehealthApi.InternalServerError}
     *
     * @example
     *     await client.consumerPricing.v3ListProviders()
     */
    public v3ListProviders(
        request: TurquoisehealthApi.V3ListProvidersRequest = {},
        requestOptions?: ConsumerPricingClient.RequestOptions,
    ): core.HttpResponsePromise<TurquoisehealthApi.V3ListEnvelopeProvider> {
        return core.HttpResponsePromise.fromPromise(this.__v3ListProviders(request, requestOptions));
    }

    private async __v3ListProviders(
        request: TurquoisehealthApi.V3ListProvidersRequest = {},
        requestOptions?: ConsumerPricingClient.RequestOptions,
    ): Promise<core.WithRawResponse<TurquoisehealthApi.V3ListEnvelopeProvider>> {
        const {
            name,
            npi,
            type: type_,
            package_id: packageId,
            network_id: networkId,
            payer_id: payerId,
            search,
            min_score: minScore,
            page_size: pageSize,
            cursor,
            "location.near.lat": locationNearLat,
            "location.near.lng": locationNearLng,
            "location.near.radius_m": locationNearRadiusM,
            "location.within.state": locationWithinState,
            "location.within.cbsa": locationWithinCbsa,
            "location.within.zip_codes": locationWithinZipCodes,
            "location.zip": locationZip,
        } = request;
        const _queryParams: Record<string, string | string[] | object | object[] | null> = {};
        if (name !== undefined) {
            _queryParams.name = name;
        }

        if (npi !== undefined) {
            _queryParams.npi = npi;
        }

        if (type_ !== undefined) {
            _queryParams.type = type_;
        }

        if (packageId !== undefined) {
            _queryParams.package_id = packageId;
        }

        if (networkId !== undefined) {
            _queryParams.network_id = networkId;
        }

        if (payerId !== undefined) {
            _queryParams.payer_id = payerId;
        }

        if (search !== undefined) {
            _queryParams.search = search;
        }

        if (minScore !== undefined) {
            _queryParams.min_score = minScore?.toString() ?? null;
        }

        if (pageSize != null) {
            _queryParams.page_size = pageSize.toString();
        }

        if (cursor !== undefined) {
            _queryParams.cursor = cursor;
        }

        if (locationNearLat !== undefined) {
            _queryParams["location.near.lat"] = locationNearLat?.toString() ?? null;
        }

        if (locationNearLng !== undefined) {
            _queryParams["location.near.lng"] = locationNearLng?.toString() ?? null;
        }

        if (locationNearRadiusM !== undefined) {
            _queryParams["location.near.radius_m"] = locationNearRadiusM?.toString() ?? null;
        }

        if (locationWithinState !== undefined) {
            _queryParams["location.within.state"] = locationWithinState;
        }

        if (locationWithinCbsa !== undefined) {
            _queryParams["location.within.cbsa"] = locationWithinCbsa;
        }

        if (locationWithinZipCodes !== undefined) {
            _queryParams["location.within.zip_codes"] = locationWithinZipCodes;
        }

        if (locationZip !== undefined) {
            _queryParams["location.zip"] = locationZip;
        }

        const _authRequest: core.AuthRequest = await this._options.authProvider.getAuthRequest();
        const _headers: core.Fetcher.Args["headers"] = mergeHeaders(
            _authRequest.headers,
            this._options?.headers,
            requestOptions?.headers,
        );
        const _response = await core.fetcher({
            url: core.url.join(
                (await core.Supplier.get(this._options.baseUrl)) ??
                    (await core.Supplier.get(this._options.environment)),
                "v3/providers",
            ),
            method: "GET",
            headers: _headers,
            queryParameters: { ..._queryParams, ...requestOptions?.queryParams },
            timeoutMs: (requestOptions?.timeoutInSeconds ?? this._options?.timeoutInSeconds ?? 60) * 1000,
            maxRetries: requestOptions?.maxRetries ?? this._options?.maxRetries,
            abortSignal: requestOptions?.abortSignal,
            fetchFn: this._options?.fetch,
            logging: this._options.logging,
        });
        if (_response.ok) {
            return {
                data: _response.body as TurquoisehealthApi.V3ListEnvelopeProvider,
                rawResponse: _response.rawResponse,
            };
        }

        if (_response.error.reason === "status-code") {
            switch (_response.error.statusCode) {
                case 400:
                    throw new TurquoisehealthApi.BadRequestError(
                        _response.error.body as TurquoisehealthApi.V3ErrorResponse,
                        _response.rawResponse,
                    );
                case 404:
                    throw new TurquoisehealthApi.NotFoundError(
                        _response.error.body as TurquoisehealthApi.V3ErrorResponse,
                        _response.rawResponse,
                    );
                case 422:
                    throw new TurquoisehealthApi.UnprocessableEntityError(
                        _response.error.body as TurquoisehealthApi.V3ErrorResponse,
                        _response.rawResponse,
                    );
                case 429:
                    throw new TurquoisehealthApi.TooManyRequestsError(
                        _response.error.body as TurquoisehealthApi.V3ErrorResponse,
                        _response.rawResponse,
                    );
                case 500:
                    throw new TurquoisehealthApi.InternalServerError(
                        _response.error.body as TurquoisehealthApi.V3ErrorResponse,
                        _response.rawResponse,
                    );
                default:
                    throw new errors.TurquoisehealthApiError({
                        statusCode: _response.error.statusCode,
                        body: _response.error.body,
                        rawResponse: _response.rawResponse,
                    });
            }
        }

        switch (_response.error.reason) {
            case "non-json":
                throw new errors.TurquoisehealthApiError({
                    statusCode: _response.error.statusCode,
                    body: _response.error.rawBody,
                    rawResponse: _response.rawResponse,
                });
            case "body-is-null":
                throw new errors.TurquoisehealthApiError({
                    statusCode: _response.error.statusCode,
                    rawResponse: _response.rawResponse,
                });
            case "timeout":
                throw new errors.TurquoisehealthApiTimeoutError("Timeout exceeded when calling GET /v3/providers.");
            case "unknown":
                throw new errors.TurquoisehealthApiError({
                    message: _response.error.errorMessage,
                    rawResponse: _response.rawResponse,
                });
        }
    }

    /**
     * Fetch a single provider by ID. Missing IDs return a 404 with the standard error body.
     *
     * @param {TurquoisehealthApi.V3GetProviderRequest} request
     * @param {ConsumerPricingClient.RequestOptions} requestOptions - Request-specific configuration.
     *
     * @throws {@link TurquoisehealthApi.BadRequestError}
     * @throws {@link TurquoisehealthApi.NotFoundError}
     * @throws {@link TurquoisehealthApi.UnprocessableEntityError}
     * @throws {@link TurquoisehealthApi.TooManyRequestsError}
     * @throws {@link TurquoisehealthApi.InternalServerError}
     *
     * @example
     *     await client.consumerPricing.v3GetProvider({
     *         provider_id: "2743"
     *     })
     */
    public v3GetProvider(
        request: TurquoisehealthApi.V3GetProviderRequest,
        requestOptions?: ConsumerPricingClient.RequestOptions,
    ): core.HttpResponsePromise<TurquoisehealthApi.V3Provider> {
        return core.HttpResponsePromise.fromPromise(this.__v3GetProvider(request, requestOptions));
    }

    private async __v3GetProvider(
        request: TurquoisehealthApi.V3GetProviderRequest,
        requestOptions?: ConsumerPricingClient.RequestOptions,
    ): Promise<core.WithRawResponse<TurquoisehealthApi.V3Provider>> {
        const { provider_id: providerId } = request;
        const _authRequest: core.AuthRequest = await this._options.authProvider.getAuthRequest();
        const _headers: core.Fetcher.Args["headers"] = mergeHeaders(
            _authRequest.headers,
            this._options?.headers,
            requestOptions?.headers,
        );
        const _response = await core.fetcher({
            url: core.url.join(
                (await core.Supplier.get(this._options.baseUrl)) ??
                    (await core.Supplier.get(this._options.environment)),
                `v3/providers/${core.url.encodePathParam(providerId)}`,
            ),
            method: "GET",
            headers: _headers,
            queryParameters: requestOptions?.queryParams,
            timeoutMs: (requestOptions?.timeoutInSeconds ?? this._options?.timeoutInSeconds ?? 60) * 1000,
            maxRetries: requestOptions?.maxRetries ?? this._options?.maxRetries,
            abortSignal: requestOptions?.abortSignal,
            fetchFn: this._options?.fetch,
            logging: this._options.logging,
        });
        if (_response.ok) {
            return { data: _response.body as TurquoisehealthApi.V3Provider, rawResponse: _response.rawResponse };
        }

        if (_response.error.reason === "status-code") {
            switch (_response.error.statusCode) {
                case 400:
                    throw new TurquoisehealthApi.BadRequestError(
                        _response.error.body as TurquoisehealthApi.V3ErrorResponse,
                        _response.rawResponse,
                    );
                case 404:
                    throw new TurquoisehealthApi.NotFoundError(
                        _response.error.body as TurquoisehealthApi.V3ErrorResponse,
                        _response.rawResponse,
                    );
                case 422:
                    throw new TurquoisehealthApi.UnprocessableEntityError(
                        _response.error.body as TurquoisehealthApi.V3ErrorResponse,
                        _response.rawResponse,
                    );
                case 429:
                    throw new TurquoisehealthApi.TooManyRequestsError(
                        _response.error.body as TurquoisehealthApi.V3ErrorResponse,
                        _response.rawResponse,
                    );
                case 500:
                    throw new TurquoisehealthApi.InternalServerError(
                        _response.error.body as TurquoisehealthApi.V3ErrorResponse,
                        _response.rawResponse,
                    );
                default:
                    throw new errors.TurquoisehealthApiError({
                        statusCode: _response.error.statusCode,
                        body: _response.error.body,
                        rawResponse: _response.rawResponse,
                    });
            }
        }

        switch (_response.error.reason) {
            case "non-json":
                throw new errors.TurquoisehealthApiError({
                    statusCode: _response.error.statusCode,
                    body: _response.error.rawBody,
                    rawResponse: _response.rawResponse,
                });
            case "body-is-null":
                throw new errors.TurquoisehealthApiError({
                    statusCode: _response.error.statusCode,
                    rawResponse: _response.rawResponse,
                });
            case "timeout":
                throw new errors.TurquoisehealthApiTimeoutError(
                    "Timeout exceeded when calling GET /v3/providers/{provider_id}.",
                );
            case "unknown":
                throw new errors.TurquoisehealthApiError({
                    message: _response.error.errorMessage,
                    rawResponse: _response.rawResponse,
                });
        }
    }
}
