// This file was auto-generated by Fern from our API Definition.

import type { BaseClientOptions, BaseRequestOptions } from "../../../../BaseClient.js";
import { type NormalizedClientOptionsWithAuth, normalizeClientOptionsWithAuth } from "../../../../BaseClient.js";
import { mergeHeaders } from "../../../../core/headers.js";
import * as core from "../../../../core/index.js";
import { toJson } from "../../../../core/json.js";
import * as environments from "../../../../environments.js";
import * as errors from "../../../../errors/index.js";
import * as TurquoiseHealthApi from "../../../index.js";

export declare namespace ConsumerPricingClient {
    export interface Options extends BaseClientOptions {}

    export interface RequestOptions extends BaseRequestOptions {}
}

export class ConsumerPricingClient {
    protected readonly _options: NormalizedClientOptionsWithAuth<ConsumerPricingClient.Options>;

    constructor(options: ConsumerPricingClient.Options = {}) {
        this._options = normalizeClientOptionsWithAuth(options);
    }

    /**
     * Fetch provider types. Results return valid inputs to filter by provider types across the API.
     *
     * @param {ConsumerPricingClient.RequestOptions} requestOptions - Request-specific configuration.
     *
     * @throws {@link TurquoiseHealthApi.BadRequestError}
     * @throws {@link TurquoiseHealthApi.NotFoundError}
     * @throws {@link TurquoiseHealthApi.UnprocessableEntityError}
     * @throws {@link TurquoiseHealthApi.TooManyRequestsError}
     * @throws {@link TurquoiseHealthApi.InternalServerError}
     *
     * @example
     *     await client.consumerPricing.v3GetProviderTypes()
     */
    public v3GetProviderTypes(
        requestOptions?: ConsumerPricingClient.RequestOptions,
    ): core.HttpResponsePromise<string[]> {
        return core.HttpResponsePromise.fromPromise(this.__v3GetProviderTypes(requestOptions));
    }

    private async __v3GetProviderTypes(
        requestOptions?: ConsumerPricingClient.RequestOptions,
    ): Promise<core.WithRawResponse<string[]>> {
        const _authRequest: core.AuthRequest = await this._options.authProvider.getAuthRequest();
        const _headers: core.Fetcher.Args["headers"] = mergeHeaders(
            _authRequest.headers,
            this._options?.headers,
            requestOptions?.headers,
        );
        const _response = await core.fetcher({
            url: core.url.join(
                (await core.Supplier.get(this._options.baseUrl)) ??
                    (await core.Supplier.get(this._options.environment)) ??
                    environments.TurquoiseHealthApiEnvironment.Default,
                "v3/providers/types",
            ),
            method: "GET",
            headers: _headers,
            queryParameters: requestOptions?.queryParams,
            timeoutMs: (requestOptions?.timeoutInSeconds ?? this._options?.timeoutInSeconds ?? 60) * 1000,
            maxRetries: requestOptions?.maxRetries ?? this._options?.maxRetries,
            abortSignal: requestOptions?.abortSignal,
            fetchFn: this._options?.fetch,
            logging: this._options.logging,
        });
        if (_response.ok) {
            return { data: _response.body as string[], rawResponse: _response.rawResponse };
        }

        if (_response.error.reason === "status-code") {
            switch (_response.error.statusCode) {
                case 400:
                    throw new TurquoiseHealthApi.BadRequestError(
                        _response.error.body as unknown,
                        _response.rawResponse,
                    );
                case 404:
                    throw new TurquoiseHealthApi.NotFoundError(_response.error.body as unknown, _response.rawResponse);
                case 422:
                    throw new TurquoiseHealthApi.UnprocessableEntityError(
                        _response.error.body as unknown,
                        _response.rawResponse,
                    );
                case 429:
                    throw new TurquoiseHealthApi.TooManyRequestsError(
                        _response.error.body as unknown,
                        _response.rawResponse,
                    );
                case 500:
                    throw new TurquoiseHealthApi.InternalServerError(
                        _response.error.body as unknown,
                        _response.rawResponse,
                    );
                default:
                    throw new errors.TurquoiseHealthApiError({
                        statusCode: _response.error.statusCode,
                        body: _response.error.body,
                        rawResponse: _response.rawResponse,
                    });
            }
        }

        switch (_response.error.reason) {
            case "non-json":
                throw new errors.TurquoiseHealthApiError({
                    statusCode: _response.error.statusCode,
                    body: _response.error.rawBody,
                    rawResponse: _response.rawResponse,
                });
            case "body-is-null":
                throw new errors.TurquoiseHealthApiError({
                    statusCode: _response.error.statusCode,
                    rawResponse: _response.rawResponse,
                });
            case "timeout":
                throw new errors.TurquoiseHealthApiTimeoutError(
                    "Timeout exceeded when calling GET /v3/providers/types.",
                );
            case "unknown":
                throw new errors.TurquoiseHealthApiError({
                    message: _response.error.errorMessage,
                    rawResponse: _response.rawResponse,
                });
        }
    }

    /**
     * Retrieve a list of providers, filtered over a search by name, NPI, provider type, or location. Additionally, filter to a list of providers with Turquoise price estimates available by a selected payer, network, or package. Results reflect provider, payer, and package combinations that Turquoise has priced services for; the list may not be comprehensive of all contacted payer networks or services that are available.
     *
     * @param {TurquoiseHealthApi.V3ListProvidersRequest} request
     * @param {ConsumerPricingClient.RequestOptions} requestOptions - Request-specific configuration.
     *
     * @throws {@link TurquoiseHealthApi.BadRequestError}
     * @throws {@link TurquoiseHealthApi.NotFoundError}
     * @throws {@link TurquoiseHealthApi.UnprocessableEntityError}
     * @throws {@link TurquoiseHealthApi.TooManyRequestsError}
     * @throws {@link TurquoiseHealthApi.InternalServerError}
     *
     * @example
     *     await client.consumerPricing.v3ListProviders()
     */
    public v3ListProviders(
        request: TurquoiseHealthApi.V3ListProvidersRequest = {},
        requestOptions?: ConsumerPricingClient.RequestOptions,
    ): core.HttpResponsePromise<TurquoiseHealthApi.ListEnvelopeProvider> {
        return core.HttpResponsePromise.fromPromise(this.__v3ListProviders(request, requestOptions));
    }

    private async __v3ListProviders(
        request: TurquoiseHealthApi.V3ListProvidersRequest = {},
        requestOptions?: ConsumerPricingClient.RequestOptions,
    ): Promise<core.WithRawResponse<TurquoiseHealthApi.ListEnvelopeProvider>> {
        const {
            name,
            npi,
            type: type_,
            package_id: packageId,
            network_id: networkId,
            payer_id: payerId,
            search,
            min_score: minScore,
            page_size: pageSize,
            cursor,
            "location.near.lat": locationNearLat,
            "location.near.lng": locationNearLng,
            "location.near.radius_m": locationNearRadiusM,
            "location.within.state": locationWithinState,
            "location.within.cbsa": locationWithinCbsa,
            "location.within.zip_codes": locationWithinZipCodes,
            "location.zip": locationZip,
        } = request;
        const _queryParams: Record<string, string | string[] | object | object[] | null> = {};
        if (name !== undefined) {
            _queryParams.name = name;
        }

        if (npi !== undefined) {
            _queryParams.npi = npi;
        }

        if (type_ !== undefined) {
            _queryParams.type = type_;
        }

        if (packageId !== undefined) {
            _queryParams.package_id = packageId;
        }

        if (networkId !== undefined) {
            _queryParams.network_id = networkId;
        }

        if (payerId !== undefined) {
            _queryParams.payer_id = payerId;
        }

        if (search !== undefined) {
            _queryParams.search = search;
        }

        if (minScore !== undefined) {
            _queryParams.min_score = minScore?.toString() ?? null;
        }

        if (pageSize != null) {
            _queryParams.page_size = pageSize.toString();
        }

        if (cursor !== undefined) {
            _queryParams.cursor = cursor;
        }

        if (locationNearLat !== undefined) {
            _queryParams["location.near.lat"] = locationNearLat?.toString() ?? null;
        }

        if (locationNearLng !== undefined) {
            _queryParams["location.near.lng"] = locationNearLng?.toString() ?? null;
        }

        if (locationNearRadiusM !== undefined) {
            _queryParams["location.near.radius_m"] = locationNearRadiusM?.toString() ?? null;
        }

        if (locationWithinState !== undefined) {
            _queryParams["location.within.state"] = locationWithinState;
        }

        if (locationWithinCbsa !== undefined) {
            _queryParams["location.within.cbsa"] = locationWithinCbsa;
        }

        if (locationWithinZipCodes !== undefined) {
            _queryParams["location.within.zip_codes"] = locationWithinZipCodes;
        }

        if (locationZip !== undefined) {
            _queryParams["location.zip"] = locationZip;
        }

        const _authRequest: core.AuthRequest = await this._options.authProvider.getAuthRequest();
        const _headers: core.Fetcher.Args["headers"] = mergeHeaders(
            _authRequest.headers,
            this._options?.headers,
            requestOptions?.headers,
        );
        const _response = await core.fetcher({
            url: core.url.join(
                (await core.Supplier.get(this._options.baseUrl)) ??
                    (await core.Supplier.get(this._options.environment)) ??
                    environments.TurquoiseHealthApiEnvironment.Default,
                "v3/providers",
            ),
            method: "GET",
            headers: _headers,
            queryParameters: { ..._queryParams, ...requestOptions?.queryParams },
            timeoutMs: (requestOptions?.timeoutInSeconds ?? this._options?.timeoutInSeconds ?? 60) * 1000,
            maxRetries: requestOptions?.maxRetries ?? this._options?.maxRetries,
            abortSignal: requestOptions?.abortSignal,
            fetchFn: this._options?.fetch,
            logging: this._options.logging,
        });
        if (_response.ok) {
            return {
                data: _response.body as TurquoiseHealthApi.ListEnvelopeProvider,
                rawResponse: _response.rawResponse,
            };
        }

        if (_response.error.reason === "status-code") {
            switch (_response.error.statusCode) {
                case 400:
                    throw new TurquoiseHealthApi.BadRequestError(
                        _response.error.body as unknown,
                        _response.rawResponse,
                    );
                case 404:
                    throw new TurquoiseHealthApi.NotFoundError(_response.error.body as unknown, _response.rawResponse);
                case 422:
                    throw new TurquoiseHealthApi.UnprocessableEntityError(
                        _response.error.body as unknown,
                        _response.rawResponse,
                    );
                case 429:
                    throw new TurquoiseHealthApi.TooManyRequestsError(
                        _response.error.body as unknown,
                        _response.rawResponse,
                    );
                case 500:
                    throw new TurquoiseHealthApi.InternalServerError(
                        _response.error.body as unknown,
                        _response.rawResponse,
                    );
                default:
                    throw new errors.TurquoiseHealthApiError({
                        statusCode: _response.error.statusCode,
                        body: _response.error.body,
                        rawResponse: _response.rawResponse,
                    });
            }
        }

        switch (_response.error.reason) {
            case "non-json":
                throw new errors.TurquoiseHealthApiError({
                    statusCode: _response.error.statusCode,
                    body: _response.error.rawBody,
                    rawResponse: _response.rawResponse,
                });
            case "body-is-null":
                throw new errors.TurquoiseHealthApiError({
                    statusCode: _response.error.statusCode,
                    rawResponse: _response.rawResponse,
                });
            case "timeout":
                throw new errors.TurquoiseHealthApiTimeoutError("Timeout exceeded when calling GET /v3/providers.");
            case "unknown":
                throw new errors.TurquoiseHealthApiError({
                    message: _response.error.errorMessage,
                    rawResponse: _response.rawResponse,
                });
        }
    }

    /**
     * Fetch details for a single provider by provider ID.
     *
     * @param {TurquoiseHealthApi.V3GetProviderRequest} request
     * @param {ConsumerPricingClient.RequestOptions} requestOptions - Request-specific configuration.
     *
     * @throws {@link TurquoiseHealthApi.BadRequestError}
     * @throws {@link TurquoiseHealthApi.NotFoundError}
     * @throws {@link TurquoiseHealthApi.UnprocessableEntityError}
     * @throws {@link TurquoiseHealthApi.TooManyRequestsError}
     * @throws {@link TurquoiseHealthApi.InternalServerError}
     *
     * @example
     *     await client.consumerPricing.v3GetProvider({
     *         provider_id: "5756"
     *     })
     */
    public v3GetProvider(
        request: TurquoiseHealthApi.V3GetProviderRequest,
        requestOptions?: ConsumerPricingClient.RequestOptions,
    ): core.HttpResponsePromise<TurquoiseHealthApi.Provider> {
        return core.HttpResponsePromise.fromPromise(this.__v3GetProvider(request, requestOptions));
    }

    private async __v3GetProvider(
        request: TurquoiseHealthApi.V3GetProviderRequest,
        requestOptions?: ConsumerPricingClient.RequestOptions,
    ): Promise<core.WithRawResponse<TurquoiseHealthApi.Provider>> {
        const { provider_id: providerId } = request;
        const _authRequest: core.AuthRequest = await this._options.authProvider.getAuthRequest();
        const _headers: core.Fetcher.Args["headers"] = mergeHeaders(
            _authRequest.headers,
            this._options?.headers,
            requestOptions?.headers,
        );
        const _response = await core.fetcher({
            url: core.url.join(
                (await core.Supplier.get(this._options.baseUrl)) ??
                    (await core.Supplier.get(this._options.environment)) ??
                    environments.TurquoiseHealthApiEnvironment.Default,
                `v3/providers/${core.url.encodePathParam(providerId)}`,
            ),
            method: "GET",
            headers: _headers,
            queryParameters: requestOptions?.queryParams,
            timeoutMs: (requestOptions?.timeoutInSeconds ?? this._options?.timeoutInSeconds ?? 60) * 1000,
            maxRetries: requestOptions?.maxRetries ?? this._options?.maxRetries,
            abortSignal: requestOptions?.abortSignal,
            fetchFn: this._options?.fetch,
            logging: this._options.logging,
        });
        if (_response.ok) {
            return { data: _response.body as TurquoiseHealthApi.Provider, rawResponse: _response.rawResponse };
        }

        if (_response.error.reason === "status-code") {
            switch (_response.error.statusCode) {
                case 400:
                    throw new TurquoiseHealthApi.BadRequestError(
                        _response.error.body as unknown,
                        _response.rawResponse,
                    );
                case 404:
                    throw new TurquoiseHealthApi.NotFoundError(_response.error.body as unknown, _response.rawResponse);
                case 422:
                    throw new TurquoiseHealthApi.UnprocessableEntityError(
                        _response.error.body as unknown,
                        _response.rawResponse,
                    );
                case 429:
                    throw new TurquoiseHealthApi.TooManyRequestsError(
                        _response.error.body as unknown,
                        _response.rawResponse,
                    );
                case 500:
                    throw new TurquoiseHealthApi.InternalServerError(
                        _response.error.body as unknown,
                        _response.rawResponse,
                    );
                default:
                    throw new errors.TurquoiseHealthApiError({
                        statusCode: _response.error.statusCode,
                        body: _response.error.body,
                        rawResponse: _response.rawResponse,
                    });
            }
        }

        switch (_response.error.reason) {
            case "non-json":
                throw new errors.TurquoiseHealthApiError({
                    statusCode: _response.error.statusCode,
                    body: _response.error.rawBody,
                    rawResponse: _response.rawResponse,
                });
            case "body-is-null":
                throw new errors.TurquoiseHealthApiError({
                    statusCode: _response.error.statusCode,
                    rawResponse: _response.rawResponse,
                });
            case "timeout":
                throw new errors.TurquoiseHealthApiTimeoutError(
                    "Timeout exceeded when calling GET /v3/providers/{provider_id}.",
                );
            case "unknown":
                throw new errors.TurquoiseHealthApiError({
                    message: _response.error.errorMessage,
                    rawResponse: _response.rawResponse,
                });
        }
    }

    /**
     * Retrieve a list of payers, filtered over a search by name, location for care, or specific providers and services priced in the Turquoise data. Location scopes to payers with at least one price at an in-area provider. Results reflect provider, payer, and package combinations that Turquoise has priced services for; the list may not be comprehensive of all contracted providers or services that are available.
     *
     * @param {TurquoiseHealthApi.V3ListPayersRequest} request
     * @param {ConsumerPricingClient.RequestOptions} requestOptions - Request-specific configuration.
     *
     * @throws {@link TurquoiseHealthApi.BadRequestError}
     * @throws {@link TurquoiseHealthApi.NotFoundError}
     * @throws {@link TurquoiseHealthApi.UnprocessableEntityError}
     * @throws {@link TurquoiseHealthApi.TooManyRequestsError}
     * @throws {@link TurquoiseHealthApi.InternalServerError}
     *
     * @example
     *     await client.consumerPricing.v3ListPayers()
     */
    public v3ListPayers(
        request: TurquoiseHealthApi.V3ListPayersRequest = {},
        requestOptions?: ConsumerPricingClient.RequestOptions,
    ): core.HttpResponsePromise<TurquoiseHealthApi.ListEnvelopePayer> {
        return core.HttpResponsePromise.fromPromise(this.__v3ListPayers(request, requestOptions));
    }

    private async __v3ListPayers(
        request: TurquoiseHealthApi.V3ListPayersRequest = {},
        requestOptions?: ConsumerPricingClient.RequestOptions,
    ): Promise<core.WithRawResponse<TurquoiseHealthApi.ListEnvelopePayer>> {
        const {
            name,
            provider_id: providerId,
            package_id: packageId,
            page_size: pageSize,
            cursor,
            "location.near.lat": locationNearLat,
            "location.near.lng": locationNearLng,
            "location.near.radius_m": locationNearRadiusM,
            "location.within.state": locationWithinState,
            "location.within.cbsa": locationWithinCbsa,
            "location.within.zip_codes": locationWithinZipCodes,
            "location.zip": locationZip,
        } = request;
        const _queryParams: Record<string, string | string[] | object | object[] | null> = {};
        if (name !== undefined) {
            _queryParams.name = name;
        }

        if (providerId !== undefined) {
            _queryParams.provider_id = providerId;
        }

        if (packageId !== undefined) {
            _queryParams.package_id = packageId;
        }

        if (pageSize != null) {
            _queryParams.page_size = pageSize.toString();
        }

        if (cursor !== undefined) {
            _queryParams.cursor = cursor;
        }

        if (locationNearLat !== undefined) {
            _queryParams["location.near.lat"] = locationNearLat?.toString() ?? null;
        }

        if (locationNearLng !== undefined) {
            _queryParams["location.near.lng"] = locationNearLng?.toString() ?? null;
        }

        if (locationNearRadiusM !== undefined) {
            _queryParams["location.near.radius_m"] = locationNearRadiusM?.toString() ?? null;
        }

        if (locationWithinState !== undefined) {
            _queryParams["location.within.state"] = locationWithinState;
        }

        if (locationWithinCbsa !== undefined) {
            _queryParams["location.within.cbsa"] = locationWithinCbsa;
        }

        if (locationWithinZipCodes !== undefined) {
            _queryParams["location.within.zip_codes"] = locationWithinZipCodes;
        }

        if (locationZip !== undefined) {
            _queryParams["location.zip"] = locationZip;
        }

        const _authRequest: core.AuthRequest = await this._options.authProvider.getAuthRequest();
        const _headers: core.Fetcher.Args["headers"] = mergeHeaders(
            _authRequest.headers,
            this._options?.headers,
            requestOptions?.headers,
        );
        const _response = await core.fetcher({
            url: core.url.join(
                (await core.Supplier.get(this._options.baseUrl)) ??
                    (await core.Supplier.get(this._options.environment)) ??
                    environments.TurquoiseHealthApiEnvironment.Default,
                "v3/payers",
            ),
            method: "GET",
            headers: _headers,
            queryParameters: { ..._queryParams, ...requestOptions?.queryParams },
            timeoutMs: (requestOptions?.timeoutInSeconds ?? this._options?.timeoutInSeconds ?? 60) * 1000,
            maxRetries: requestOptions?.maxRetries ?? this._options?.maxRetries,
            abortSignal: requestOptions?.abortSignal,
            fetchFn: this._options?.fetch,
            logging: this._options.logging,
        });
        if (_response.ok) {
            return { data: _response.body as TurquoiseHealthApi.ListEnvelopePayer, rawResponse: _response.rawResponse };
        }

        if (_response.error.reason === "status-code") {
            switch (_response.error.statusCode) {
                case 400:
                    throw new TurquoiseHealthApi.BadRequestError(
                        _response.error.body as unknown,
                        _response.rawResponse,
                    );
                case 404:
                    throw new TurquoiseHealthApi.NotFoundError(_response.error.body as unknown, _response.rawResponse);
                case 422:
                    throw new TurquoiseHealthApi.UnprocessableEntityError(
                        _response.error.body as unknown,
                        _response.rawResponse,
                    );
                case 429:
                    throw new TurquoiseHealthApi.TooManyRequestsError(
                        _response.error.body as unknown,
                        _response.rawResponse,
                    );
                case 500:
                    throw new TurquoiseHealthApi.InternalServerError(
                        _response.error.body as unknown,
                        _response.rawResponse,
                    );
                default:
                    throw new errors.TurquoiseHealthApiError({
                        statusCode: _response.error.statusCode,
                        body: _response.error.body,
                        rawResponse: _response.rawResponse,
                    });
            }
        }

        switch (_response.error.reason) {
            case "non-json":
                throw new errors.TurquoiseHealthApiError({
                    statusCode: _response.error.statusCode,
                    body: _response.error.rawBody,
                    rawResponse: _response.rawResponse,
                });
            case "body-is-null":
                throw new errors.TurquoiseHealthApiError({
                    statusCode: _response.error.statusCode,
                    rawResponse: _response.rawResponse,
                });
            case "timeout":
                throw new errors.TurquoiseHealthApiTimeoutError("Timeout exceeded when calling GET /v3/payers.");
            case "unknown":
                throw new errors.TurquoiseHealthApiError({
                    message: _response.error.errorMessage,
                    rawResponse: _response.rawResponse,
                });
        }
    }

    /**
     * Fetch details about a single payer by payer ID.
     *
     * @param {TurquoiseHealthApi.V3GetPayerRequest} request
     * @param {ConsumerPricingClient.RequestOptions} requestOptions - Request-specific configuration.
     *
     * @throws {@link TurquoiseHealthApi.BadRequestError}
     * @throws {@link TurquoiseHealthApi.NotFoundError}
     * @throws {@link TurquoiseHealthApi.UnprocessableEntityError}
     * @throws {@link TurquoiseHealthApi.TooManyRequestsError}
     * @throws {@link TurquoiseHealthApi.InternalServerError}
     *
     * @example
     *     await client.consumerPricing.v3GetPayer({
     *         payer_id: "76"
     *     })
     */
    public v3GetPayer(
        request: TurquoiseHealthApi.V3GetPayerRequest,
        requestOptions?: ConsumerPricingClient.RequestOptions,
    ): core.HttpResponsePromise<TurquoiseHealthApi.Payer> {
        return core.HttpResponsePromise.fromPromise(this.__v3GetPayer(request, requestOptions));
    }

    private async __v3GetPayer(
        request: TurquoiseHealthApi.V3GetPayerRequest,
        requestOptions?: ConsumerPricingClient.RequestOptions,
    ): Promise<core.WithRawResponse<TurquoiseHealthApi.Payer>> {
        const { payer_id: payerId } = request;
        const _authRequest: core.AuthRequest = await this._options.authProvider.getAuthRequest();
        const _headers: core.Fetcher.Args["headers"] = mergeHeaders(
            _authRequest.headers,
            this._options?.headers,
            requestOptions?.headers,
        );
        const _response = await core.fetcher({
            url: core.url.join(
                (await core.Supplier.get(this._options.baseUrl)) ??
                    (await core.Supplier.get(this._options.environment)) ??
                    environments.TurquoiseHealthApiEnvironment.Default,
                `v3/payers/${core.url.encodePathParam(payerId)}`,
            ),
            method: "GET",
            headers: _headers,
            queryParameters: requestOptions?.queryParams,
            timeoutMs: (requestOptions?.timeoutInSeconds ?? this._options?.timeoutInSeconds ?? 60) * 1000,
            maxRetries: requestOptions?.maxRetries ?? this._options?.maxRetries,
            abortSignal: requestOptions?.abortSignal,
            fetchFn: this._options?.fetch,
            logging: this._options.logging,
        });
        if (_response.ok) {
            return { data: _response.body as TurquoiseHealthApi.Payer, rawResponse: _response.rawResponse };
        }

        if (_response.error.reason === "status-code") {
            switch (_response.error.statusCode) {
                case 400:
                    throw new TurquoiseHealthApi.BadRequestError(
                        _response.error.body as unknown,
                        _response.rawResponse,
                    );
                case 404:
                    throw new TurquoiseHealthApi.NotFoundError(_response.error.body as unknown, _response.rawResponse);
                case 422:
                    throw new TurquoiseHealthApi.UnprocessableEntityError(
                        _response.error.body as unknown,
                        _response.rawResponse,
                    );
                case 429:
                    throw new TurquoiseHealthApi.TooManyRequestsError(
                        _response.error.body as unknown,
                        _response.rawResponse,
                    );
                case 500:
                    throw new TurquoiseHealthApi.InternalServerError(
                        _response.error.body as unknown,
                        _response.rawResponse,
                    );
                default:
                    throw new errors.TurquoiseHealthApiError({
                        statusCode: _response.error.statusCode,
                        body: _response.error.body,
                        rawResponse: _response.rawResponse,
                    });
            }
        }

        switch (_response.error.reason) {
            case "non-json":
                throw new errors.TurquoiseHealthApiError({
                    statusCode: _response.error.statusCode,
                    body: _response.error.rawBody,
                    rawResponse: _response.rawResponse,
                });
            case "body-is-null":
                throw new errors.TurquoiseHealthApiError({
                    statusCode: _response.error.statusCode,
                    rawResponse: _response.rawResponse,
                });
            case "timeout":
                throw new errors.TurquoiseHealthApiTimeoutError(
                    "Timeout exceeded when calling GET /v3/payers/{payer_id}.",
                );
            case "unknown":
                throw new errors.TurquoiseHealthApiError({
                    message: _response.error.errorMessage,
                    rawResponse: _response.rawResponse,
                });
        }
    }

    /**
     * Retrieve a list of payer networks, filtered over a search by name, payer organization (e.g., Cigna), location for care, or specific providers and services priced in the Turquoise data. Location scopes to payer networks with at least one price at an in-area provider. Results reflect provider, payer network, and package combinations that Turquoise has priced services for; the list may not be comprehensive of all contracted providers or services that are available.
     *
     * @param {TurquoiseHealthApi.V3ListNetworksRequest} request
     * @param {ConsumerPricingClient.RequestOptions} requestOptions - Request-specific configuration.
     *
     * @throws {@link TurquoiseHealthApi.BadRequestError}
     * @throws {@link TurquoiseHealthApi.NotFoundError}
     * @throws {@link TurquoiseHealthApi.UnprocessableEntityError}
     * @throws {@link TurquoiseHealthApi.TooManyRequestsError}
     * @throws {@link TurquoiseHealthApi.InternalServerError}
     *
     * @example
     *     await client.consumerPricing.v3ListNetworks()
     */
    public v3ListNetworks(
        request: TurquoiseHealthApi.V3ListNetworksRequest = {},
        requestOptions?: ConsumerPricingClient.RequestOptions,
    ): core.HttpResponsePromise<TurquoiseHealthApi.ListEnvelopeNetwork> {
        return core.HttpResponsePromise.fromPromise(this.__v3ListNetworks(request, requestOptions));
    }

    private async __v3ListNetworks(
        request: TurquoiseHealthApi.V3ListNetworksRequest = {},
        requestOptions?: ConsumerPricingClient.RequestOptions,
    ): Promise<core.WithRawResponse<TurquoiseHealthApi.ListEnvelopeNetwork>> {
        const {
            name,
            payer_id: payerId,
            provider_id: providerId,
            package_id: packageId,
            search,
            min_score: minScore,
            page_size: pageSize,
            cursor,
            "location.near.lat": locationNearLat,
            "location.near.lng": locationNearLng,
            "location.near.radius_m": locationNearRadiusM,
            "location.within.state": locationWithinState,
            "location.within.cbsa": locationWithinCbsa,
            "location.within.zip_codes": locationWithinZipCodes,
            "location.zip": locationZip,
        } = request;
        const _queryParams: Record<string, string | string[] | object | object[] | null> = {};
        if (name !== undefined) {
            _queryParams.name = name;
        }

        if (payerId !== undefined) {
            _queryParams.payer_id = payerId;
        }

        if (providerId !== undefined) {
            _queryParams.provider_id = providerId;
        }

        if (packageId !== undefined) {
            _queryParams.package_id = packageId;
        }

        if (search !== undefined) {
            _queryParams.search = search;
        }

        if (minScore !== undefined) {
            _queryParams.min_score = minScore?.toString() ?? null;
        }

        if (pageSize != null) {
            _queryParams.page_size = pageSize.toString();
        }

        if (cursor !== undefined) {
            _queryParams.cursor = cursor;
        }

        if (locationNearLat !== undefined) {
            _queryParams["location.near.lat"] = locationNearLat?.toString() ?? null;
        }

        if (locationNearLng !== undefined) {
            _queryParams["location.near.lng"] = locationNearLng?.toString() ?? null;
        }

        if (locationNearRadiusM !== undefined) {
            _queryParams["location.near.radius_m"] = locationNearRadiusM?.toString() ?? null;
        }

        if (locationWithinState !== undefined) {
            _queryParams["location.within.state"] = locationWithinState;
        }

        if (locationWithinCbsa !== undefined) {
            _queryParams["location.within.cbsa"] = locationWithinCbsa;
        }

        if (locationWithinZipCodes !== undefined) {
            _queryParams["location.within.zip_codes"] = locationWithinZipCodes;
        }

        if (locationZip !== undefined) {
            _queryParams["location.zip"] = locationZip;
        }

        const _authRequest: core.AuthRequest = await this._options.authProvider.getAuthRequest();
        const _headers: core.Fetcher.Args["headers"] = mergeHeaders(
            _authRequest.headers,
            this._options?.headers,
            requestOptions?.headers,
        );
        const _response = await core.fetcher({
            url: core.url.join(
                (await core.Supplier.get(this._options.baseUrl)) ??
                    (await core.Supplier.get(this._options.environment)) ??
                    environments.TurquoiseHealthApiEnvironment.Default,
                "v3/networks",
            ),
            method: "GET",
            headers: _headers,
            queryParameters: { ..._queryParams, ...requestOptions?.queryParams },
            timeoutMs: (requestOptions?.timeoutInSeconds ?? this._options?.timeoutInSeconds ?? 60) * 1000,
            maxRetries: requestOptions?.maxRetries ?? this._options?.maxRetries,
            abortSignal: requestOptions?.abortSignal,
            fetchFn: this._options?.fetch,
            logging: this._options.logging,
        });
        if (_response.ok) {
            return {
                data: _response.body as TurquoiseHealthApi.ListEnvelopeNetwork,
                rawResponse: _response.rawResponse,
            };
        }

        if (_response.error.reason === "status-code") {
            switch (_response.error.statusCode) {
                case 400:
                    throw new TurquoiseHealthApi.BadRequestError(
                        _response.error.body as unknown,
                        _response.rawResponse,
                    );
                case 404:
                    throw new TurquoiseHealthApi.NotFoundError(_response.error.body as unknown, _response.rawResponse);
                case 422:
                    throw new TurquoiseHealthApi.UnprocessableEntityError(
                        _response.error.body as unknown,
                        _response.rawResponse,
                    );
                case 429:
                    throw new TurquoiseHealthApi.TooManyRequestsError(
                        _response.error.body as unknown,
                        _response.rawResponse,
                    );
                case 500:
                    throw new TurquoiseHealthApi.InternalServerError(
                        _response.error.body as unknown,
                        _response.rawResponse,
                    );
                default:
                    throw new errors.TurquoiseHealthApiError({
                        statusCode: _response.error.statusCode,
                        body: _response.error.body,
                        rawResponse: _response.rawResponse,
                    });
            }
        }

        switch (_response.error.reason) {
            case "non-json":
                throw new errors.TurquoiseHealthApiError({
                    statusCode: _response.error.statusCode,
                    body: _response.error.rawBody,
                    rawResponse: _response.rawResponse,
                });
            case "body-is-null":
                throw new errors.TurquoiseHealthApiError({
                    statusCode: _response.error.statusCode,
                    rawResponse: _response.rawResponse,
                });
            case "timeout":
                throw new errors.TurquoiseHealthApiTimeoutError("Timeout exceeded when calling GET /v3/networks.");
            case "unknown":
                throw new errors.TurquoiseHealthApiError({
                    message: _response.error.errorMessage,
                    rawResponse: _response.rawResponse,
                });
        }
    }

    /**
     * Fetch details about a single network by network ID.
     *
     * @param {TurquoiseHealthApi.V3GetNetworkRequest} request
     * @param {ConsumerPricingClient.RequestOptions} requestOptions - Request-specific configuration.
     *
     * @throws {@link TurquoiseHealthApi.BadRequestError}
     * @throws {@link TurquoiseHealthApi.NotFoundError}
     * @throws {@link TurquoiseHealthApi.UnprocessableEntityError}
     * @throws {@link TurquoiseHealthApi.TooManyRequestsError}
     * @throws {@link TurquoiseHealthApi.InternalServerError}
     *
     * @example
     *     await client.consumerPricing.v3GetNetwork({
     *         network_id: "-3776001016975145508"
     *     })
     */
    public v3GetNetwork(
        request: TurquoiseHealthApi.V3GetNetworkRequest,
        requestOptions?: ConsumerPricingClient.RequestOptions,
    ): core.HttpResponsePromise<TurquoiseHealthApi.Network> {
        return core.HttpResponsePromise.fromPromise(this.__v3GetNetwork(request, requestOptions));
    }

    private async __v3GetNetwork(
        request: TurquoiseHealthApi.V3GetNetworkRequest,
        requestOptions?: ConsumerPricingClient.RequestOptions,
    ): Promise<core.WithRawResponse<TurquoiseHealthApi.Network>> {
        const { network_id: networkId } = request;
        const _authRequest: core.AuthRequest = await this._options.authProvider.getAuthRequest();
        const _headers: core.Fetcher.Args["headers"] = mergeHeaders(
            _authRequest.headers,
            this._options?.headers,
            requestOptions?.headers,
        );
        const _response = await core.fetcher({
            url: core.url.join(
                (await core.Supplier.get(this._options.baseUrl)) ??
                    (await core.Supplier.get(this._options.environment)) ??
                    environments.TurquoiseHealthApiEnvironment.Default,
                `v3/networks/${core.url.encodePathParam(networkId)}`,
            ),
            method: "GET",
            headers: _headers,
            queryParameters: requestOptions?.queryParams,
            timeoutMs: (requestOptions?.timeoutInSeconds ?? this._options?.timeoutInSeconds ?? 60) * 1000,
            maxRetries: requestOptions?.maxRetries ?? this._options?.maxRetries,
            abortSignal: requestOptions?.abortSignal,
            fetchFn: this._options?.fetch,
            logging: this._options.logging,
        });
        if (_response.ok) {
            return { data: _response.body as TurquoiseHealthApi.Network, rawResponse: _response.rawResponse };
        }

        if (_response.error.reason === "status-code") {
            switch (_response.error.statusCode) {
                case 400:
                    throw new TurquoiseHealthApi.BadRequestError(
                        _response.error.body as unknown,
                        _response.rawResponse,
                    );
                case 404:
                    throw new TurquoiseHealthApi.NotFoundError(_response.error.body as unknown, _response.rawResponse);
                case 422:
                    throw new TurquoiseHealthApi.UnprocessableEntityError(
                        _response.error.body as unknown,
                        _response.rawResponse,
                    );
                case 429:
                    throw new TurquoiseHealthApi.TooManyRequestsError(
                        _response.error.body as unknown,
                        _response.rawResponse,
                    );
                case 500:
                    throw new TurquoiseHealthApi.InternalServerError(
                        _response.error.body as unknown,
                        _response.rawResponse,
                    );
                default:
                    throw new errors.TurquoiseHealthApiError({
                        statusCode: _response.error.statusCode,
                        body: _response.error.body,
                        rawResponse: _response.rawResponse,
                    });
            }
        }

        switch (_response.error.reason) {
            case "non-json":
                throw new errors.TurquoiseHealthApiError({
                    statusCode: _response.error.statusCode,
                    body: _response.error.rawBody,
                    rawResponse: _response.rawResponse,
                });
            case "body-is-null":
                throw new errors.TurquoiseHealthApiError({
                    statusCode: _response.error.statusCode,
                    rawResponse: _response.rawResponse,
                });
            case "timeout":
                throw new errors.TurquoiseHealthApiTimeoutError(
                    "Timeout exceeded when calling GET /v3/networks/{network_id}.",
                );
            case "unknown":
                throw new errors.TurquoiseHealthApiError({
                    message: _response.error.errorMessage,
                    rawResponse: _response.rawResponse,
                });
        }
    }

    /**
     * Return a list of service packages, filtered over name or anchor code. Additionally, filter to a list of packages with Turquoise price estimates available by a selected payer, network, or provider. Results reflect provider, payer, and package combinations that Turquoise has priced services for; the list may not be comprehensive of all payer networks or providers that support this service. When multiple relationship filters are combined, they must be satisfied by the same price row, so results are always fulfillable via GET /v3/prices.
     *
     * @param {TurquoiseHealthApi.V3ListPackagesRequest} request
     * @param {ConsumerPricingClient.RequestOptions} requestOptions - Request-specific configuration.
     *
     * @throws {@link TurquoiseHealthApi.BadRequestError}
     * @throws {@link TurquoiseHealthApi.NotFoundError}
     * @throws {@link TurquoiseHealthApi.UnprocessableEntityError}
     * @throws {@link TurquoiseHealthApi.TooManyRequestsError}
     * @throws {@link TurquoiseHealthApi.InternalServerError}
     *
     * @example
     *     await client.consumerPricing.v3ListPackages()
     */
    public v3ListPackages(
        request: TurquoiseHealthApi.V3ListPackagesRequest = {},
        requestOptions?: ConsumerPricingClient.RequestOptions,
    ): core.HttpResponsePromise<TurquoiseHealthApi.ListEnvelopePackage> {
        return core.HttpResponsePromise.fromPromise(this.__v3ListPackages(request, requestOptions));
    }

    private async __v3ListPackages(
        request: TurquoiseHealthApi.V3ListPackagesRequest = {},
        requestOptions?: ConsumerPricingClient.RequestOptions,
    ): Promise<core.WithRawResponse<TurquoiseHealthApi.ListEnvelopePackage>> {
        const {
            name,
            anchor_code: anchorCode,
            provider_id: providerId,
            network_id: networkId,
            payer_id: payerId,
            search,
            min_score: minScore,
            page_size: pageSize,
            cursor,
        } = request;
        const _queryParams: Record<string, string | string[] | object | object[] | null> = {};
        if (name !== undefined) {
            _queryParams.name = name;
        }

        if (anchorCode !== undefined) {
            _queryParams.anchor_code = anchorCode;
        }

        if (providerId !== undefined) {
            _queryParams.provider_id = providerId;
        }

        if (networkId !== undefined) {
            _queryParams.network_id = networkId;
        }

        if (payerId !== undefined) {
            _queryParams.payer_id = payerId;
        }

        if (search !== undefined) {
            _queryParams.search = search;
        }

        if (minScore !== undefined) {
            _queryParams.min_score = minScore?.toString() ?? null;
        }

        if (pageSize != null) {
            _queryParams.page_size = pageSize.toString();
        }

        if (cursor !== undefined) {
            _queryParams.cursor = cursor;
        }

        const _authRequest: core.AuthRequest = await this._options.authProvider.getAuthRequest();
        const _headers: core.Fetcher.Args["headers"] = mergeHeaders(
            _authRequest.headers,
            this._options?.headers,
            requestOptions?.headers,
        );
        const _response = await core.fetcher({
            url: core.url.join(
                (await core.Supplier.get(this._options.baseUrl)) ??
                    (await core.Supplier.get(this._options.environment)) ??
                    environments.TurquoiseHealthApiEnvironment.Default,
                "v3/packages",
            ),
            method: "GET",
            headers: _headers,
            queryParameters: { ..._queryParams, ...requestOptions?.queryParams },
            timeoutMs: (requestOptions?.timeoutInSeconds ?? this._options?.timeoutInSeconds ?? 60) * 1000,
            maxRetries: requestOptions?.maxRetries ?? this._options?.maxRetries,
            abortSignal: requestOptions?.abortSignal,
            fetchFn: this._options?.fetch,
            logging: this._options.logging,
        });
        if (_response.ok) {
            return {
                data: _response.body as TurquoiseHealthApi.ListEnvelopePackage,
                rawResponse: _response.rawResponse,
            };
        }

        if (_response.error.reason === "status-code") {
            switch (_response.error.statusCode) {
                case 400:
                    throw new TurquoiseHealthApi.BadRequestError(
                        _response.error.body as unknown,
                        _response.rawResponse,
                    );
                case 404:
                    throw new TurquoiseHealthApi.NotFoundError(_response.error.body as unknown, _response.rawResponse);
                case 422:
                    throw new TurquoiseHealthApi.UnprocessableEntityError(
                        _response.error.body as unknown,
                        _response.rawResponse,
                    );
                case 429:
                    throw new TurquoiseHealthApi.TooManyRequestsError(
                        _response.error.body as unknown,
                        _response.rawResponse,
                    );
                case 500:
                    throw new TurquoiseHealthApi.InternalServerError(
                        _response.error.body as unknown,
                        _response.rawResponse,
                    );
                default:
                    throw new errors.TurquoiseHealthApiError({
                        statusCode: _response.error.statusCode,
                        body: _response.error.body,
                        rawResponse: _response.rawResponse,
                    });
            }
        }

        switch (_response.error.reason) {
            case "non-json":
                throw new errors.TurquoiseHealthApiError({
                    statusCode: _response.error.statusCode,
                    body: _response.error.rawBody,
                    rawResponse: _response.rawResponse,
                });
            case "body-is-null":
                throw new errors.TurquoiseHealthApiError({
                    statusCode: _response.error.statusCode,
                    rawResponse: _response.rawResponse,
                });
            case "timeout":
                throw new errors.TurquoiseHealthApiTimeoutError("Timeout exceeded when calling GET /v3/packages.");
            case "unknown":
                throw new errors.TurquoiseHealthApiError({
                    message: _response.error.errorMessage,
                    rawResponse: _response.rawResponse,
                });
        }
    }

    /**
     * Fetch package details by package ID.
     *
     * @param {TurquoiseHealthApi.V3GetPackageRequest} request
     * @param {ConsumerPricingClient.RequestOptions} requestOptions - Request-specific configuration.
     *
     * @throws {@link TurquoiseHealthApi.BadRequestError}
     * @throws {@link TurquoiseHealthApi.NotFoundError}
     * @throws {@link TurquoiseHealthApi.UnprocessableEntityError}
     * @throws {@link TurquoiseHealthApi.TooManyRequestsError}
     * @throws {@link TurquoiseHealthApi.InternalServerError}
     *
     * @example
     *     await client.consumerPricing.v3GetPackage({
     *         package_id: "OB002"
     *     })
     */
    public v3GetPackage(
        request: TurquoiseHealthApi.V3GetPackageRequest,
        requestOptions?: ConsumerPricingClient.RequestOptions,
    ): core.HttpResponsePromise<TurquoiseHealthApi.Package> {
        return core.HttpResponsePromise.fromPromise(this.__v3GetPackage(request, requestOptions));
    }

    private async __v3GetPackage(
        request: TurquoiseHealthApi.V3GetPackageRequest,
        requestOptions?: ConsumerPricingClient.RequestOptions,
    ): Promise<core.WithRawResponse<TurquoiseHealthApi.Package>> {
        const { package_id: packageId } = request;
        const _authRequest: core.AuthRequest = await this._options.authProvider.getAuthRequest();
        const _headers: core.Fetcher.Args["headers"] = mergeHeaders(
            _authRequest.headers,
            this._options?.headers,
            requestOptions?.headers,
        );
        const _response = await core.fetcher({
            url: core.url.join(
                (await core.Supplier.get(this._options.baseUrl)) ??
                    (await core.Supplier.get(this._options.environment)) ??
                    environments.TurquoiseHealthApiEnvironment.Default,
                `v3/packages/${core.url.encodePathParam(packageId)}`,
            ),
            method: "GET",
            headers: _headers,
            queryParameters: requestOptions?.queryParams,
            timeoutMs: (requestOptions?.timeoutInSeconds ?? this._options?.timeoutInSeconds ?? 60) * 1000,
            maxRetries: requestOptions?.maxRetries ?? this._options?.maxRetries,
            abortSignal: requestOptions?.abortSignal,
            fetchFn: this._options?.fetch,
            logging: this._options.logging,
        });
        if (_response.ok) {
            return { data: _response.body as TurquoiseHealthApi.Package, rawResponse: _response.rawResponse };
        }

        if (_response.error.reason === "status-code") {
            switch (_response.error.statusCode) {
                case 400:
                    throw new TurquoiseHealthApi.BadRequestError(
                        _response.error.body as unknown,
                        _response.rawResponse,
                    );
                case 404:
                    throw new TurquoiseHealthApi.NotFoundError(_response.error.body as unknown, _response.rawResponse);
                case 422:
                    throw new TurquoiseHealthApi.UnprocessableEntityError(
                        _response.error.body as unknown,
                        _response.rawResponse,
                    );
                case 429:
                    throw new TurquoiseHealthApi.TooManyRequestsError(
                        _response.error.body as unknown,
                        _response.rawResponse,
                    );
                case 500:
                    throw new TurquoiseHealthApi.InternalServerError(
                        _response.error.body as unknown,
                        _response.rawResponse,
                    );
                default:
                    throw new errors.TurquoiseHealthApiError({
                        statusCode: _response.error.statusCode,
                        body: _response.error.body,
                        rawResponse: _response.rawResponse,
                    });
            }
        }

        switch (_response.error.reason) {
            case "non-json":
                throw new errors.TurquoiseHealthApiError({
                    statusCode: _response.error.statusCode,
                    body: _response.error.rawBody,
                    rawResponse: _response.rawResponse,
                });
            case "body-is-null":
                throw new errors.TurquoiseHealthApiError({
                    statusCode: _response.error.statusCode,
                    rawResponse: _response.rawResponse,
                });
            case "timeout":
                throw new errors.TurquoiseHealthApiTimeoutError(
                    "Timeout exceeded when calling GET /v3/packages/{package_id}.",
                );
            case "unknown":
                throw new errors.TurquoiseHealthApiError({
                    message: _response.error.errorMessage,
                    rawResponse: _response.rawResponse,
                });
        }
    }

    /**
     * Review a service package's composition. This includes common codes and fee types, and association rates across variations of packages for a given service.
     *
     * @param {TurquoiseHealthApi.V3ListPackageLineItemsRequest} request
     * @param {ConsumerPricingClient.RequestOptions} requestOptions - Request-specific configuration.
     *
     * @throws {@link TurquoiseHealthApi.BadRequestError}
     * @throws {@link TurquoiseHealthApi.NotFoundError}
     * @throws {@link TurquoiseHealthApi.UnprocessableEntityError}
     * @throws {@link TurquoiseHealthApi.TooManyRequestsError}
     * @throws {@link TurquoiseHealthApi.InternalServerError}
     *
     * @example
     *     await client.consumerPricing.v3ListPackageLineItems({
     *         package_id: "OB002"
     *     })
     */
    public v3ListPackageLineItems(
        request: TurquoiseHealthApi.V3ListPackageLineItemsRequest,
        requestOptions?: ConsumerPricingClient.RequestOptions,
    ): core.HttpResponsePromise<TurquoiseHealthApi.ListEnvelopeLineItem> {
        return core.HttpResponsePromise.fromPromise(this.__v3ListPackageLineItems(request, requestOptions));
    }

    private async __v3ListPackageLineItems(
        request: TurquoiseHealthApi.V3ListPackageLineItemsRequest,
        requestOptions?: ConsumerPricingClient.RequestOptions,
    ): Promise<core.WithRawResponse<TurquoiseHealthApi.ListEnvelopeLineItem>> {
        const { package_id: packageId } = request;
        const _authRequest: core.AuthRequest = await this._options.authProvider.getAuthRequest();
        const _headers: core.Fetcher.Args["headers"] = mergeHeaders(
            _authRequest.headers,
            this._options?.headers,
            requestOptions?.headers,
        );
        const _response = await core.fetcher({
            url: core.url.join(
                (await core.Supplier.get(this._options.baseUrl)) ??
                    (await core.Supplier.get(this._options.environment)) ??
                    environments.TurquoiseHealthApiEnvironment.Default,
                `v3/packages/${core.url.encodePathParam(packageId)}/line_items`,
            ),
            method: "GET",
            headers: _headers,
            queryParameters: requestOptions?.queryParams,
            timeoutMs: (requestOptions?.timeoutInSeconds ?? this._options?.timeoutInSeconds ?? 60) * 1000,
            maxRetries: requestOptions?.maxRetries ?? this._options?.maxRetries,
            abortSignal: requestOptions?.abortSignal,
            fetchFn: this._options?.fetch,
            logging: this._options.logging,
        });
        if (_response.ok) {
            return {
                data: _response.body as TurquoiseHealthApi.ListEnvelopeLineItem,
                rawResponse: _response.rawResponse,
            };
        }

        if (_response.error.reason === "status-code") {
            switch (_response.error.statusCode) {
                case 400:
                    throw new TurquoiseHealthApi.BadRequestError(
                        _response.error.body as unknown,
                        _response.rawResponse,
                    );
                case 404:
                    throw new TurquoiseHealthApi.NotFoundError(_response.error.body as unknown, _response.rawResponse);
                case 422:
                    throw new TurquoiseHealthApi.UnprocessableEntityError(
                        _response.error.body as unknown,
                        _response.rawResponse,
                    );
                case 429:
                    throw new TurquoiseHealthApi.TooManyRequestsError(
                        _response.error.body as unknown,
                        _response.rawResponse,
                    );
                case 500:
                    throw new TurquoiseHealthApi.InternalServerError(
                        _response.error.body as unknown,
                        _response.rawResponse,
                    );
                default:
                    throw new errors.TurquoiseHealthApiError({
                        statusCode: _response.error.statusCode,
                        body: _response.error.body,
                        rawResponse: _response.rawResponse,
                    });
            }
        }

        switch (_response.error.reason) {
            case "non-json":
                throw new errors.TurquoiseHealthApiError({
                    statusCode: _response.error.statusCode,
                    body: _response.error.rawBody,
                    rawResponse: _response.rawResponse,
                });
            case "body-is-null":
                throw new errors.TurquoiseHealthApiError({
                    statusCode: _response.error.statusCode,
                    rawResponse: _response.rawResponse,
                });
            case "timeout":
                throw new errors.TurquoiseHealthApiTimeoutError(
                    "Timeout exceeded when calling GET /v3/packages/{package_id}/line_items.",
                );
            case "unknown":
                throw new errors.TurquoiseHealthApiError({
                    message: _response.error.errorMessage,
                    rawResponse: _response.rawResponse,
                });
        }
    }

    /**
     * Return prices for valid provider, service package, and pricing arrangement (cash or negotiated) combinations.
     *
     * @param {TurquoiseHealthApi.PricesQueryRequest} request
     * @param {ConsumerPricingClient.RequestOptions} requestOptions - Request-specific configuration.
     *
     * @throws {@link TurquoiseHealthApi.BadRequestError}
     * @throws {@link TurquoiseHealthApi.NotFoundError}
     * @throws {@link TurquoiseHealthApi.UnprocessableEntityError}
     * @throws {@link TurquoiseHealthApi.TooManyRequestsError}
     * @throws {@link TurquoiseHealthApi.InternalServerError}
     *
     * @example
     *     await client.consumerPricing.v3QueryPrices({
     *         package_id: "OB002",
     *         provider_id: "5756",
     *         pricing: {
     *             type: "negotiated",
     *             network_id: "-3776001016975145508"
     *         }
     *     })
     *
     * @example
     *     await client.consumerPricing.v3QueryPrices({
     *         package_id: "RA008",
     *         provider_id: "5756",
     *         pricing: {
     *             type: "cash"
     *         }
     *     })
     *
     * @example
     *     await client.consumerPricing.v3QueryPrices({
     *         package_id: "RA008",
     *         pricing: {
     *             type: "cash"
     *         },
     *         location: {
     *             near: {
     *                 lat: 39.745961,
     *                 lng: -104.971559,
     *                 radius_m: 25000
     *             }
     *         },
     *         sort: "distance"
     *     })
     *
     * @example
     *     await client.consumerPricing.v3QueryPrices({
     *         package_id: "RA008",
     *         pricing: {
     *             type: "cash"
     *         },
     *         location: {
     *             zip: "80218"
     *         }
     *     })
     *
     * @example
     *     await client.consumerPricing.v3QueryPrices({
     *         package_id: "OB002",
     *         pricing: {
     *             type: "negotiated",
     *             network_id: "-3776001016975145508"
     *         },
     *         location: {
     *             within: {
     *                 zip_codes: ["80218", "80210"]
     *             }
     *         }
     *     })
     */
    public v3QueryPrices(
        request: TurquoiseHealthApi.PricesQueryRequest,
        requestOptions?: ConsumerPricingClient.RequestOptions,
    ): core.HttpResponsePromise<TurquoiseHealthApi.ListEnvelopeProviderPackagePrice> {
        return core.HttpResponsePromise.fromPromise(this.__v3QueryPrices(request, requestOptions));
    }

    private async __v3QueryPrices(
        request: TurquoiseHealthApi.PricesQueryRequest,
        requestOptions?: ConsumerPricingClient.RequestOptions,
    ): Promise<core.WithRawResponse<TurquoiseHealthApi.ListEnvelopeProviderPackagePrice>> {
        const _authRequest: core.AuthRequest = await this._options.authProvider.getAuthRequest();
        const _headers: core.Fetcher.Args["headers"] = mergeHeaders(
            _authRequest.headers,
            this._options?.headers,
            requestOptions?.headers,
        );
        const _response = await core.fetcher({
            url: core.url.join(
                (await core.Supplier.get(this._options.baseUrl)) ??
                    (await core.Supplier.get(this._options.environment)) ??
                    environments.TurquoiseHealthApiEnvironment.Default,
                "v3/prices/query",
            ),
            method: "POST",
            headers: _headers,
            contentType: "application/json",
            queryParameters: requestOptions?.queryParams,
            requestType: "json",
            body: request,
            timeoutMs: (requestOptions?.timeoutInSeconds ?? this._options?.timeoutInSeconds ?? 60) * 1000,
            maxRetries: requestOptions?.maxRetries ?? this._options?.maxRetries,
            abortSignal: requestOptions?.abortSignal,
            fetchFn: this._options?.fetch,
            logging: this._options.logging,
        });
        if (_response.ok) {
            return {
                data: _response.body as TurquoiseHealthApi.ListEnvelopeProviderPackagePrice,
                rawResponse: _response.rawResponse,
            };
        }

        if (_response.error.reason === "status-code") {
            switch (_response.error.statusCode) {
                case 400:
                    throw new TurquoiseHealthApi.BadRequestError(
                        _response.error.body as unknown,
                        _response.rawResponse,
                    );
                case 404:
                    throw new TurquoiseHealthApi.NotFoundError(_response.error.body as unknown, _response.rawResponse);
                case 422:
                    throw new TurquoiseHealthApi.UnprocessableEntityError(
                        _response.error.body as unknown,
                        _response.rawResponse,
                    );
                case 429:
                    throw new TurquoiseHealthApi.TooManyRequestsError(
                        _response.error.body as unknown,
                        _response.rawResponse,
                    );
                case 500:
                    throw new TurquoiseHealthApi.InternalServerError(
                        _response.error.body as unknown,
                        _response.rawResponse,
                    );
                default:
                    throw new errors.TurquoiseHealthApiError({
                        statusCode: _response.error.statusCode,
                        body: _response.error.body,
                        rawResponse: _response.rawResponse,
                    });
            }
        }

        switch (_response.error.reason) {
            case "non-json":
                throw new errors.TurquoiseHealthApiError({
                    statusCode: _response.error.statusCode,
                    body: _response.error.rawBody,
                    rawResponse: _response.rawResponse,
                });
            case "body-is-null":
                throw new errors.TurquoiseHealthApiError({
                    statusCode: _response.error.statusCode,
                    rawResponse: _response.rawResponse,
                });
            case "timeout":
                throw new errors.TurquoiseHealthApiTimeoutError("Timeout exceeded when calling POST /v3/prices/query.");
            case "unknown":
                throw new errors.TurquoiseHealthApiError({
                    message: _response.error.errorMessage,
                    rawResponse: _response.rawResponse,
                });
        }
    }

    /**
     * Return summary statistics (min, max, average, median, quartiles) over prices matching the same filters as /query, excluding sorting and pagination. Use this endpoint to compare prices across relevant criteria.
     *
     * @param {TurquoiseHealthApi.PricesCompareRequest} request
     * @param {ConsumerPricingClient.RequestOptions} requestOptions - Request-specific configuration.
     *
     * @throws {@link TurquoiseHealthApi.BadRequestError}
     * @throws {@link TurquoiseHealthApi.NotFoundError}
     * @throws {@link TurquoiseHealthApi.UnprocessableEntityError}
     * @throws {@link TurquoiseHealthApi.TooManyRequestsError}
     * @throws {@link TurquoiseHealthApi.InternalServerError}
     *
     * @example
     *     await client.consumerPricing.v3ComparePrices({
     *         package_id: "OB002",
     *         provider_id: "5756",
     *         pricing: {
     *             type: "negotiated",
     *             network_id: "-3776001016975145508"
     *         }
     *     })
     *
     * @example
     *     await client.consumerPricing.v3ComparePrices({
     *         package_id: "RA008",
     *         pricing: {
     *             type: "cash"
     *         },
     *         location: {
     *             within: {
     *                 zip_codes: ["80218", "80210"]
     *             }
     *         }
     *     })
     *
     * @example
     *     await client.consumerPricing.v3ComparePrices({
     *         package_id: "RA008",
     *         pricing: {
     *             type: "cash"
     *         },
     *         location: {
     *             near: {
     *                 lat: 39.745961,
     *                 lng: -104.971559,
     *                 radius_m: 25000
     *             }
     *         }
     *     })
     */
    public v3ComparePrices(
        request: TurquoiseHealthApi.PricesCompareRequest,
        requestOptions?: ConsumerPricingClient.RequestOptions,
    ): core.HttpResponsePromise<TurquoiseHealthApi.PriceComparison> {
        return core.HttpResponsePromise.fromPromise(this.__v3ComparePrices(request, requestOptions));
    }

    private async __v3ComparePrices(
        request: TurquoiseHealthApi.PricesCompareRequest,
        requestOptions?: ConsumerPricingClient.RequestOptions,
    ): Promise<core.WithRawResponse<TurquoiseHealthApi.PriceComparison>> {
        const _authRequest: core.AuthRequest = await this._options.authProvider.getAuthRequest();
        const _headers: core.Fetcher.Args["headers"] = mergeHeaders(
            _authRequest.headers,
            this._options?.headers,
            requestOptions?.headers,
        );
        const _response = await core.fetcher({
            url: core.url.join(
                (await core.Supplier.get(this._options.baseUrl)) ??
                    (await core.Supplier.get(this._options.environment)) ??
                    environments.TurquoiseHealthApiEnvironment.Default,
                "v3/prices/compare",
            ),
            method: "POST",
            headers: _headers,
            contentType: "application/json",
            queryParameters: requestOptions?.queryParams,
            requestType: "json",
            body: request,
            timeoutMs: (requestOptions?.timeoutInSeconds ?? this._options?.timeoutInSeconds ?? 60) * 1000,
            maxRetries: requestOptions?.maxRetries ?? this._options?.maxRetries,
            abortSignal: requestOptions?.abortSignal,
            fetchFn: this._options?.fetch,
            logging: this._options.logging,
        });
        if (_response.ok) {
            return { data: _response.body as TurquoiseHealthApi.PriceComparison, rawResponse: _response.rawResponse };
        }

        if (_response.error.reason === "status-code") {
            switch (_response.error.statusCode) {
                case 400:
                    throw new TurquoiseHealthApi.BadRequestError(
                        _response.error.body as unknown,
                        _response.rawResponse,
                    );
                case 404:
                    throw new TurquoiseHealthApi.NotFoundError(_response.error.body as unknown, _response.rawResponse);
                case 422:
                    throw new TurquoiseHealthApi.UnprocessableEntityError(
                        _response.error.body as unknown,
                        _response.rawResponse,
                    );
                case 429:
                    throw new TurquoiseHealthApi.TooManyRequestsError(
                        _response.error.body as unknown,
                        _response.rawResponse,
                    );
                case 500:
                    throw new TurquoiseHealthApi.InternalServerError(
                        _response.error.body as unknown,
                        _response.rawResponse,
                    );
                default:
                    throw new errors.TurquoiseHealthApiError({
                        statusCode: _response.error.statusCode,
                        body: _response.error.body,
                        rawResponse: _response.rawResponse,
                    });
            }
        }

        switch (_response.error.reason) {
            case "non-json":
                throw new errors.TurquoiseHealthApiError({
                    statusCode: _response.error.statusCode,
                    body: _response.error.rawBody,
                    rawResponse: _response.rawResponse,
                });
            case "body-is-null":
                throw new errors.TurquoiseHealthApiError({
                    statusCode: _response.error.statusCode,
                    rawResponse: _response.rawResponse,
                });
            case "timeout":
                throw new errors.TurquoiseHealthApiTimeoutError(
                    "Timeout exceeded when calling POST /v3/prices/compare.",
                );
            case "unknown":
                throw new errors.TurquoiseHealthApiError({
                    message: _response.error.errorMessage,
                    rawResponse: _response.rawResponse,
                });
        }
    }

    /**
     * Fetch a single price by its unique price ID. Expand line items to review the priced package composition.
     *
     * @param {TurquoiseHealthApi.V3GetPriceRequest} request
     * @param {ConsumerPricingClient.RequestOptions} requestOptions - Request-specific configuration.
     *
     * @throws {@link TurquoiseHealthApi.BadRequestError}
     * @throws {@link TurquoiseHealthApi.NotFoundError}
     * @throws {@link TurquoiseHealthApi.UnprocessableEntityError}
     * @throws {@link TurquoiseHealthApi.TooManyRequestsError}
     * @throws {@link TurquoiseHealthApi.InternalServerError}
     *
     * @example
     *     await client.consumerPricing.v3GetPrice({
     *         price_id: "prc_5756.OB002.-3776001016975145508"
     *     })
     */
    public v3GetPrice(
        request: TurquoiseHealthApi.V3GetPriceRequest,
        requestOptions?: ConsumerPricingClient.RequestOptions,
    ): core.HttpResponsePromise<TurquoiseHealthApi.ProviderPackagePrice> {
        return core.HttpResponsePromise.fromPromise(this.__v3GetPrice(request, requestOptions));
    }

    private async __v3GetPrice(
        request: TurquoiseHealthApi.V3GetPriceRequest,
        requestOptions?: ConsumerPricingClient.RequestOptions,
    ): Promise<core.WithRawResponse<TurquoiseHealthApi.ProviderPackagePrice>> {
        const { price_id: priceId, expand } = request;
        const _queryParams: Record<string, string | string[] | object | object[] | null> = {};
        if (expand !== undefined) {
            _queryParams.expand = toJson(expand);
        }

        const _authRequest: core.AuthRequest = await this._options.authProvider.getAuthRequest();
        const _headers: core.Fetcher.Args["headers"] = mergeHeaders(
            _authRequest.headers,
            this._options?.headers,
            requestOptions?.headers,
        );
        const _response = await core.fetcher({
            url: core.url.join(
                (await core.Supplier.get(this._options.baseUrl)) ??
                    (await core.Supplier.get(this._options.environment)) ??
                    environments.TurquoiseHealthApiEnvironment.Default,
                `v3/prices/${core.url.encodePathParam(priceId)}`,
            ),
            method: "GET",
            headers: _headers,
            queryParameters: { ..._queryParams, ...requestOptions?.queryParams },
            timeoutMs: (requestOptions?.timeoutInSeconds ?? this._options?.timeoutInSeconds ?? 60) * 1000,
            maxRetries: requestOptions?.maxRetries ?? this._options?.maxRetries,
            abortSignal: requestOptions?.abortSignal,
            fetchFn: this._options?.fetch,
            logging: this._options.logging,
        });
        if (_response.ok) {
            return {
                data: _response.body as TurquoiseHealthApi.ProviderPackagePrice,
                rawResponse: _response.rawResponse,
            };
        }

        if (_response.error.reason === "status-code") {
            switch (_response.error.statusCode) {
                case 400:
                    throw new TurquoiseHealthApi.BadRequestError(
                        _response.error.body as unknown,
                        _response.rawResponse,
                    );
                case 404:
                    throw new TurquoiseHealthApi.NotFoundError(_response.error.body as unknown, _response.rawResponse);
                case 422:
                    throw new TurquoiseHealthApi.UnprocessableEntityError(
                        _response.error.body as unknown,
                        _response.rawResponse,
                    );
                case 429:
                    throw new TurquoiseHealthApi.TooManyRequestsError(
                        _response.error.body as unknown,
                        _response.rawResponse,
                    );
                case 500:
                    throw new TurquoiseHealthApi.InternalServerError(
                        _response.error.body as unknown,
                        _response.rawResponse,
                    );
                default:
                    throw new errors.TurquoiseHealthApiError({
                        statusCode: _response.error.statusCode,
                        body: _response.error.body,
                        rawResponse: _response.rawResponse,
                    });
            }
        }

        switch (_response.error.reason) {
            case "non-json":
                throw new errors.TurquoiseHealthApiError({
                    statusCode: _response.error.statusCode,
                    body: _response.error.rawBody,
                    rawResponse: _response.rawResponse,
                });
            case "body-is-null":
                throw new errors.TurquoiseHealthApiError({
                    statusCode: _response.error.statusCode,
                    rawResponse: _response.rawResponse,
                });
            case "timeout":
                throw new errors.TurquoiseHealthApiTimeoutError(
                    "Timeout exceeded when calling GET /v3/prices/{price_id}.",
                );
            case "unknown":
                throw new errors.TurquoiseHealthApiError({
                    message: _response.error.errorMessage,
                    rawResponse: _response.rawResponse,
                });
        }
    }

    /**
     * Get personalized cost estimates for this member. If we haven't checked their eligibility yet, you'll get a 202 back. Just retry in a bit. The member must have given consent (`consent_attested` must be true).
     *
     * @param {TurquoiseHealthApi.ConsumerSitePersonalizedEstimatesQueryRequest} request
     * @param {ConsumerPricingClient.RequestOptions} requestOptions - Request-specific configuration.
     *
     * @throws {@link TurquoiseHealthApi.BadRequestError}
     * @throws {@link TurquoiseHealthApi.UnauthorizedError}
     * @throws {@link TurquoiseHealthApi.ForbiddenError}
     * @throws {@link TurquoiseHealthApi.NotFoundError}
     * @throws {@link TurquoiseHealthApi.UnprocessableEntityError}
     * @throws {@link TurquoiseHealthApi.TooManyRequestsError}
     * @throws {@link TurquoiseHealthApi.InternalServerError}
     * @throws {@link TurquoiseHealthApi.BadGatewayError}
     * @throws {@link TurquoiseHealthApi.ServiceUnavailableError}
     *
     * @example
     *     await client.consumerPricing.v3ListPersonalizedEstimates({
     *         package_id: "GA003",
     *         provider_id: "5756",
     *         pricing: {
     *             type: "negotiated",
     *             network_id: "-3776001016975145508"
     *         },
     *         member_eligibility: {
     *             first_name: "test123",
     *             last_name: "test123",
     *             date_of_birth: "2001-01-01",
     *             member_id: "test123",
     *             consent_attested: "consent_attested"
     *         },
     *         sort_direction: "asc",
     *         page_size: 25
     *     })
     */
    public v3ListPersonalizedEstimates(
        request: TurquoiseHealthApi.ConsumerSitePersonalizedEstimatesQueryRequest,
        requestOptions?: ConsumerPricingClient.RequestOptions,
    ): core.HttpResponsePromise<TurquoiseHealthApi.V3ListPersonalizedEstimatesResponse> {
        return core.HttpResponsePromise.fromPromise(this.__v3ListPersonalizedEstimates(request, requestOptions));
    }

    private async __v3ListPersonalizedEstimates(
        request: TurquoiseHealthApi.ConsumerSitePersonalizedEstimatesQueryRequest,
        requestOptions?: ConsumerPricingClient.RequestOptions,
    ): Promise<core.WithRawResponse<TurquoiseHealthApi.V3ListPersonalizedEstimatesResponse>> {
        const { expand, ..._body } = request;
        const _queryParams: Record<string, string | string[] | object | object[] | null> = {};
        if (expand != null) {
            if (Array.isArray(expand)) {
                _queryParams.expand = expand.map((item) => item);
            } else {
                _queryParams.expand = expand;
            }
        }

        const _headers: core.Fetcher.Args["headers"] = mergeHeaders(this._options?.headers, requestOptions?.headers);
        const _response = await core.fetcher({
            url: core.url.join(
                (await core.Supplier.get(this._options.baseUrl)) ??
                    (await core.Supplier.get(this._options.environment)) ??
                    environments.TurquoiseHealthApiEnvironment.Default,
                "v3/personalized-estimates",
            ),
            method: "POST",
            headers: _headers,
            contentType: "application/json",
            queryParameters: { ..._queryParams, ...requestOptions?.queryParams },
            requestType: "json",
            body: _body,
            timeoutMs: (requestOptions?.timeoutInSeconds ?? this._options?.timeoutInSeconds ?? 60) * 1000,
            maxRetries: requestOptions?.maxRetries ?? this._options?.maxRetries,
            abortSignal: requestOptions?.abortSignal,
            fetchFn: this._options?.fetch,
            logging: this._options.logging,
        });
        if (_response.ok) {
            return {
                data: _response.body as TurquoiseHealthApi.V3ListPersonalizedEstimatesResponse,
                rawResponse: _response.rawResponse,
            };
        }

        if (_response.error.reason === "status-code") {
            switch (_response.error.statusCode) {
                case 400:
                    throw new TurquoiseHealthApi.BadRequestError(
                        _response.error.body as unknown,
                        _response.rawResponse,
                    );
                case 401:
                    throw new TurquoiseHealthApi.UnauthorizedError(
                        _response.error.body as TurquoiseHealthApi.ConsumerSitePersonalizedEstimateErrorResponse,
                        _response.rawResponse,
                    );
                case 403:
                    throw new TurquoiseHealthApi.ForbiddenError(
                        _response.error.body as TurquoiseHealthApi.ConsumerSitePersonalizedEstimateErrorResponse,
                        _response.rawResponse,
                    );
                case 404:
                    throw new TurquoiseHealthApi.NotFoundError(_response.error.body as unknown, _response.rawResponse);
                case 422:
                    throw new TurquoiseHealthApi.UnprocessableEntityError(
                        _response.error.body as unknown,
                        _response.rawResponse,
                    );
                case 429:
                    throw new TurquoiseHealthApi.TooManyRequestsError(
                        _response.error.body as unknown,
                        _response.rawResponse,
                    );
                case 500:
                    throw new TurquoiseHealthApi.InternalServerError(
                        _response.error.body as unknown,
                        _response.rawResponse,
                    );
                case 502:
                    throw new TurquoiseHealthApi.BadGatewayError(
                        _response.error.body as TurquoiseHealthApi.ConsumerSitePersonalizedEstimateErrorResponse,
                        _response.rawResponse,
                    );
                case 503:
                    throw new TurquoiseHealthApi.ServiceUnavailableError(
                        _response.error.body as TurquoiseHealthApi.ConsumerSitePersonalizedEstimateErrorResponse,
                        _response.rawResponse,
                    );
                default:
                    throw new errors.TurquoiseHealthApiError({
                        statusCode: _response.error.statusCode,
                        body: _response.error.body,
                        rawResponse: _response.rawResponse,
                    });
            }
        }

        switch (_response.error.reason) {
            case "non-json":
                throw new errors.TurquoiseHealthApiError({
                    statusCode: _response.error.statusCode,
                    body: _response.error.rawBody,
                    rawResponse: _response.rawResponse,
                });
            case "body-is-null":
                throw new errors.TurquoiseHealthApiError({
                    statusCode: _response.error.statusCode,
                    rawResponse: _response.rawResponse,
                });
            case "timeout":
                throw new errors.TurquoiseHealthApiTimeoutError(
                    "Timeout exceeded when calling POST /v3/personalized-estimates.",
                );
            case "unknown":
                throw new errors.TurquoiseHealthApiError({
                    message: _response.error.errorMessage,
                    rawResponse: _response.rawResponse,
                });
        }
    }

    /**
     * Compare what this member would pay out-of-pocket across providers for the givenpackage. You'll get back the min, max, average, median, and quartiles. If we haven't checked their eligibility yet, you'll get a 202 back, just retry in a bit. The member must have given consent (`consent_attested` must be true).
     *
     * @param {TurquoiseHealthApi.ConsumerSitePriceComparisonInput} request
     * @param {ConsumerPricingClient.RequestOptions} requestOptions - Request-specific configuration.
     *
     * @throws {@link TurquoiseHealthApi.BadRequestError}
     * @throws {@link TurquoiseHealthApi.UnauthorizedError}
     * @throws {@link TurquoiseHealthApi.ForbiddenError}
     * @throws {@link TurquoiseHealthApi.NotFoundError}
     * @throws {@link TurquoiseHealthApi.UnprocessableEntityError}
     * @throws {@link TurquoiseHealthApi.TooManyRequestsError}
     * @throws {@link TurquoiseHealthApi.InternalServerError}
     * @throws {@link TurquoiseHealthApi.BadGatewayError}
     * @throws {@link TurquoiseHealthApi.ServiceUnavailableError}
     *
     * @example
     *     await client.consumerPricing.v3ComparePersonalizedEstimates({
     *         package_id: "GA003",
     *         pricing: {
     *             type: "negotiated",
     *             network_id: "-3776001016975145508"
     *         },
     *         member_eligibility: {
     *             first_name: "test123",
     *             last_name: "test123",
     *             date_of_birth: "2001-01-01",
     *             member_id: "test123",
     *             consent_attested: "consent_attested"
     *         },
     *         location: {
     *             zip: "80218"
     *         }
     *     })
     */
    public v3ComparePersonalizedEstimates(
        request: TurquoiseHealthApi.ConsumerSitePriceComparisonInput,
        requestOptions?: ConsumerPricingClient.RequestOptions,
    ): core.HttpResponsePromise<TurquoiseHealthApi.ConsumerSitePriceComparison> {
        return core.HttpResponsePromise.fromPromise(this.__v3ComparePersonalizedEstimates(request, requestOptions));
    }

    private async __v3ComparePersonalizedEstimates(
        request: TurquoiseHealthApi.ConsumerSitePriceComparisonInput,
        requestOptions?: ConsumerPricingClient.RequestOptions,
    ): Promise<core.WithRawResponse<TurquoiseHealthApi.ConsumerSitePriceComparison>> {
        const _headers: core.Fetcher.Args["headers"] = mergeHeaders(this._options?.headers, requestOptions?.headers);
        const _response = await core.fetcher({
            url: core.url.join(
                (await core.Supplier.get(this._options.baseUrl)) ??
                    (await core.Supplier.get(this._options.environment)) ??
                    environments.TurquoiseHealthApiEnvironment.Default,
                "v3/personalized-estimates/compare",
            ),
            method: "POST",
            headers: _headers,
            contentType: "application/json",
            queryParameters: requestOptions?.queryParams,
            requestType: "json",
            body: request,
            timeoutMs: (requestOptions?.timeoutInSeconds ?? this._options?.timeoutInSeconds ?? 60) * 1000,
            maxRetries: requestOptions?.maxRetries ?? this._options?.maxRetries,
            abortSignal: requestOptions?.abortSignal,
            fetchFn: this._options?.fetch,
            logging: this._options.logging,
        });
        if (_response.ok) {
            return {
                data: _response.body as TurquoiseHealthApi.ConsumerSitePriceComparison,
                rawResponse: _response.rawResponse,
            };
        }

        if (_response.error.reason === "status-code") {
            switch (_response.error.statusCode) {
                case 400:
                    throw new TurquoiseHealthApi.BadRequestError(
                        _response.error.body as unknown,
                        _response.rawResponse,
                    );
                case 401:
                    throw new TurquoiseHealthApi.UnauthorizedError(
                        _response.error.body as TurquoiseHealthApi.ConsumerSitePersonalizedEstimateErrorResponse,
                        _response.rawResponse,
                    );
                case 403:
                    throw new TurquoiseHealthApi.ForbiddenError(
                        _response.error.body as TurquoiseHealthApi.ConsumerSitePersonalizedEstimateErrorResponse,
                        _response.rawResponse,
                    );
                case 404:
                    throw new TurquoiseHealthApi.NotFoundError(_response.error.body as unknown, _response.rawResponse);
                case 422:
                    throw new TurquoiseHealthApi.UnprocessableEntityError(
                        _response.error.body as unknown,
                        _response.rawResponse,
                    );
                case 429:
                    throw new TurquoiseHealthApi.TooManyRequestsError(
                        _response.error.body as unknown,
                        _response.rawResponse,
                    );
                case 500:
                    throw new TurquoiseHealthApi.InternalServerError(
                        _response.error.body as unknown,
                        _response.rawResponse,
                    );
                case 502:
                    throw new TurquoiseHealthApi.BadGatewayError(
                        _response.error.body as TurquoiseHealthApi.ConsumerSitePersonalizedEstimateErrorResponse,
                        _response.rawResponse,
                    );
                case 503:
                    throw new TurquoiseHealthApi.ServiceUnavailableError(
                        _response.error.body as TurquoiseHealthApi.ConsumerSitePersonalizedEstimateErrorResponse,
                        _response.rawResponse,
                    );
                default:
                    throw new errors.TurquoiseHealthApiError({
                        statusCode: _response.error.statusCode,
                        body: _response.error.body,
                        rawResponse: _response.rawResponse,
                    });
            }
        }

        switch (_response.error.reason) {
            case "non-json":
                throw new errors.TurquoiseHealthApiError({
                    statusCode: _response.error.statusCode,
                    body: _response.error.rawBody,
                    rawResponse: _response.rawResponse,
                });
            case "body-is-null":
                throw new errors.TurquoiseHealthApiError({
                    statusCode: _response.error.statusCode,
                    rawResponse: _response.rawResponse,
                });
            case "timeout":
                throw new errors.TurquoiseHealthApiTimeoutError(
                    "Timeout exceeded when calling POST /v3/personalized-estimates/compare.",
                );
            case "unknown":
                throw new errors.TurquoiseHealthApiError({
                    message: _response.error.errorMessage,
                    rawResponse: _response.rawResponse,
                });
        }
    }
}
