# This file was auto-generated by Fern from our API Definition.

import typing

from ...types.no_data_response import NoDataResponse
from ...types.provider_breakdown import ProviderBreakdown

GetProviderSspPricesResponse = typing.Union[ProviderBreakdown, NoDataResponse]
