// This file was auto-generated by Fern from our API Definition.

export const CareNavSortType = {
    PriceAsc: "price-asc",
    RatingDesc: "rating-desc",
} as const;
export type CareNavSortType = (typeof CareNavSortType)[keyof typeof CareNavSortType];
