// This file was auto-generated by Fern from our API Definition.

/**
 * Member out-of-pocket estimate at the (provider × ssp × [network]) grain.  Inherits `Rate`; the inherited `amount`/`amount_cents` carry the member's cost-share total (out-of-pocket), not the full negotiated price. The breakdown fields explain how that total is composed.
 */
export interface ConsumerSiteModulesConsumerPricingV2DtosRatePersonalizedEstimate {
    /** `cash` ⇔ `network_id is null`. `negotiated` otherwise. */
    price_type: string;
    /** Provider identifier. Upstream-derived from the dataset and may change as the dataset is rebuilt. Do not bake into URLs, bookmarks, or persistent storage. */
    provider_id: string;
    /** SSP identifier. Upstream-derived from the dataset and may change as the dataset is rebuilt. Do not bake into URLs, bookmarks, or persistent storage. */
    ssp_id: string;
    /** Signed 64-bit integer serialized as a string to preserve precision in JSON. */
    network_id?: string | null;
    /** String-decimal money value, e.g. "1250.00". */
    amount: string;
    /** Integer minor units, e.g. 125000. */
    amount_cents: number;
    /** ISO currency code. Always USD today. */
    currency?: string | null;
    /** Portion of the estimate applied to the deductible. */
    amount_towards_deductible: string;
    /** Integer minor units of `amount_towards_deductible`. */
    amount_towards_deductible_cents: number;
    /** Portion of the estimate that is a flat copay. */
    amount_towards_copayment: string;
    /** Integer minor units of `amount_towards_copayment`. */
    amount_towards_copayment_cents: number;
    /** Portion of the estimate that is coinsurance. */
    amount_towards_coinsurance: string;
    /** Integer minor units of `amount_towards_coinsurance`. */
    amount_towards_coinsurance_cents: number;
    /** Whether the member's deductible is fully met by/at this estimate. */
    is_deductible_met: boolean;
    /** Whether the member's out-of-pocket max is met by/at this estimate. */
    is_out_of_pocket_met: boolean;
    /** The sub-package the estimate was computed over. */
    sub_package_code: string;
    /** Full pre-insurance negotiated price for context. */
    total_negotiated_price: string;
    /** Integer minor units of `total_negotiated_price`. */
    total_negotiated_price_cents: number;
}
