// This file was auto-generated by Fern from our API Definition.

/**
 * RateBreakdownLineItem
 */
export interface ConsumerSiteRateBreakdownLineItem {
    /** CPT or HCPCS code. */
    line_code: string;
    /** Billing code type. */
    code_type: string;
    /** Fee category (professional, facility, etc). */
    fee_type: string;
    /** Human-readable line item description. */
    description: string;
    /** Likelihood this line item is part of the SSP. */
    line_item_association_rate: ConsumerSiteRateBreakdownLineItem.LineItemAssociationRate;
}

export namespace ConsumerSiteRateBreakdownLineItem {
    /**
     * Likelihood this line item is part of the SSP.
     */
    export type LineItemAssociationRate = number | number;
}
