// This file was auto-generated by Fern from our API Definition.

import type * as TurquoiseHealthApi from "../index.js";

/**
 * ModulesConsumerPricingV3DtosPersonalizedEstimatePersonalizedEstimate
 */
export interface ConsumerSiteModulesConsumerPricingV3DtosPersonalizedEstimatePersonalizedEstimate {
    object?: string | null;
    provider: TurquoiseHealthApi.ConsumerSiteEntityRef;
    package: TurquoiseHealthApi.ConsumerSiteEntityRef;
    pricing: TurquoiseHealthApi.ConsumerSitePricingResolved;
    /** Amount that insurance company + patient pay for the service. */
    total_allowed_amount: TurquoiseHealthApi.ConsumerSiteMoney;
    member_cost_share: TurquoiseHealthApi.ConsumerSiteMemberCostShare;
    sub_package_id?: string | null;
    line_items?: TurquoiseHealthApi.ConsumerSiteLineItem[] | null;
}
