// This file was auto-generated by Fern from our API Definition.

import type * as TurquoiseHealthApi from "../index.js";

/**
 * ListEnvelopePersonalizedEstimate
 */
export interface ConsumerSiteListEnvelopePersonalizedEstimate {
    object?: string | null;
    items: TurquoiseHealthApi.ConsumerSiteModulesConsumerPricingV3DtosPersonalizedEstimatePersonalizedEstimate[];
    page: TurquoiseHealthApi.ConsumerSiteModulesConsumerPricingV3DtosCommonPageMeta;
    no_data_reason?: TurquoiseHealthApi.ConsumerSiteNoDataReason | null;
    /** Human-readable caveats about what this result does and does not imply. */
    disclosures?: string[] | null;
}
