// This file was auto-generated by Fern from our API Definition.

/** Stable error code registry for the v3 surface. Switch on this in code. */
export const ErrorCode = {
    InvalidRequest: "invalid_request",
    InvalidIdFormat: "invalid_id_format",
    InsufficientScope: "insufficient_scope",
    LocationAmbiguous: "location_ambiguous",
    UnresolvableLocation: "unresolvable_location",
    NotFound: "not_found",
    InvalidExpand: "invalid_expand",
    PermissionDenied: "permission_denied",
    RateLimited: "rate_limited",
    SearchUnavailable: "search_unavailable",
    ConflictingParameters: "conflicting_parameters",
} as const;
export type ErrorCode = (typeof ErrorCode)[keyof typeof ErrorCode];
