// This file was auto-generated by Fern from our API Definition.

export interface ErrorDetail {
    /** Field that caused the error, if applicable */
    field?: string | null;
    /** Description of the error */
    message: string;
}
