// This file was auto-generated by Fern from our API Definition.

import type * as TurquoiseHealthApi from "../index.js";

export interface InsuranceNetworkPage {
    results: TurquoiseHealthApi.InsuranceNetwork[];
    page_size?: number | null;
    count: number;
    /** Set when results are empty. `no_data` if no matching records exist; `permission_denied` if matching records exist but are excluded by your data permissions. */
    no_data_reason?: TurquoiseHealthApi.NoDataReason | null;
}
