// This file was auto-generated by Fern from our API Definition.

export interface InsuranceNetwork {
    /** Insurance network identifier */
    network_id: string;
    /** Insurance network name */
    network_name: string;
    /** Insurance payer name */
    payer_name: string;
    /** Insurance payer identifier */
    payer_id: string;
}
