// This file was auto-generated by Fern from our API Definition.

import type * as TurquoiseHealthApi from "../index.js";

export interface ListEnvelopeNetwork {
    object?: ListEnvelopeNetwork.Object_;
    items: TurquoiseHealthApi.Network[];
    page: TurquoiseHealthApi.PageMeta;
    /** Set when `items` is empty. `no_data` means no matching records exist; `permission_denied` means matching records exist but are excluded by your data permissions. */
    no_data_reason?: TurquoiseHealthApi.NoDataReason | null;
    /** Human-readable caveats about what this result does and does not imply. */
    disclosures?: string[];
}

export namespace ListEnvelopeNetwork {
    export const Object_ = {
        List: "list",
    } as const;
    export type Object_ = (typeof Object_)[keyof typeof Object_];
}
