// This file was auto-generated by Fern from our API Definition.

import type * as TurquoiseHealthApi from "../index.js";

/**
 * Structured location intent: exactly one of the three modes.
 */
export interface Location {
    near?: TurquoiseHealthApi.LocationNear | null;
    within?: TurquoiseHealthApi.LocationWithin | null;
    /** Resolves the ZIP to its centroid, then runs `near`. */
    zip?: string | null;
}
