// This file was auto-generated by Fern from our API Definition.

import type * as TurquoiseHealthApi from "../index.js";

export interface Network {
    object?: Network.Object_;
    /** Network identifier. Upstream-derived from the dataset and may change as the dataset is rebuilt. Re-resolve via search rather than persisting long-term. */
    id: string;
    /** Display name of the network. */
    name: string;
    /** The network's payer as an {id, name} stub; the full entity lives at /v3/payers/{id}. */
    payer: TurquoiseHealthApi.EntityRef;
    /** Query-relative metadata (search only). */
    context?: TurquoiseHealthApi.SearchContext | null;
}

export namespace Network {
    export const Object_ = {
        Network: "network",
    } as const;
    export type Object_ = (typeof Object_)[keyof typeof Object_];
}
