// This file was auto-generated by Fern from our API Definition.

/**
 * Insurance network row.
 */
export interface Network {
    /** Network identifier. Int64String — JSON string-wrapped 64-bit integer, because JSON cannot safely represent values above 2^53. Upstream-derived from the dataset and may change as the dataset is rebuilt. Do not bake into URLs, bookmarks, or persistent storage. */
    id: string;
    /** Insurance network name. */
    name: string;
    /** Insurance payer identifier. Upstream-derived from the dataset and may change as the dataset is rebuilt. Do not bake into URLs, bookmarks, or persistent storage. */
    payer_id: string;
    /** Insurance payer name. */
    payer_name: string;
    /** Semantic similarity score (0-1) when results are from a search query. Higher is more relevant. */
    score?: number | null;
}
