// This file was auto-generated by Fern from our API Definition.

import type * as TurquoiseHealthApi from "../index.js";

export interface Package {
    object?: Package.Object_;
    /** Package identifier. Upstream-derived from the dataset and may change as the dataset is rebuilt. Re-resolve via search rather than persisting long-term. */
    id: string;
    /** Package taxonomy. Only Standard Service Packages ('ssp') are served today; other package types (e.g. consumer bundles) may be added as they become servable. */
    type?: Package.Type;
    /** Display name of the service package. */
    name: string;
    /** Patient-facing description of the package. */
    description?: string | null;
    /** The package's comprehensive anchor (base) billing codes — the rows billed as the anchor itself, not its professional-fee counterparts. Every package is expected to carry at least one. In the current catalog every anchor code maps to exactly one package (measured 07/2026), so ?anchor_code= behaves as a unique lookup — but that is an observed property, not a guarantee: the lookup returns every package anchored by the code. */
    anchor_codes?: TurquoiseHealthApi.BillingCode[];
    disclosures?: string[];
    /** Query-relative metadata (search only). */
    context?: TurquoiseHealthApi.SearchContext | null;
}

export namespace Package {
    export const Object_ = {
        Package: "package",
    } as const;
    export type Object_ = (typeof Object_)[keyof typeof Object_];
    /** Package taxonomy. Only Standard Service Packages ('ssp') are served today; other package types (e.g. consumer bundles) may be added as they become servable. */
    export const Type = {
        Ssp: "ssp",
    } as const;
    export type Type = (typeof Type)[keyof typeof Type];
}
