// This file was auto-generated by Fern from our API Definition.

/** Optional relations the price detail endpoint can inline via `expand`. */
export const PriceExpand = {
    LineItems: "line_items",
} as const;
export type PriceExpand = (typeof PriceExpand)[keyof typeof PriceExpand];
