// This file was auto-generated by Fern from our API Definition.

import type * as TurquoiseHealthApi from "../index.js";

export interface PriceDetail {
    max_price: number;
    max_price_billing_code: string;
    /** Signed 64-bit integer serialized as a string to preserve precision in JSON. */
    network_id: string;
    provider_id: number;
    ssp_id: string;
    line_items: TurquoiseHealthApi.PackageLineItem[];
}
