// This file was auto-generated by Fern from our API Definition.

/** Sort options for price listings. `distance` requires a near/zip location. */
export const PriceSort = {
    Total: "total",
    Distance: "distance",
} as const;
export type PriceSort = (typeof PriceSort)[keyof typeof PriceSort];
