// This file was auto-generated by Fern from our API Definition.

export interface ProviderLocationDetails {
    /** Provider street address */
    street_address: string;
    /** Provider latitude */
    latitude?: number | null;
    /** Provider longitude */
    longitude?: number | null;
    /** Distance from the search location in meters */
    distance_in_meters?: number | null;
    /** CMS overall hospital quality rating (1-5) */
    hospital_overall_rating?: number | null;
}
