// This file was auto-generated by Fern from our API Definition.

import type * as TurquoisehealthApi from "../index.js";

export interface RateBreakdown {
    price_type: RateBreakdown.PriceType;
    provider_id: string;
    ssp_id: string;
    /** Signed 64-bit integer serialized as a string to preserve precision in JSON. */
    network_id?: string | null;
    /** SSP-total amount from /prices. */
    total_amount: string;
    total_amount_cents: number;
    currency?: string;
    line_items: TurquoisehealthApi.RateBreakdownLineItem[];
}

export namespace RateBreakdown {
    export const PriceType = {
        Cash: "cash",
        Negotiated: "negotiated",
    } as const;
    export type PriceType = (typeof PriceType)[keyof typeof PriceType];
}
