// This file was auto-generated by Fern from our API Definition.

import type * as TurquoiseHealthApi from "../index.js";

export interface V3ComparisonStats {
    min: TurquoiseHealthApi.V3Money;
    max: TurquoiseHealthApi.V3Money;
    avg: TurquoiseHealthApi.V3Money;
    median: TurquoiseHealthApi.V3Money;
    q1: TurquoiseHealthApi.V3Money;
    q3: TurquoiseHealthApi.V3Money;
}
