// This file was auto-generated by Fern from our API Definition.

/**
 * Two-field reference stub. `expand=` swaps it for the full entity.
 *
 * `name` is nullable by design: 0.8% of priced providers have no reference
 * row (measured 07/2026), and the v3 rule is to emit the stub with a null
 * name rather than silently dropping the priced row.
 */
export interface V3EntityRef {
    /** Entity identifier. Upstream-derived from the dataset and may change as the dataset is rebuilt. Re-resolve via search rather than persisting long-term. */
    id: string;
    /** Display name; null when reference data is missing. */
    name?: string | null;
}
