// This file was auto-generated by Fern from our API Definition.

import type * as TurquoisehealthApi from "../index.js";

export interface V3ErrorResponse {
    error: TurquoisehealthApi.V3ErrorPayload;
}
