// This file was auto-generated by Fern from our API Definition.

import type * as TurquoiseHealthApi from "../index.js";

export interface V3ListEnvelopePackage {
    object?: V3ListEnvelopePackage.Object_;
    items: TurquoiseHealthApi.V3Package[];
    page: TurquoiseHealthApi.V3PageMeta;
    /** Set when `items` is empty. `no_data` means no matching records exist; `permission_denied` means matching records exist but are excluded by your data permissions. */
    no_data_reason?: TurquoiseHealthApi.V3NoDataReason | null;
    /** Human-readable caveats about what this result does and does not imply. */
    disclosures?: string[];
}

export namespace V3ListEnvelopePackage {
    export const Object_ = {
        List: "list",
    } as const;
    export type Object_ = (typeof Object_)[keyof typeof Object_];
}
