// This file was auto-generated by Fern from our API Definition.

/**
 * A component of a package's composition (from `api_ssp_contents`).
 */
export interface V3LineItem {
    /** Billing code. */
    code: string;
    /** Billing code type. */
    code_type: string;
    /** Fee category: base_code, facility_fee, professional_fee, optional_fee. */
    fee_type: string;
    /** Human-readable line item description. */
    description: string;
    /** Likelihood this line item is part of the package (0-1). */
    association_rate: number;
}
