// This file was auto-generated by Fern from our API Definition.

import type * as TurquoisehealthApi from "../index.js";

/**
 * The resolved payment arrangement on a price. Cash prices omit
 * network/payer; negotiated prices carry both as reference stubs.
 */
export interface V3PricingResolved {
    type: V3PricingResolved.Type;
    network?: TurquoisehealthApi.V3EntityRef | null;
    payer?: TurquoisehealthApi.V3EntityRef | null;
}

export namespace V3PricingResolved {
    export const Type = {
        Cash: "cash",
        Negotiated: "negotiated",
    } as const;
    export type Type = (typeof Type)[keyof typeof Type];
}
