// This file was auto-generated by Fern from our API Definition.

import type * as TurquoisehealthApi from "../index.js";

export interface V3ProviderPackagePrice {
    object?: V3ProviderPackagePrice.Object_;
    /** Price identifier (encodes the provider × package × pricing grain). Upstream-derived from the dataset and may change as the dataset is rebuilt. Re-resolve via search rather than persisting long-term. */
    id: string;
    /** Full provider entity (always inlined). */
    provider: TurquoisehealthApi.V3Provider;
    /** Reference stub. */
    package: TurquoisehealthApi.V3EntityRef;
    pricing: TurquoisehealthApi.V3PricingResolved;
    /** The package-total price at this grain. */
    total: TurquoisehealthApi.V3Money;
    /** Package composition; present when expand=line_items (detail only). */
    line_items?: TurquoisehealthApi.V3LineItem[] | null;
    context?: TurquoisehealthApi.V3MatchContext | null;
}

export namespace V3ProviderPackagePrice {
    export const Object_ = {
        Price: "price",
    } as const;
    export type Object_ = (typeof Object_)[keyof typeof Object_];
}
