// This file was auto-generated by Fern from our API Definition.

import type * as TurquoisehealthApi from "../index.js";

export interface V3Provider {
    object?: V3Provider.Object_;
    /** Provider identifier. Upstream-derived from the dataset and may change as the dataset is rebuilt. Re-resolve via search rather than persisting long-term. */
    id: string;
    /** Provider facility or organization name. */
    name: string;
    /** Provider type as reported in the dataset. */
    type?: string | null;
    /** National Provider Identifier. */
    npi?: string | null;
    address: TurquoisehealthApi.V3ProviderAddress;
    /** Query-relative metadata (near/zip mode only). */
    context?: TurquoisehealthApi.V3MatchContext | null;
}

export namespace V3Provider {
    export const Object_ = {
        Provider: "provider",
    } as const;
    export type Object_ = (typeof Object_)[keyof typeof Object_];
}
