# This file was auto-generated by Fern from our API Definition.

import typing

from ..core.client_wrapper import AsyncClientWrapper, SyncClientWrapper
from ..core.request_options import RequestOptions
from ..types.v3list_envelope_line_item import V3ListEnvelopeLineItem
from ..types.v3list_envelope_network import V3ListEnvelopeNetwork
from ..types.v3list_envelope_package import V3ListEnvelopePackage
from ..types.v3list_envelope_payer import V3ListEnvelopePayer
from ..types.v3list_envelope_provider import V3ListEnvelopeProvider
from ..types.v3list_envelope_provider_package_price import V3ListEnvelopeProviderPackagePrice
from ..types.v3location import V3Location
from ..types.v3network import V3Network
from ..types.v3package import V3Package
from ..types.v3payer import V3Payer
from ..types.v3price_comparison import V3PriceComparison
from ..types.v3price_expand import V3PriceExpand
from ..types.v3price_sort import V3PriceSort
from ..types.v3provider import V3Provider
from ..types.v3provider_package_price import V3ProviderPackagePrice
from .raw_client import AsyncRawConsumerPricingClient, RawConsumerPricingClient
from .types.v3prices_compare_request_pricing import V3PricesCompareRequestPricing
from .types.v3prices_query_request_pricing import V3PricesQueryRequestPricing
from .types.v3prices_query_request_sort_direction import V3PricesQueryRequestSortDirection

# this is used as the default value for optional parameters
OMIT = typing.cast(typing.Any, ...)


class ConsumerPricingClient:
    def __init__(self, *, client_wrapper: SyncClientWrapper):
        self._raw_client = RawConsumerPricingClient(client_wrapper=client_wrapper)

    @property
    def with_raw_response(self) -> RawConsumerPricingClient:
        """
        Retrieves a raw implementation of this client that returns raw responses.

        Returns
        -------
        RawConsumerPricingClient
        """
        return self._raw_client

    def v3list_providers(
        self,
        *,
        name: typing.Optional[str] = None,
        npi: typing.Optional[str] = None,
        type: typing.Optional[str] = None,
        package_id: typing.Optional[str] = None,
        network_id: typing.Optional[str] = None,
        payer_id: typing.Optional[str] = None,
        search: typing.Optional[str] = None,
        min_score: typing.Optional[float] = None,
        page_size: typing.Optional[int] = None,
        cursor: typing.Optional[str] = None,
        location_near_lat: typing.Optional[float] = None,
        location_near_lng: typing.Optional[float] = None,
        location_near_radius_m: typing.Optional[int] = None,
        location_within_state: typing.Optional[str] = None,
        location_within_cbsa: typing.Optional[str] = None,
        location_within_zip_codes: typing.Optional[str] = None,
        location_zip: typing.Optional[str] = None,
        request_options: typing.Optional[RequestOptions] = None,
    ) -> V3ListEnvelopeProvider:
        """
        Retrieve a list of providers, filtered over a search by name, NPI, provider type, or location. Additionally, filter to a list of providers with Turquoise price estimates available by a selected payer, network, or package. Results reflect provider, payer, and package combinations that Turquoise has priced services for; the list may not be comprehensive of all contacted payer networks or services that are available.

        Parameters
        ----------
        name : typing.Optional[str]
            Case-insensitive substring match on provider name.

        npi : typing.Optional[str]
            Exact NPI match.

        type : typing.Optional[str]
            Provider type as reported in the dataset (exact match).

        package_id : typing.Optional[str]
            Providers with at least one price for this package.

        network_id : typing.Optional[str]
            Providers with at least one price under this network (combined with package_id/payer_id, the same price row must match).

        payer_id : typing.Optional[str]
            Providers priced under any of this payer's networks (combined with other relationship filters, the same price row must match).

        search : typing.Optional[str]
            Semantic search over provider names. Composes with the other filters and a near/zip location; returns a single relevance-ordered page. 503 search_unavailable until the provider embedding index is populated.

        min_score : typing.Optional[float]
            Minimum similarity score (0-1).

        page_size : typing.Optional[int]

        cursor : typing.Optional[str]
            Opaque cursor from a previous page.next_cursor.

        location_near_lat : typing.Optional[float]

        location_near_lng : typing.Optional[float]

        location_near_radius_m : typing.Optional[int]

        location_within_state : typing.Optional[str]

        location_within_cbsa : typing.Optional[str]

        location_within_zip_codes : typing.Optional[str]
            Comma-separated ZIP codes (exact match, any-of).

        location_zip : typing.Optional[str]
            Resolves the ZIP to its centroid, then runs `near` with the default radius.

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        V3ListEnvelopeProvider
            Successful Response

        Examples
        --------
        from turquoisehealth-api import TurquoiseHealth

        client = TurquoiseHealth(token="YOUR_TOKEN", base_url="https://yourhost.com/path/to/api", )
        client.consumer_pricing.v3list_providers()
        """
        _response = self._raw_client.v3list_providers(
            name=name,
            npi=npi,
            type=type,
            package_id=package_id,
            network_id=network_id,
            payer_id=payer_id,
            search=search,
            min_score=min_score,
            page_size=page_size,
            cursor=cursor,
            location_near_lat=location_near_lat,
            location_near_lng=location_near_lng,
            location_near_radius_m=location_near_radius_m,
            location_within_state=location_within_state,
            location_within_cbsa=location_within_cbsa,
            location_within_zip_codes=location_within_zip_codes,
            location_zip=location_zip,
            request_options=request_options,
        )
        return _response.data

    def v3get_provider_types(self, *, request_options: typing.Optional[RequestOptions] = None) -> typing.List[str]:
        """
        Fetch provider types. Results return valid inputs to filter by provider types across the API.

        Parameters
        ----------
        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        typing.List[str]
            Successful Response

        Examples
        --------
        from turquoisehealth-api import TurquoiseHealth

        client = TurquoiseHealth(token="YOUR_TOKEN", base_url="https://yourhost.com/path/to/api", )
        client.consumer_pricing.v3get_provider_types()
        """
        _response = self._raw_client.v3get_provider_types(request_options=request_options)
        return _response.data

    def v3get_provider(
        self, provider_id: str, *, request_options: typing.Optional[RequestOptions] = None
    ) -> V3Provider:
        """
        Fetch details for a single provider by provider ID.

        Parameters
        ----------
        provider_id : str
            Provider identifier.

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        V3Provider
            Successful Response

        Examples
        --------
        from turquoisehealth-api import TurquoiseHealth

        client = TurquoiseHealth(token="YOUR_TOKEN", base_url="https://yourhost.com/path/to/api", )
        client.consumer_pricing.v3get_provider(provider_id='5756', )
        """
        _response = self._raw_client.v3get_provider(provider_id, request_options=request_options)
        return _response.data

    def v3list_payers(
        self,
        *,
        name: typing.Optional[str] = None,
        provider_id: typing.Optional[str] = None,
        package_id: typing.Optional[str] = None,
        page_size: typing.Optional[int] = None,
        cursor: typing.Optional[str] = None,
        location_near_lat: typing.Optional[float] = None,
        location_near_lng: typing.Optional[float] = None,
        location_near_radius_m: typing.Optional[int] = None,
        location_within_state: typing.Optional[str] = None,
        location_within_cbsa: typing.Optional[str] = None,
        location_within_zip_codes: typing.Optional[str] = None,
        location_zip: typing.Optional[str] = None,
        request_options: typing.Optional[RequestOptions] = None,
    ) -> V3ListEnvelopePayer:
        """
        Retrieve a list of payers, filtered over a search by name, location for care, or specific providers and services priced in the Turquoise data. Location scopes to payers with at least one price at an in-area provider. Results reflect provider, payer, and package combinations that Turquoise has priced services for; the list may not be comprehensive of all contracted providers or services that are available.

        Parameters
        ----------
        name : typing.Optional[str]
            Case-insensitive substring match on payer name.

        provider_id : typing.Optional[str]
            Payers with at least one price at this provider.

        package_id : typing.Optional[str]
            Payers with at least one price for this package.

        page_size : typing.Optional[int]

        cursor : typing.Optional[str]
            Opaque cursor from a previous page.next_cursor.

        location_near_lat : typing.Optional[float]

        location_near_lng : typing.Optional[float]

        location_near_radius_m : typing.Optional[int]

        location_within_state : typing.Optional[str]

        location_within_cbsa : typing.Optional[str]

        location_within_zip_codes : typing.Optional[str]
            Comma-separated ZIP codes (exact match, any-of).

        location_zip : typing.Optional[str]
            Resolves the ZIP to its centroid, then runs `near` with the default radius.

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        V3ListEnvelopePayer
            Successful Response

        Examples
        --------
        from turquoisehealth-api import TurquoiseHealth

        client = TurquoiseHealth(token="YOUR_TOKEN", base_url="https://yourhost.com/path/to/api", )
        client.consumer_pricing.v3list_payers()
        """
        _response = self._raw_client.v3list_payers(
            name=name,
            provider_id=provider_id,
            package_id=package_id,
            page_size=page_size,
            cursor=cursor,
            location_near_lat=location_near_lat,
            location_near_lng=location_near_lng,
            location_near_radius_m=location_near_radius_m,
            location_within_state=location_within_state,
            location_within_cbsa=location_within_cbsa,
            location_within_zip_codes=location_within_zip_codes,
            location_zip=location_zip,
            request_options=request_options,
        )
        return _response.data

    def v3get_payer(self, payer_id: str, *, request_options: typing.Optional[RequestOptions] = None) -> V3Payer:
        """
        Fetch details about a single payer by payer ID.

        Parameters
        ----------
        payer_id : str
            Payer identifier.

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        V3Payer
            Successful Response

        Examples
        --------
        from turquoisehealth-api import TurquoiseHealth

        client = TurquoiseHealth(token="YOUR_TOKEN", base_url="https://yourhost.com/path/to/api", )
        client.consumer_pricing.v3get_payer(payer_id='76', )
        """
        _response = self._raw_client.v3get_payer(payer_id, request_options=request_options)
        return _response.data

    def v3list_networks(
        self,
        *,
        name: typing.Optional[str] = None,
        payer_id: typing.Optional[str] = None,
        provider_id: typing.Optional[str] = None,
        package_id: typing.Optional[str] = None,
        search: typing.Optional[str] = None,
        min_score: typing.Optional[float] = None,
        page_size: typing.Optional[int] = None,
        cursor: typing.Optional[str] = None,
        location_near_lat: typing.Optional[float] = None,
        location_near_lng: typing.Optional[float] = None,
        location_near_radius_m: typing.Optional[int] = None,
        location_within_state: typing.Optional[str] = None,
        location_within_cbsa: typing.Optional[str] = None,
        location_within_zip_codes: typing.Optional[str] = None,
        location_zip: typing.Optional[str] = None,
        request_options: typing.Optional[RequestOptions] = None,
    ) -> V3ListEnvelopeNetwork:
        """
        Retrieve a list of payer networks, filtered over a search by name, payer organization (e.g., Cigna), location for care, or specific providers and services priced in the Turquoise data. Location scopes to payer networks with at least one price at an in-area provider. Results reflect provider, payer network, and package combinations that Turquoise has priced services for; the list may not be comprehensive of all contracted providers or services that are available.

        Parameters
        ----------
        name : typing.Optional[str]
            Case-insensitive substring match on network or payer name.

        payer_id : typing.Optional[str]
            Exact payer id match.

        provider_id : typing.Optional[str]
            Networks with at least one price at this provider.

        package_id : typing.Optional[str]
            Networks with at least one price for this package.

        search : typing.Optional[str]
            Semantic search over network and payer names. Composes with the other filters; returns a single relevance-ordered page (no cursor).

        min_score : typing.Optional[float]
            Minimum similarity score (0-1).

        page_size : typing.Optional[int]

        cursor : typing.Optional[str]
            Opaque cursor from a previous page.next_cursor.

        location_near_lat : typing.Optional[float]

        location_near_lng : typing.Optional[float]

        location_near_radius_m : typing.Optional[int]

        location_within_state : typing.Optional[str]

        location_within_cbsa : typing.Optional[str]

        location_within_zip_codes : typing.Optional[str]
            Comma-separated ZIP codes (exact match, any-of).

        location_zip : typing.Optional[str]
            Resolves the ZIP to its centroid, then runs `near` with the default radius.

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        V3ListEnvelopeNetwork
            Successful Response

        Examples
        --------
        from turquoisehealth-api import TurquoiseHealth

        client = TurquoiseHealth(token="YOUR_TOKEN", base_url="https://yourhost.com/path/to/api", )
        client.consumer_pricing.v3list_networks()
        """
        _response = self._raw_client.v3list_networks(
            name=name,
            payer_id=payer_id,
            provider_id=provider_id,
            package_id=package_id,
            search=search,
            min_score=min_score,
            page_size=page_size,
            cursor=cursor,
            location_near_lat=location_near_lat,
            location_near_lng=location_near_lng,
            location_near_radius_m=location_near_radius_m,
            location_within_state=location_within_state,
            location_within_cbsa=location_within_cbsa,
            location_within_zip_codes=location_within_zip_codes,
            location_zip=location_zip,
            request_options=request_options,
        )
        return _response.data

    def v3get_network(self, network_id: str, *, request_options: typing.Optional[RequestOptions] = None) -> V3Network:
        """
        Fetch details about a single network by network ID.

        Parameters
        ----------
        network_id : str
            Network identifier (string-wrapped 64-bit integer).

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        V3Network
            Successful Response

        Examples
        --------
        from turquoisehealth-api import TurquoiseHealth

        client = TurquoiseHealth(token="YOUR_TOKEN", base_url="https://yourhost.com/path/to/api", )
        client.consumer_pricing.v3get_network(network_id='-3776001016975145508', )
        """
        _response = self._raw_client.v3get_network(network_id, request_options=request_options)
        return _response.data

    def v3list_packages(
        self,
        *,
        name: typing.Optional[str] = None,
        anchor_code: typing.Optional[str] = None,
        provider_id: typing.Optional[str] = None,
        network_id: typing.Optional[str] = None,
        payer_id: typing.Optional[str] = None,
        search: typing.Optional[str] = None,
        min_score: typing.Optional[float] = None,
        page_size: typing.Optional[int] = None,
        cursor: typing.Optional[str] = None,
        request_options: typing.Optional[RequestOptions] = None,
    ) -> V3ListEnvelopePackage:
        """
        Return a list of service packages, filtered over name or anchor code. Additionally, filter to a list of packages with Turquoise price estimates available by a selected payer, network, or provider. Results reflect provider, payer, and package combinations that Turquoise has priced services for; the list may not be comprehensive of all payer networks or providers that support this service. When multiple relationship filters are combined, they must be satisfied by the same price row, so results are always fulfillable via GET /v3/prices.

        Parameters
        ----------
        name : typing.Optional[str]
            Case-insensitive substring match on package name.

        anchor_code : typing.Optional[str]
            Billing code lookup; matches against anchor_codes[].code (package base codes only). Returns every package anchored by the code — exactly one in the current catalog, but uniqueness is not contractual (an anchor's full upstream identity includes revenue code and billing class, which this API collapses).

        provider_id : typing.Optional[str]
            Packages priced at this provider.

        network_id : typing.Optional[str]
            Packages with at least one price under this network (combined with provider_id/payer_id, the same price row must match).

        payer_id : typing.Optional[str]
            Packages priced under any of this payer's networks (combined with other relationship filters, the same price row must match).

        search : typing.Optional[str]
            Semantic search over package name and description. Composes with the other filters; returns a single relevance-ordered page (no cursor). 503 search_unavailable when the embedding index is not populated.

        min_score : typing.Optional[float]
            Minimum similarity score (0-1).

        page_size : typing.Optional[int]

        cursor : typing.Optional[str]
            Opaque cursor from a previous page.next_cursor.

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        V3ListEnvelopePackage
            Successful Response

        Examples
        --------
        from turquoisehealth-api import TurquoiseHealth

        client = TurquoiseHealth(token="YOUR_TOKEN", base_url="https://yourhost.com/path/to/api", )
        client.consumer_pricing.v3list_packages()
        """
        _response = self._raw_client.v3list_packages(
            name=name,
            anchor_code=anchor_code,
            provider_id=provider_id,
            network_id=network_id,
            payer_id=payer_id,
            search=search,
            min_score=min_score,
            page_size=page_size,
            cursor=cursor,
            request_options=request_options,
        )
        return _response.data

    def v3get_package(self, package_id: str, *, request_options: typing.Optional[RequestOptions] = None) -> V3Package:
        """
        Fetch package details by package ID.

        Parameters
        ----------
        package_id : str
            Package identifier.

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        V3Package
            Successful Response

        Examples
        --------
        from turquoisehealth-api import TurquoiseHealth

        client = TurquoiseHealth(token="YOUR_TOKEN", base_url="https://yourhost.com/path/to/api", )
        client.consumer_pricing.v3get_package(package_id='OB002', )
        """
        _response = self._raw_client.v3get_package(package_id, request_options=request_options)
        return _response.data

    def v3list_package_line_items(
        self, package_id: str, *, request_options: typing.Optional[RequestOptions] = None
    ) -> V3ListEnvelopeLineItem:
        """
        Review a service package's composition. This includes common codes and fee types, and association rates across variations of packages for a given service.

        Parameters
        ----------
        package_id : str
            Package identifier.

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        V3ListEnvelopeLineItem
            Successful Response

        Examples
        --------
        from turquoisehealth-api import TurquoiseHealth

        client = TurquoiseHealth(token="YOUR_TOKEN", base_url="https://yourhost.com/path/to/api", )
        client.consumer_pricing.v3list_package_line_items(package_id='OB002', )
        """
        _response = self._raw_client.v3list_package_line_items(package_id, request_options=request_options)
        return _response.data

    def v3compare_prices(
        self,
        *,
        package_id: str,
        pricing: V3PricesCompareRequestPricing,
        provider_id: typing.Optional[str] = OMIT,
        location: typing.Optional[V3Location] = OMIT,
        request_options: typing.Optional[RequestOptions] = None,
    ) -> V3PriceComparison:
        """
        Return summary statistics (min, max, average, median, quartiles) over prices matching the same filters as /query, excluding sorting and pagination. Use this endpoint to compare prices across relevant criteria.
        
        Parameters
        ----------
        package_id : str
        
        pricing : V3PricesCompareRequestPricing
        
        provider_id : typing.Optional[str]
        
        location : typing.Optional[V3Location]
        
        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.
        
        Returns
        -------
        V3PriceComparison
            Successful Response
        
        Examples
        --------
        from turquoisehealth-api import TurquoiseHealth
        from turquoisehealth-api.consumer_pricing import \
            V3PricesCompareRequestPricing_Negotiated
        
        client = TurquoiseHealth(token="YOUR_TOKEN", base_url="https://yourhost.com/path/to/api", )
        client.consumer_pricing.v3compare_prices(package_id='OB002', provider_id='5756', pricing=V3PricesCompareRequestPricing_Negotiated(network_id='-3776001016975145508', ), )
        """
        _response = self._raw_client.v3compare_prices(
            package_id=package_id,
            pricing=pricing,
            provider_id=provider_id,
            location=location,
            request_options=request_options,
        )
        return _response.data

    def v3query_prices(
        self,
        *,
        package_id: str,
        pricing: V3PricesQueryRequestPricing,
        provider_id: typing.Optional[str] = OMIT,
        location: typing.Optional[V3Location] = OMIT,
        sort: typing.Optional[V3PriceSort] = OMIT,
        sort_direction: typing.Optional[V3PricesQueryRequestSortDirection] = OMIT,
        page_size: typing.Optional[int] = OMIT,
        cursor: typing.Optional[str] = OMIT,
        request_options: typing.Optional[RequestOptions] = None,
    ) -> V3ListEnvelopeProviderPackagePrice:
        """
        Return prices for valid provider, service package, and pricing arrangement (cash or negotiated) combinations.
        
        Parameters
        ----------
        package_id : str
        
        pricing : V3PricesQueryRequestPricing
        
        provider_id : typing.Optional[str]
        
        location : typing.Optional[V3Location]
        
        sort : typing.Optional[V3PriceSort]
            `total` (default) or `distance` (requires a near/zip location).
        
        sort_direction : typing.Optional[V3PricesQueryRequestSortDirection]
            Sort order. Defaults to ascending (lowest total / nearest first).
        
        page_size : typing.Optional[int]
        
        cursor : typing.Optional[str]
        
        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.
        
        Returns
        -------
        V3ListEnvelopeProviderPackagePrice
            Successful Response
        
        Examples
        --------
        from turquoisehealth-api import TurquoiseHealth
        from turquoisehealth-api.consumer_pricing import \
            V3PricesQueryRequestPricing_Negotiated
        
        client = TurquoiseHealth(token="YOUR_TOKEN", base_url="https://yourhost.com/path/to/api", )
        client.consumer_pricing.v3query_prices(package_id='OB002', provider_id='5756', pricing=V3PricesQueryRequestPricing_Negotiated(network_id='-3776001016975145508', ), )
        """
        _response = self._raw_client.v3query_prices(
            package_id=package_id,
            pricing=pricing,
            provider_id=provider_id,
            location=location,
            sort=sort,
            sort_direction=sort_direction,
            page_size=page_size,
            cursor=cursor,
            request_options=request_options,
        )
        return _response.data

    def v3get_price(
        self,
        price_id: str,
        *,
        expand: typing.Optional[typing.Sequence[V3PriceExpand]] = None,
        request_options: typing.Optional[RequestOptions] = None,
    ) -> V3ProviderPackagePrice:
        """
        Fetch a single price by its unique price ID. Expand line items to review the priced package composition.

        Parameters
        ----------
        price_id : str
            Price identifier.

        expand : typing.Optional[typing.Sequence[V3PriceExpand]]
            Relations to inline. Repeat the param to request several.

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        V3ProviderPackagePrice
            Successful Response

        Examples
        --------
        from turquoisehealth-api import TurquoiseHealth

        client = TurquoiseHealth(token="YOUR_TOKEN", base_url="https://yourhost.com/path/to/api", )
        client.consumer_pricing.v3get_price(price_id='prc_5756.OB002.-3776001016975145508', )
        """
        _response = self._raw_client.v3get_price(price_id, expand=expand, request_options=request_options)
        return _response.data


class AsyncConsumerPricingClient:
    def __init__(self, *, client_wrapper: AsyncClientWrapper):
        self._raw_client = AsyncRawConsumerPricingClient(client_wrapper=client_wrapper)

    @property
    def with_raw_response(self) -> AsyncRawConsumerPricingClient:
        """
        Retrieves a raw implementation of this client that returns raw responses.

        Returns
        -------
        AsyncRawConsumerPricingClient
        """
        return self._raw_client

    async def v3list_providers(
        self,
        *,
        name: typing.Optional[str] = None,
        npi: typing.Optional[str] = None,
        type: typing.Optional[str] = None,
        package_id: typing.Optional[str] = None,
        network_id: typing.Optional[str] = None,
        payer_id: typing.Optional[str] = None,
        search: typing.Optional[str] = None,
        min_score: typing.Optional[float] = None,
        page_size: typing.Optional[int] = None,
        cursor: typing.Optional[str] = None,
        location_near_lat: typing.Optional[float] = None,
        location_near_lng: typing.Optional[float] = None,
        location_near_radius_m: typing.Optional[int] = None,
        location_within_state: typing.Optional[str] = None,
        location_within_cbsa: typing.Optional[str] = None,
        location_within_zip_codes: typing.Optional[str] = None,
        location_zip: typing.Optional[str] = None,
        request_options: typing.Optional[RequestOptions] = None,
    ) -> V3ListEnvelopeProvider:
        """
        Retrieve a list of providers, filtered over a search by name, NPI, provider type, or location. Additionally, filter to a list of providers with Turquoise price estimates available by a selected payer, network, or package. Results reflect provider, payer, and package combinations that Turquoise has priced services for; the list may not be comprehensive of all contacted payer networks or services that are available.

        Parameters
        ----------
        name : typing.Optional[str]
            Case-insensitive substring match on provider name.

        npi : typing.Optional[str]
            Exact NPI match.

        type : typing.Optional[str]
            Provider type as reported in the dataset (exact match).

        package_id : typing.Optional[str]
            Providers with at least one price for this package.

        network_id : typing.Optional[str]
            Providers with at least one price under this network (combined with package_id/payer_id, the same price row must match).

        payer_id : typing.Optional[str]
            Providers priced under any of this payer's networks (combined with other relationship filters, the same price row must match).

        search : typing.Optional[str]
            Semantic search over provider names. Composes with the other filters and a near/zip location; returns a single relevance-ordered page. 503 search_unavailable until the provider embedding index is populated.

        min_score : typing.Optional[float]
            Minimum similarity score (0-1).

        page_size : typing.Optional[int]

        cursor : typing.Optional[str]
            Opaque cursor from a previous page.next_cursor.

        location_near_lat : typing.Optional[float]

        location_near_lng : typing.Optional[float]

        location_near_radius_m : typing.Optional[int]

        location_within_state : typing.Optional[str]

        location_within_cbsa : typing.Optional[str]

        location_within_zip_codes : typing.Optional[str]
            Comma-separated ZIP codes (exact match, any-of).

        location_zip : typing.Optional[str]
            Resolves the ZIP to its centroid, then runs `near` with the default radius.

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        V3ListEnvelopeProvider
            Successful Response

        Examples
        --------
        import asyncio

        from turquoisehealth-api import AsyncTurquoiseHealth

        client = AsyncTurquoiseHealth(token="YOUR_TOKEN", base_url="https://yourhost.com/path/to/api", )
        async def main() -> None:
            await client.consumer_pricing.v3list_providers()
        asyncio.run(main())
        """
        _response = await self._raw_client.v3list_providers(
            name=name,
            npi=npi,
            type=type,
            package_id=package_id,
            network_id=network_id,
            payer_id=payer_id,
            search=search,
            min_score=min_score,
            page_size=page_size,
            cursor=cursor,
            location_near_lat=location_near_lat,
            location_near_lng=location_near_lng,
            location_near_radius_m=location_near_radius_m,
            location_within_state=location_within_state,
            location_within_cbsa=location_within_cbsa,
            location_within_zip_codes=location_within_zip_codes,
            location_zip=location_zip,
            request_options=request_options,
        )
        return _response.data

    async def v3get_provider_types(
        self, *, request_options: typing.Optional[RequestOptions] = None
    ) -> typing.List[str]:
        """
        Fetch provider types. Results return valid inputs to filter by provider types across the API.

        Parameters
        ----------
        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        typing.List[str]
            Successful Response

        Examples
        --------
        import asyncio

        from turquoisehealth-api import AsyncTurquoiseHealth

        client = AsyncTurquoiseHealth(token="YOUR_TOKEN", base_url="https://yourhost.com/path/to/api", )
        async def main() -> None:
            await client.consumer_pricing.v3get_provider_types()
        asyncio.run(main())
        """
        _response = await self._raw_client.v3get_provider_types(request_options=request_options)
        return _response.data

    async def v3get_provider(
        self, provider_id: str, *, request_options: typing.Optional[RequestOptions] = None
    ) -> V3Provider:
        """
        Fetch details for a single provider by provider ID.

        Parameters
        ----------
        provider_id : str
            Provider identifier.

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        V3Provider
            Successful Response

        Examples
        --------
        import asyncio

        from turquoisehealth-api import AsyncTurquoiseHealth

        client = AsyncTurquoiseHealth(token="YOUR_TOKEN", base_url="https://yourhost.com/path/to/api", )
        async def main() -> None:
            await client.consumer_pricing.v3get_provider(provider_id='5756', )
        asyncio.run(main())
        """
        _response = await self._raw_client.v3get_provider(provider_id, request_options=request_options)
        return _response.data

    async def v3list_payers(
        self,
        *,
        name: typing.Optional[str] = None,
        provider_id: typing.Optional[str] = None,
        package_id: typing.Optional[str] = None,
        page_size: typing.Optional[int] = None,
        cursor: typing.Optional[str] = None,
        location_near_lat: typing.Optional[float] = None,
        location_near_lng: typing.Optional[float] = None,
        location_near_radius_m: typing.Optional[int] = None,
        location_within_state: typing.Optional[str] = None,
        location_within_cbsa: typing.Optional[str] = None,
        location_within_zip_codes: typing.Optional[str] = None,
        location_zip: typing.Optional[str] = None,
        request_options: typing.Optional[RequestOptions] = None,
    ) -> V3ListEnvelopePayer:
        """
        Retrieve a list of payers, filtered over a search by name, location for care, or specific providers and services priced in the Turquoise data. Location scopes to payers with at least one price at an in-area provider. Results reflect provider, payer, and package combinations that Turquoise has priced services for; the list may not be comprehensive of all contracted providers or services that are available.

        Parameters
        ----------
        name : typing.Optional[str]
            Case-insensitive substring match on payer name.

        provider_id : typing.Optional[str]
            Payers with at least one price at this provider.

        package_id : typing.Optional[str]
            Payers with at least one price for this package.

        page_size : typing.Optional[int]

        cursor : typing.Optional[str]
            Opaque cursor from a previous page.next_cursor.

        location_near_lat : typing.Optional[float]

        location_near_lng : typing.Optional[float]

        location_near_radius_m : typing.Optional[int]

        location_within_state : typing.Optional[str]

        location_within_cbsa : typing.Optional[str]

        location_within_zip_codes : typing.Optional[str]
            Comma-separated ZIP codes (exact match, any-of).

        location_zip : typing.Optional[str]
            Resolves the ZIP to its centroid, then runs `near` with the default radius.

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        V3ListEnvelopePayer
            Successful Response

        Examples
        --------
        import asyncio

        from turquoisehealth-api import AsyncTurquoiseHealth

        client = AsyncTurquoiseHealth(token="YOUR_TOKEN", base_url="https://yourhost.com/path/to/api", )
        async def main() -> None:
            await client.consumer_pricing.v3list_payers()
        asyncio.run(main())
        """
        _response = await self._raw_client.v3list_payers(
            name=name,
            provider_id=provider_id,
            package_id=package_id,
            page_size=page_size,
            cursor=cursor,
            location_near_lat=location_near_lat,
            location_near_lng=location_near_lng,
            location_near_radius_m=location_near_radius_m,
            location_within_state=location_within_state,
            location_within_cbsa=location_within_cbsa,
            location_within_zip_codes=location_within_zip_codes,
            location_zip=location_zip,
            request_options=request_options,
        )
        return _response.data

    async def v3get_payer(self, payer_id: str, *, request_options: typing.Optional[RequestOptions] = None) -> V3Payer:
        """
        Fetch details about a single payer by payer ID.

        Parameters
        ----------
        payer_id : str
            Payer identifier.

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        V3Payer
            Successful Response

        Examples
        --------
        import asyncio

        from turquoisehealth-api import AsyncTurquoiseHealth

        client = AsyncTurquoiseHealth(token="YOUR_TOKEN", base_url="https://yourhost.com/path/to/api", )
        async def main() -> None:
            await client.consumer_pricing.v3get_payer(payer_id='76', )
        asyncio.run(main())
        """
        _response = await self._raw_client.v3get_payer(payer_id, request_options=request_options)
        return _response.data

    async def v3list_networks(
        self,
        *,
        name: typing.Optional[str] = None,
        payer_id: typing.Optional[str] = None,
        provider_id: typing.Optional[str] = None,
        package_id: typing.Optional[str] = None,
        search: typing.Optional[str] = None,
        min_score: typing.Optional[float] = None,
        page_size: typing.Optional[int] = None,
        cursor: typing.Optional[str] = None,
        location_near_lat: typing.Optional[float] = None,
        location_near_lng: typing.Optional[float] = None,
        location_near_radius_m: typing.Optional[int] = None,
        location_within_state: typing.Optional[str] = None,
        location_within_cbsa: typing.Optional[str] = None,
        location_within_zip_codes: typing.Optional[str] = None,
        location_zip: typing.Optional[str] = None,
        request_options: typing.Optional[RequestOptions] = None,
    ) -> V3ListEnvelopeNetwork:
        """
        Retrieve a list of payer networks, filtered over a search by name, payer organization (e.g., Cigna), location for care, or specific providers and services priced in the Turquoise data. Location scopes to payer networks with at least one price at an in-area provider. Results reflect provider, payer network, and package combinations that Turquoise has priced services for; the list may not be comprehensive of all contracted providers or services that are available.

        Parameters
        ----------
        name : typing.Optional[str]
            Case-insensitive substring match on network or payer name.

        payer_id : typing.Optional[str]
            Exact payer id match.

        provider_id : typing.Optional[str]
            Networks with at least one price at this provider.

        package_id : typing.Optional[str]
            Networks with at least one price for this package.

        search : typing.Optional[str]
            Semantic search over network and payer names. Composes with the other filters; returns a single relevance-ordered page (no cursor).

        min_score : typing.Optional[float]
            Minimum similarity score (0-1).

        page_size : typing.Optional[int]

        cursor : typing.Optional[str]
            Opaque cursor from a previous page.next_cursor.

        location_near_lat : typing.Optional[float]

        location_near_lng : typing.Optional[float]

        location_near_radius_m : typing.Optional[int]

        location_within_state : typing.Optional[str]

        location_within_cbsa : typing.Optional[str]

        location_within_zip_codes : typing.Optional[str]
            Comma-separated ZIP codes (exact match, any-of).

        location_zip : typing.Optional[str]
            Resolves the ZIP to its centroid, then runs `near` with the default radius.

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        V3ListEnvelopeNetwork
            Successful Response

        Examples
        --------
        import asyncio

        from turquoisehealth-api import AsyncTurquoiseHealth

        client = AsyncTurquoiseHealth(token="YOUR_TOKEN", base_url="https://yourhost.com/path/to/api", )
        async def main() -> None:
            await client.consumer_pricing.v3list_networks()
        asyncio.run(main())
        """
        _response = await self._raw_client.v3list_networks(
            name=name,
            payer_id=payer_id,
            provider_id=provider_id,
            package_id=package_id,
            search=search,
            min_score=min_score,
            page_size=page_size,
            cursor=cursor,
            location_near_lat=location_near_lat,
            location_near_lng=location_near_lng,
            location_near_radius_m=location_near_radius_m,
            location_within_state=location_within_state,
            location_within_cbsa=location_within_cbsa,
            location_within_zip_codes=location_within_zip_codes,
            location_zip=location_zip,
            request_options=request_options,
        )
        return _response.data

    async def v3get_network(
        self, network_id: str, *, request_options: typing.Optional[RequestOptions] = None
    ) -> V3Network:
        """
        Fetch details about a single network by network ID.

        Parameters
        ----------
        network_id : str
            Network identifier (string-wrapped 64-bit integer).

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        V3Network
            Successful Response

        Examples
        --------
        import asyncio

        from turquoisehealth-api import AsyncTurquoiseHealth

        client = AsyncTurquoiseHealth(token="YOUR_TOKEN", base_url="https://yourhost.com/path/to/api", )
        async def main() -> None:
            await client.consumer_pricing.v3get_network(network_id='-3776001016975145508', )
        asyncio.run(main())
        """
        _response = await self._raw_client.v3get_network(network_id, request_options=request_options)
        return _response.data

    async def v3list_packages(
        self,
        *,
        name: typing.Optional[str] = None,
        anchor_code: typing.Optional[str] = None,
        provider_id: typing.Optional[str] = None,
        network_id: typing.Optional[str] = None,
        payer_id: typing.Optional[str] = None,
        search: typing.Optional[str] = None,
        min_score: typing.Optional[float] = None,
        page_size: typing.Optional[int] = None,
        cursor: typing.Optional[str] = None,
        request_options: typing.Optional[RequestOptions] = None,
    ) -> V3ListEnvelopePackage:
        """
        Return a list of service packages, filtered over name or anchor code. Additionally, filter to a list of packages with Turquoise price estimates available by a selected payer, network, or provider. Results reflect provider, payer, and package combinations that Turquoise has priced services for; the list may not be comprehensive of all payer networks or providers that support this service. When multiple relationship filters are combined, they must be satisfied by the same price row, so results are always fulfillable via GET /v3/prices.

        Parameters
        ----------
        name : typing.Optional[str]
            Case-insensitive substring match on package name.

        anchor_code : typing.Optional[str]
            Billing code lookup; matches against anchor_codes[].code (package base codes only). Returns every package anchored by the code — exactly one in the current catalog, but uniqueness is not contractual (an anchor's full upstream identity includes revenue code and billing class, which this API collapses).

        provider_id : typing.Optional[str]
            Packages priced at this provider.

        network_id : typing.Optional[str]
            Packages with at least one price under this network (combined with provider_id/payer_id, the same price row must match).

        payer_id : typing.Optional[str]
            Packages priced under any of this payer's networks (combined with other relationship filters, the same price row must match).

        search : typing.Optional[str]
            Semantic search over package name and description. Composes with the other filters; returns a single relevance-ordered page (no cursor). 503 search_unavailable when the embedding index is not populated.

        min_score : typing.Optional[float]
            Minimum similarity score (0-1).

        page_size : typing.Optional[int]

        cursor : typing.Optional[str]
            Opaque cursor from a previous page.next_cursor.

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        V3ListEnvelopePackage
            Successful Response

        Examples
        --------
        import asyncio

        from turquoisehealth-api import AsyncTurquoiseHealth

        client = AsyncTurquoiseHealth(token="YOUR_TOKEN", base_url="https://yourhost.com/path/to/api", )
        async def main() -> None:
            await client.consumer_pricing.v3list_packages()
        asyncio.run(main())
        """
        _response = await self._raw_client.v3list_packages(
            name=name,
            anchor_code=anchor_code,
            provider_id=provider_id,
            network_id=network_id,
            payer_id=payer_id,
            search=search,
            min_score=min_score,
            page_size=page_size,
            cursor=cursor,
            request_options=request_options,
        )
        return _response.data

    async def v3get_package(
        self, package_id: str, *, request_options: typing.Optional[RequestOptions] = None
    ) -> V3Package:
        """
        Fetch package details by package ID.

        Parameters
        ----------
        package_id : str
            Package identifier.

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        V3Package
            Successful Response

        Examples
        --------
        import asyncio

        from turquoisehealth-api import AsyncTurquoiseHealth

        client = AsyncTurquoiseHealth(token="YOUR_TOKEN", base_url="https://yourhost.com/path/to/api", )
        async def main() -> None:
            await client.consumer_pricing.v3get_package(package_id='OB002', )
        asyncio.run(main())
        """
        _response = await self._raw_client.v3get_package(package_id, request_options=request_options)
        return _response.data

    async def v3list_package_line_items(
        self, package_id: str, *, request_options: typing.Optional[RequestOptions] = None
    ) -> V3ListEnvelopeLineItem:
        """
        Review a service package's composition. This includes common codes and fee types, and association rates across variations of packages for a given service.

        Parameters
        ----------
        package_id : str
            Package identifier.

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        V3ListEnvelopeLineItem
            Successful Response

        Examples
        --------
        import asyncio

        from turquoisehealth-api import AsyncTurquoiseHealth

        client = AsyncTurquoiseHealth(token="YOUR_TOKEN", base_url="https://yourhost.com/path/to/api", )
        async def main() -> None:
            await client.consumer_pricing.v3list_package_line_items(package_id='OB002', )
        asyncio.run(main())
        """
        _response = await self._raw_client.v3list_package_line_items(package_id, request_options=request_options)
        return _response.data

    async def v3compare_prices(
        self,
        *,
        package_id: str,
        pricing: V3PricesCompareRequestPricing,
        provider_id: typing.Optional[str] = OMIT,
        location: typing.Optional[V3Location] = OMIT,
        request_options: typing.Optional[RequestOptions] = None,
    ) -> V3PriceComparison:
        """
        Return summary statistics (min, max, average, median, quartiles) over prices matching the same filters as /query, excluding sorting and pagination. Use this endpoint to compare prices across relevant criteria.
        
        Parameters
        ----------
        package_id : str
        
        pricing : V3PricesCompareRequestPricing
        
        provider_id : typing.Optional[str]
        
        location : typing.Optional[V3Location]
        
        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.
        
        Returns
        -------
        V3PriceComparison
            Successful Response
        
        Examples
        --------
        import asyncio
        
        from turquoisehealth-api import AsyncTurquoiseHealth
        from turquoisehealth-api.consumer_pricing import \
            V3PricesCompareRequestPricing_Negotiated
        
        client = AsyncTurquoiseHealth(token="YOUR_TOKEN", base_url="https://yourhost.com/path/to/api", )
        async def main() -> None:
            await client.consumer_pricing.v3compare_prices(package_id='OB002', provider_id='5756', pricing=V3PricesCompareRequestPricing_Negotiated(network_id='-3776001016975145508', ), )
        asyncio.run(main())
        """
        _response = await self._raw_client.v3compare_prices(
            package_id=package_id,
            pricing=pricing,
            provider_id=provider_id,
            location=location,
            request_options=request_options,
        )
        return _response.data

    async def v3query_prices(
        self,
        *,
        package_id: str,
        pricing: V3PricesQueryRequestPricing,
        provider_id: typing.Optional[str] = OMIT,
        location: typing.Optional[V3Location] = OMIT,
        sort: typing.Optional[V3PriceSort] = OMIT,
        sort_direction: typing.Optional[V3PricesQueryRequestSortDirection] = OMIT,
        page_size: typing.Optional[int] = OMIT,
        cursor: typing.Optional[str] = OMIT,
        request_options: typing.Optional[RequestOptions] = None,
    ) -> V3ListEnvelopeProviderPackagePrice:
        """
        Return prices for valid provider, service package, and pricing arrangement (cash or negotiated) combinations.
        
        Parameters
        ----------
        package_id : str
        
        pricing : V3PricesQueryRequestPricing
        
        provider_id : typing.Optional[str]
        
        location : typing.Optional[V3Location]
        
        sort : typing.Optional[V3PriceSort]
            `total` (default) or `distance` (requires a near/zip location).
        
        sort_direction : typing.Optional[V3PricesQueryRequestSortDirection]
            Sort order. Defaults to ascending (lowest total / nearest first).
        
        page_size : typing.Optional[int]
        
        cursor : typing.Optional[str]
        
        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.
        
        Returns
        -------
        V3ListEnvelopeProviderPackagePrice
            Successful Response
        
        Examples
        --------
        import asyncio
        
        from turquoisehealth-api import AsyncTurquoiseHealth
        from turquoisehealth-api.consumer_pricing import \
            V3PricesQueryRequestPricing_Negotiated
        
        client = AsyncTurquoiseHealth(token="YOUR_TOKEN", base_url="https://yourhost.com/path/to/api", )
        async def main() -> None:
            await client.consumer_pricing.v3query_prices(package_id='OB002', provider_id='5756', pricing=V3PricesQueryRequestPricing_Negotiated(network_id='-3776001016975145508', ), )
        asyncio.run(main())
        """
        _response = await self._raw_client.v3query_prices(
            package_id=package_id,
            pricing=pricing,
            provider_id=provider_id,
            location=location,
            sort=sort,
            sort_direction=sort_direction,
            page_size=page_size,
            cursor=cursor,
            request_options=request_options,
        )
        return _response.data

    async def v3get_price(
        self,
        price_id: str,
        *,
        expand: typing.Optional[typing.Sequence[V3PriceExpand]] = None,
        request_options: typing.Optional[RequestOptions] = None,
    ) -> V3ProviderPackagePrice:
        """
        Fetch a single price by its unique price ID. Expand line items to review the priced package composition.

        Parameters
        ----------
        price_id : str
            Price identifier.

        expand : typing.Optional[typing.Sequence[V3PriceExpand]]
            Relations to inline. Repeat the param to request several.

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        V3ProviderPackagePrice
            Successful Response

        Examples
        --------
        import asyncio

        from turquoisehealth-api import AsyncTurquoiseHealth

        client = AsyncTurquoiseHealth(token="YOUR_TOKEN", base_url="https://yourhost.com/path/to/api", )
        async def main() -> None:
            await client.consumer_pricing.v3get_price(price_id='prc_5756.OB002.-3776001016975145508', )
        asyncio.run(main())
        """
        _response = await self._raw_client.v3get_price(price_id, expand=expand, request_options=request_options)
        return _response.data
