# This file was auto-generated by Fern from our API Definition.

# isort: skip_file

import typing
from importlib import import_module

if typing.TYPE_CHECKING:
    from .consumer_pricing_v2error_code import ConsumerPricingV2ErrorCode
    from .v3billing_code import V3BillingCode
    from .v3comparison_stats import V3ComparisonStats
    from .v3consumer_pricing_v2error_code import V3ConsumerPricingV2ErrorCode
    from .v3entity_ref import V3EntityRef
    from .v3error_code import V3ErrorCode
    from .v3error_payload import V3ErrorPayload
    from .v3error_response import V3ErrorResponse
    from .v3line_item import V3LineItem
    from .v3list_envelope_line_item import V3ListEnvelopeLineItem
    from .v3list_envelope_line_item_object import V3ListEnvelopeLineItemObject
    from .v3list_envelope_network import V3ListEnvelopeNetwork
    from .v3list_envelope_network_object import V3ListEnvelopeNetworkObject
    from .v3list_envelope_package import V3ListEnvelopePackage
    from .v3list_envelope_package_object import V3ListEnvelopePackageObject
    from .v3list_envelope_payer import V3ListEnvelopePayer
    from .v3list_envelope_payer_object import V3ListEnvelopePayerObject
    from .v3list_envelope_provider import V3ListEnvelopeProvider
    from .v3list_envelope_provider_object import V3ListEnvelopeProviderObject
    from .v3list_envelope_provider_package_price import V3ListEnvelopeProviderPackagePrice
    from .v3list_envelope_provider_package_price_object import V3ListEnvelopeProviderPackagePriceObject
    from .v3location import V3Location
    from .v3location_near import V3LocationNear
    from .v3location_within import V3LocationWithin
    from .v3match_context import V3MatchContext
    from .v3money import V3Money
    from .v3network import V3Network
    from .v3network_object import V3NetworkObject
    from .v3no_data_reason import V3NoDataReason
    from .v3package import V3Package
    from .v3package_object import V3PackageObject
    from .v3package_type import V3PackageType
    from .v3page_meta import V3PageMeta
    from .v3payer import V3Payer
    from .v3payer_object import V3PayerObject
    from .v3price_comparison import V3PriceComparison
    from .v3price_comparison_object import V3PriceComparisonObject
    from .v3price_expand import V3PriceExpand
    from .v3price_sort import V3PriceSort
    from .v3pricing_cash import V3PricingCash
    from .v3pricing_negotiated import V3PricingNegotiated
    from .v3pricing_resolved import V3PricingResolved
    from .v3pricing_resolved_type import V3PricingResolvedType
    from .v3provider import V3Provider
    from .v3provider_address import V3ProviderAddress
    from .v3provider_object import V3ProviderObject
    from .v3provider_package_price import V3ProviderPackagePrice
    from .v3provider_package_price_object import V3ProviderPackagePriceObject
    from .v3response_meta import V3ResponseMeta
    from .v3search_context import V3SearchContext
_dynamic_imports: typing.Dict[str, str] = {
    "ConsumerPricingV2ErrorCode": ".consumer_pricing_v2error_code",
    "V3BillingCode": ".v3billing_code",
    "V3ComparisonStats": ".v3comparison_stats",
    "V3ConsumerPricingV2ErrorCode": ".v3consumer_pricing_v2error_code",
    "V3EntityRef": ".v3entity_ref",
    "V3ErrorCode": ".v3error_code",
    "V3ErrorPayload": ".v3error_payload",
    "V3ErrorResponse": ".v3error_response",
    "V3LineItem": ".v3line_item",
    "V3ListEnvelopeLineItem": ".v3list_envelope_line_item",
    "V3ListEnvelopeLineItemObject": ".v3list_envelope_line_item_object",
    "V3ListEnvelopeNetwork": ".v3list_envelope_network",
    "V3ListEnvelopeNetworkObject": ".v3list_envelope_network_object",
    "V3ListEnvelopePackage": ".v3list_envelope_package",
    "V3ListEnvelopePackageObject": ".v3list_envelope_package_object",
    "V3ListEnvelopePayer": ".v3list_envelope_payer",
    "V3ListEnvelopePayerObject": ".v3list_envelope_payer_object",
    "V3ListEnvelopeProvider": ".v3list_envelope_provider",
    "V3ListEnvelopeProviderObject": ".v3list_envelope_provider_object",
    "V3ListEnvelopeProviderPackagePrice": ".v3list_envelope_provider_package_price",
    "V3ListEnvelopeProviderPackagePriceObject": ".v3list_envelope_provider_package_price_object",
    "V3Location": ".v3location",
    "V3LocationNear": ".v3location_near",
    "V3LocationWithin": ".v3location_within",
    "V3MatchContext": ".v3match_context",
    "V3Money": ".v3money",
    "V3Network": ".v3network",
    "V3NetworkObject": ".v3network_object",
    "V3NoDataReason": ".v3no_data_reason",
    "V3Package": ".v3package",
    "V3PackageObject": ".v3package_object",
    "V3PackageType": ".v3package_type",
    "V3PageMeta": ".v3page_meta",
    "V3Payer": ".v3payer",
    "V3PayerObject": ".v3payer_object",
    "V3PriceComparison": ".v3price_comparison",
    "V3PriceComparisonObject": ".v3price_comparison_object",
    "V3PriceExpand": ".v3price_expand",
    "V3PriceSort": ".v3price_sort",
    "V3PricingCash": ".v3pricing_cash",
    "V3PricingNegotiated": ".v3pricing_negotiated",
    "V3PricingResolved": ".v3pricing_resolved",
    "V3PricingResolvedType": ".v3pricing_resolved_type",
    "V3Provider": ".v3provider",
    "V3ProviderAddress": ".v3provider_address",
    "V3ProviderObject": ".v3provider_object",
    "V3ProviderPackagePrice": ".v3provider_package_price",
    "V3ProviderPackagePriceObject": ".v3provider_package_price_object",
    "V3ResponseMeta": ".v3response_meta",
    "V3SearchContext": ".v3search_context",
}


def __getattr__(attr_name: str) -> typing.Any:
    module_name = _dynamic_imports.get(attr_name)
    if module_name is None:
        raise AttributeError(f"No {attr_name} found in _dynamic_imports for module name -> {__name__}")
    try:
        module = import_module(module_name, __package__)
        if module_name == f".{attr_name}":
            return module
        else:
            return getattr(module, attr_name)
    except ImportError as e:
        raise ImportError(f"Failed to import {attr_name} from {module_name}: {e}") from e
    except AttributeError as e:
        raise AttributeError(f"Failed to get {attr_name} from {module_name}: {e}") from e


def __dir__():
    lazy_attrs = list(_dynamic_imports.keys())
    return sorted(lazy_attrs)


__all__ = [
    "ConsumerPricingV2ErrorCode",
    "V3BillingCode",
    "V3ComparisonStats",
    "V3ConsumerPricingV2ErrorCode",
    "V3EntityRef",
    "V3ErrorCode",
    "V3ErrorPayload",
    "V3ErrorResponse",
    "V3LineItem",
    "V3ListEnvelopeLineItem",
    "V3ListEnvelopeLineItemObject",
    "V3ListEnvelopeNetwork",
    "V3ListEnvelopeNetworkObject",
    "V3ListEnvelopePackage",
    "V3ListEnvelopePackageObject",
    "V3ListEnvelopePayer",
    "V3ListEnvelopePayerObject",
    "V3ListEnvelopeProvider",
    "V3ListEnvelopeProviderObject",
    "V3ListEnvelopeProviderPackagePrice",
    "V3ListEnvelopeProviderPackagePriceObject",
    "V3Location",
    "V3LocationNear",
    "V3LocationWithin",
    "V3MatchContext",
    "V3Money",
    "V3Network",
    "V3NetworkObject",
    "V3NoDataReason",
    "V3Package",
    "V3PackageObject",
    "V3PackageType",
    "V3PageMeta",
    "V3Payer",
    "V3PayerObject",
    "V3PriceComparison",
    "V3PriceComparisonObject",
    "V3PriceExpand",
    "V3PriceSort",
    "V3PricingCash",
    "V3PricingNegotiated",
    "V3PricingResolved",
    "V3PricingResolvedType",
    "V3Provider",
    "V3ProviderAddress",
    "V3ProviderObject",
    "V3ProviderPackagePrice",
    "V3ProviderPackagePriceObject",
    "V3ResponseMeta",
    "V3SearchContext",
]
