# This file was auto-generated by Fern from our API Definition.

import typing

import pydantic
from ..core.pydantic_utilities import IS_PYDANTIC_V2, UniversalBaseModel
from .consumer_site_rate_compare_location_near_lat import ConsumerSiteRateCompareLocationNearLat
from .consumer_site_rate_compare_location_near_lng import ConsumerSiteRateCompareLocationNearLng


class ConsumerSiteRateCompareLocation(UniversalBaseModel):
    """
    Structured location for POST bodies. Exactly zero or one mode permitted.  Validated by the service layer (location.py shares LocationQuery for GET query params; this is the body equivalent).
    """

    near_lat: typing.Optional[ConsumerSiteRateCompareLocationNearLat] = None
    near_lng: typing.Optional[ConsumerSiteRateCompareLocationNearLng] = None
    near_radius_m: typing.Optional[int] = None
    within_state: typing.Optional[str] = None
    within_cbsa_name: typing.Optional[str] = None
    within_zip_codes: typing.Optional[typing.List[str]] = None
    zip_anchor: typing.Optional[str] = None

    if IS_PYDANTIC_V2:
        model_config: typing.ClassVar[pydantic.ConfigDict] = pydantic.ConfigDict(extra="allow", frozen=True)  # type: ignore # Pydantic v2
    else:

        class Config:
            frozen = True
            smart_union = True
            extra = pydantic.Extra.allow
