# This file was auto-generated by Fern from our API Definition.

import datetime as dt
import typing

import pydantic
from ..core.pydantic_utilities import IS_PYDANTIC_V2, UniversalBaseModel
from .consumer_site_rate_compare_location import ConsumerSiteRateCompareLocation


class ConsumerSiteListPricesInputV2(UniversalBaseModel):
    """
    Inbound payload for the list-prices endpoint.

    Extends eligibility fields with optional search parameters forwarded to the
    personalized-estimates API.
    """

    first_name: str
    last_name: str
    date_of_birth: dt.date
    member_id: str
    consent_attested: str
    network_id: int
    ssp_id: typing.Optional[str] = None
    provider_id: typing.Optional[str] = None
    location: typing.Optional[ConsumerSiteRateCompareLocation] = None
    page_size: typing.Optional[int] = None
    cursor: typing.Optional[str] = None

    if IS_PYDANTIC_V2:
        model_config: typing.ClassVar[pydantic.ConfigDict] = pydantic.ConfigDict(extra="allow", frozen=True)  # type: ignore # Pydantic v2
    else:

        class Config:
            frozen = True
            smart_union = True
            extra = pydantic.Extra.allow
