# This file was auto-generated by Fern from our API Definition.

import typing

import pydantic
import typing_extensions
from ..core.pydantic_utilities import IS_PYDANTIC_V2, UniversalBaseModel
from ..core.serialization import FieldMetadata


class ConsumerSiteRateComparison(UniversalBaseModel):
    """
    Bounded statistic bundle. No envelope per the ticket.
    """

    count: int = pydantic.Field()
    """
    Number of rate rows the statistics were computed over.
    """

    currency: typing.Optional[str] = None
    min_amount: typing.Optional[str] = None
    min_amount_cents: typing.Optional[int] = None
    max_amount: typing.Optional[str] = None
    max_amount_cents: typing.Optional[int] = None
    avg_amount: typing.Optional[str] = None
    avg_amount_cents: typing.Optional[int] = None
    median_amount: typing.Optional[str] = None
    median_amount_cents: typing.Optional[int] = None
    q1amount: typing_extensions.Annotated[typing.Optional[str], FieldMetadata(alias="q1_amount")] = None
    q1amount_cents: typing_extensions.Annotated[typing.Optional[int], FieldMetadata(alias="q1_amount_cents")] = None
    q3amount: typing_extensions.Annotated[typing.Optional[str], FieldMetadata(alias="q3_amount")] = None
    q3amount_cents: typing_extensions.Annotated[typing.Optional[int], FieldMetadata(alias="q3_amount_cents")] = None

    if IS_PYDANTIC_V2:
        model_config: typing.ClassVar[pydantic.ConfigDict] = pydantic.ConfigDict(extra="allow", frozen=True)  # type: ignore # Pydantic v2
    else:

        class Config:
            frozen = True
            smart_union = True
            extra = pydantic.Extra.allow
