# This file was auto-generated by Fern from our API Definition.

import typing

import pydantic
from ..core.pydantic_utilities import IS_PYDANTIC_V2, UniversalBaseModel
from .consumer_site_money import ConsumerSiteMoney


class ConsumerSiteComparisonStats(UniversalBaseModel):
    """
    ComparisonStats
    """

    min: ConsumerSiteMoney
    max: ConsumerSiteMoney
    avg: ConsumerSiteMoney
    median: ConsumerSiteMoney
    q1: ConsumerSiteMoney
    q3: ConsumerSiteMoney

    if IS_PYDANTIC_V2:
        model_config: typing.ClassVar[pydantic.ConfigDict] = pydantic.ConfigDict(extra="allow", frozen=True)  # type: ignore # Pydantic v2
    else:

        class Config:
            frozen = True
            smart_union = True
            extra = pydantic.Extra.allow
