# This file was auto-generated by Fern from our API Definition.

import datetime as dt
import typing

import pydantic
from ..core.pydantic_utilities import IS_PYDANTIC_V2, UniversalBaseModel
from .consumer_site_rate_compare_location import ConsumerSiteRateCompareLocation


class ConsumerSiteProviderBreakdownInputV2(UniversalBaseModel):
    """
    Inbound payload for the provider-breakdown endpoint.

    Extends eligibility fields with required provider and service identifiers.
    """

    first_name: str
    last_name: str
    date_of_birth: dt.date
    member_id: str
    consent_attested: str
    network_id: int
    provider_id: str
    ssp_id: str
    location: typing.Optional[ConsumerSiteRateCompareLocation] = None

    if IS_PYDANTIC_V2:
        model_config: typing.ClassVar[pydantic.ConfigDict] = pydantic.ConfigDict(extra="allow", frozen=True)  # type: ignore # Pydantic v2
    else:

        class Config:
            frozen = True
            smart_union = True
            extra = pydantic.Extra.allow
