# This file was auto-generated by Fern from our API Definition.

import typing

import pydantic
from ..core.pydantic_utilities import IS_PYDANTIC_V2, UniversalBaseModel
from .consumer_site_personalized_estimate_error_code import ConsumerSitePersonalizedEstimateErrorCode


class ConsumerSitePersonalizedEstimateErrorPayload(UniversalBaseModel):
    """
    Details about an error returned by a v3 personalized-estimate endpoint.
    """

    code: ConsumerSitePersonalizedEstimateErrorCode = pydantic.Field()
    """
    Stable, documented error code. Switch on this in code.
    """

    message: str = pydantic.Field()
    """
    Human-readable error summary, suitable for narration to an end user.
    """

    hint: typing.Optional[str] = pydantic.Field(default=None)
    """
    Actionable suggestion for the caller, when applicable.
    """

    expected: typing.Optional[str] = pydantic.Field(default=None)
    """
    What the API expected (format, value range, etc).
    """

    received: typing.Optional[str] = pydantic.Field(default=None)
    """
    What the API actually received.
    """

    field: typing.Optional[str] = pydantic.Field(default=None)
    """
    Dot-path of the offending request field, when applicable.
    """

    if IS_PYDANTIC_V2:
        model_config: typing.ClassVar[pydantic.ConfigDict] = pydantic.ConfigDict(extra="allow", frozen=True)  # type: ignore # Pydantic v2
    else:

        class Config:
            frozen = True
            smart_union = True
            extra = pydantic.Extra.allow
