# This file was auto-generated by Fern from our API Definition.

import typing

import pydantic
from ..core.pydantic_utilities import IS_PYDANTIC_V2, UniversalBaseModel


class Coordinates(UniversalBaseModel):
    latitude: float = pydantic.Field()
    """
    Latitude for exact geo targeting
    """

    longitude: float = pydantic.Field()
    """
    Longitude for exact geo targeting
    """

    distance_in_meters: typing.Optional[int] = pydantic.Field(default=None)
    """
    Search radius in meters.
    """

    if IS_PYDANTIC_V2:
        model_config: typing.ClassVar[pydantic.ConfigDict] = pydantic.ConfigDict(extra="allow", frozen=True)  # type: ignore # Pydantic v2
    else:

        class Config:
            frozen = True
            smart_union = True
            extra = pydantic.Extra.allow
