# This file was auto-generated by Fern from our API Definition.

import typing

import pydantic
from ..core.pydantic_utilities import IS_PYDANTIC_V2, UniversalBaseModel


class EntityRef(UniversalBaseModel):
    """
    Two-field reference stub. `expand=` swaps it for the full entity.

    `name` is nullable by design: 0.8% of priced providers have no reference
    row (measured 07/2026), and the v3 rule is to emit the stub with a null
    name rather than silently dropping the priced row.
    """

    id: str = pydantic.Field()
    """
    Entity identifier. Upstream-derived from the dataset and may change as the dataset is rebuilt. Re-resolve via search rather than persisting long-term.
    """

    name: typing.Optional[str] = pydantic.Field(default=None)
    """
    Display name; null when reference data is missing.
    """

    if IS_PYDANTIC_V2:
        model_config: typing.ClassVar[pydantic.ConfigDict] = pydantic.ConfigDict(extra="allow", frozen=True)  # type: ignore # Pydantic v2
    else:

        class Config:
            frozen = True
            smart_union = True
            extra = pydantic.Extra.allow
