# This file was auto-generated by Fern from our API Definition.

import typing

import pydantic
from ..core.pydantic_utilities import IS_PYDANTIC_V2, UniversalBaseModel
from .network import Network
from .no_data_reason import NoDataReason
from .page_meta import PageMeta


class EnvelopeNetwork(UniversalBaseModel):
    items: typing.List[Network]
    page: PageMeta
    no_data_reason: typing.Optional[NoDataReason] = pydantic.Field(default=None)
    """
    Set when `items` is empty. `no_data` means no matching records exist; `permission_denied` means matching records exist but are excluded by your data permissions.
    """

    if IS_PYDANTIC_V2:
        model_config: typing.ClassVar[pydantic.ConfigDict] = pydantic.ConfigDict(extra="allow", frozen=True)  # type: ignore # Pydantic v2
    else:

        class Config:
            frozen = True
            smart_union = True
            extra = pydantic.Extra.allow
