# This file was auto-generated by Fern from our API Definition.

import typing

ErrorCode = typing.Union[
    typing.Literal[
        "INVALID_REQUEST",
        "INVALID_STATE_FORMAT",
        "INVALID_ID_FORMAT",
        "INVALID_EXPAND",
        "INSUFFICIENT_SCOPE",
        "LOCATION_REQUIRED",
        "LOCATION_AMBIGUOUS",
        "UNRESOLVABLE_LOCATION",
        "NOT_FOUND",
        "INSUFFICIENT_DATA",
        "RATE_LIMITED",
        "PERMISSION_DENIED",
        "SEARCH_UNAVAILABLE",
    ],
    typing.Any,
]
