# This file was auto-generated by Fern from our API Definition.

import typing

import pydantic
from ..core.pydantic_utilities import IS_PYDANTIC_V2, UniversalBaseModel


class MatchContext(UniversalBaseModel):
    """
    Query-relative metadata for resources with a concrete location.
    """

    score: typing.Optional[float] = pydantic.Field(default=None)
    """
    Semantic similarity (0-1).
    """

    distance_m: typing.Optional[float] = pydantic.Field(default=None)
    """
    Distance from the search anchor in meters.
    """

    if IS_PYDANTIC_V2:
        model_config: typing.ClassVar[pydantic.ConfigDict] = pydantic.ConfigDict(extra="allow", frozen=True)  # type: ignore # Pydantic v2
    else:

        class Config:
            frozen = True
            smart_union = True
            extra = pydantic.Extra.allow
