# This file was auto-generated by Fern from our API Definition.

import typing

import pydantic
from ..core.pydantic_utilities import IS_PYDANTIC_V2, UniversalBaseModel


class ProviderLocationDetails(UniversalBaseModel):
    street_address: str = pydantic.Field()
    """
    Provider street address
    """

    latitude: typing.Optional[float] = pydantic.Field(default=None)
    """
    Provider latitude
    """

    longitude: typing.Optional[float] = pydantic.Field(default=None)
    """
    Provider longitude
    """

    distance_in_meters: typing.Optional[float] = pydantic.Field(default=None)
    """
    Distance from the search location in meters
    """

    hospital_overall_rating: typing.Optional[int] = pydantic.Field(default=None)
    """
    CMS overall hospital quality rating (1-5)
    """

    if IS_PYDANTIC_V2:
        model_config: typing.ClassVar[pydantic.ConfigDict] = pydantic.ConfigDict(extra="allow", frozen=True)  # type: ignore # Pydantic v2
    else:

        class Config:
            frozen = True
            smart_union = True
            extra = pydantic.Extra.allow
