# This file was auto-generated by Fern from our API Definition.

import typing

import pydantic
from ..core.pydantic_utilities import IS_PYDANTIC_V2, UniversalBaseModel


class Provider(UniversalBaseModel):
    """
    Provider list/detail row.
    """

    id: str = pydantic.Field()
    """
    Provider identifier. Upstream-derived from the dataset and may change as the dataset is rebuilt. Do not bake into URLs, bookmarks, or persistent storage.
    """

    name: str = pydantic.Field()
    """
    Provider facility or organization name.
    """

    type: typing.Optional[str] = pydantic.Field(default=None)
    """
    Provider type (hospital, ASC, imaging center, etc).
    """

    npi: typing.Optional[str] = pydantic.Field(default=None)
    """
    National Provider Identifier.
    """

    city: str = pydantic.Field()
    """
    City the provider is located in.
    """

    state: str = pydantic.Field()
    """
    Two-letter USPS state code.
    """

    zip_code: str = pydantic.Field()
    """
    Provider ZIP code.
    """

    distance_m: typing.Optional[float] = pydantic.Field(default=None)
    """
    Distance from the search anchor in meters. Null when no `near`/`zip_anchor` location was supplied.
    """

    latitude: typing.Optional[float] = pydantic.Field(default=None)
    """
    Provider HQ latitude.
    """

    longitude: typing.Optional[float] = pydantic.Field(default=None)
    """
    Provider HQ longitude.
    """

    if IS_PYDANTIC_V2:
        model_config: typing.ClassVar[pydantic.ConfigDict] = pydantic.ConfigDict(extra="allow", frozen=True)  # type: ignore # Pydantic v2
    else:

        class Config:
            frozen = True
            smart_union = True
            extra = pydantic.Extra.allow
