# This file was auto-generated by Fern from our API Definition.

import typing

import pydantic
from ..core.pydantic_utilities import IS_PYDANTIC_V2, UniversalBaseModel
from .match_context import MatchContext
from .provider_address import ProviderAddress
from .provider_object import ProviderObject


class Provider(UniversalBaseModel):
    object: typing.Optional[ProviderObject] = None
    id: str = pydantic.Field()
    """
    Provider identifier. Upstream-derived from the dataset and may change as the dataset is rebuilt. Re-resolve via search rather than persisting long-term.
    """

    name: str = pydantic.Field()
    """
    Provider facility or organization name.
    """

    type: typing.Optional[str] = pydantic.Field(default=None)
    """
    Provider type as reported in the dataset.
    """

    npi: typing.Optional[str] = pydantic.Field(default=None)
    """
    National Provider Identifier.
    """

    address: ProviderAddress
    context: typing.Optional[MatchContext] = pydantic.Field(default=None)
    """
    Query-relative metadata (near/zip mode only).
    """

    if IS_PYDANTIC_V2:
        model_config: typing.ClassVar[pydantic.ConfigDict] = pydantic.ConfigDict(extra="allow", frozen=True)  # type: ignore # Pydantic v2
    else:

        class Config:
            frozen = True
            smart_union = True
            extra = pydantic.Extra.allow
