# This file was auto-generated by Fern from our API Definition.

import typing

import pydantic
from ..core.pydantic_utilities import IS_PYDANTIC_V2, UniversalBaseModel
from .entity_ref import EntityRef
from .line_item import LineItem
from .match_context import MatchContext
from .money import Money
from .pricing_resolved import PricingResolved
from .provider import Provider
from .provider_package_price_object import ProviderPackagePriceObject


class ProviderPackagePrice(UniversalBaseModel):
    object: typing.Optional[ProviderPackagePriceObject] = None
    id: str = pydantic.Field()
    """
    Price identifier (encodes the provider × package × pricing grain). Upstream-derived from the dataset and may change as the dataset is rebuilt. Re-resolve via search rather than persisting long-term.
    """

    provider: Provider = pydantic.Field()
    """
    Full provider entity (always inlined).
    """

    package: EntityRef = pydantic.Field()
    """
    Reference stub.
    """

    pricing: PricingResolved
    total: Money = pydantic.Field()
    """
    The package-total price at this grain.
    """

    line_items: typing.Optional[typing.List[LineItem]] = pydantic.Field(default=None)
    """
    Package composition; present when expand=line_items (detail only).
    """

    context: typing.Optional[MatchContext] = None

    if IS_PYDANTIC_V2:
        model_config: typing.ClassVar[pydantic.ConfigDict] = pydantic.ConfigDict(extra="allow", frozen=True)  # type: ignore # Pydantic v2
    else:

        class Config:
            frozen = True
            smart_union = True
            extra = pydantic.Extra.allow
