# This file was auto-generated by Fern from our API Definition.

import typing

import pydantic
from ..core.pydantic_utilities import IS_PYDANTIC_V2, UniversalBaseModel
from .care_nav_provider import CareNavProvider
from .price_detail import PriceDetail


class ProviderBreakdown(UniversalBaseModel):
    provider: CareNavProvider = pydantic.Field()
    """
    Provider details
    """

    price: typing.Optional[PriceDetail] = pydantic.Field(default=None)
    """
    Itemized price breakdown for the package
    """

    if IS_PYDANTIC_V2:
        model_config: typing.ClassVar[pydantic.ConfigDict] = pydantic.ConfigDict(extra="allow", frozen=True)  # type: ignore # Pydantic v2
    else:

        class Config:
            frozen = True
            smart_union = True
            extra = pydantic.Extra.allow
