# This file was auto-generated by Fern from our API Definition.

import typing

import pydantic
from ..core.pydantic_utilities import IS_PYDANTIC_V2, UniversalBaseModel
from .rate_breakdown_line_item import RateBreakdownLineItem
from .rate_breakdown_rate_type import RateBreakdownRateType


class RateBreakdown(UniversalBaseModel):
    rate_type: RateBreakdownRateType
    provider_id: str
    ssp_id: str
    network_id: typing.Optional[str] = pydantic.Field(default=None)
    """
    Signed 64-bit integer serialized as a string to preserve precision in JSON.
    """

    total_amount: str = pydantic.Field()
    """
    SSP-total amount from /prices.
    """

    total_amount_cents: int
    currency: typing.Optional[str] = None
    line_items: typing.List[RateBreakdownLineItem]

    if IS_PYDANTIC_V2:
        model_config: typing.ClassVar[pydantic.ConfigDict] = pydantic.ConfigDict(extra="allow", frozen=True)  # type: ignore # Pydantic v2
    else:

        class Config:
            frozen = True
            smart_union = True
            extra = pydantic.Extra.allow
