# This file was auto-generated by Fern from our API Definition.

import typing

import pydantic
from ..core.pydantic_utilities import IS_PYDANTIC_V2, UniversalBaseModel


class Ssp(UniversalBaseModel):
    """
    Standard Service Package row.

    Sparse by default. Component billing codes and pricing relationships are
    reachable via the dedicated rate endpoints.
    """

    id: str = pydantic.Field()
    """
    SSP identifier. Upstream-derived from the dataset and may change as the dataset is rebuilt. Do not bake into URLs, bookmarks, or persistent storage.
    """

    name: str = pydantic.Field()
    """
    Display name of the service package.
    """

    patient_description: typing.Optional[str] = pydantic.Field(default=None)
    """
    Patient-facing description of the service package.
    """

    if IS_PYDANTIC_V2:
        model_config: typing.ClassVar[pydantic.ConfigDict] = pydantic.ConfigDict(extra="allow", frozen=True)  # type: ignore # Pydantic v2
    else:

        class Config:
            frozen = True
            smart_union = True
            extra = pydantic.Extra.allow
