# This file was auto-generated by Fern from our API Definition.

import typing

import pydantic
from ..core.pydantic_utilities import IS_PYDANTIC_V2, UniversalBaseModel
from .care_nav_provider import CareNavProvider


class SspPrice(UniversalBaseModel):
    provider: CareNavProvider = pydantic.Field()
    """
    Provider details
    """

    package_price: float = pydantic.Field()
    """
    Total estimated package price for this provider
    """

    if IS_PYDANTIC_V2:
        model_config: typing.ClassVar[pydantic.ConfigDict] = pydantic.ConfigDict(extra="allow", frozen=True)  # type: ignore # Pydantic v2
    else:

        class Config:
            frozen = True
            smart_union = True
            extra = pydantic.Extra.allow
