# This file was auto-generated by Fern from our API Definition.

import typing

V3ErrorCode = typing.Union[
    typing.Literal[
        "invalid_request",
        "invalid_id_format",
        "insufficient_scope",
        "location_ambiguous",
        "unresolvable_location",
        "not_found",
        "invalid_expand",
        "permission_denied",
        "rate_limited",
        "search_unavailable",
        "conflicting_parameters",
    ],
    typing.Any,
]
