# This file was auto-generated by Fern from our API Definition.

import typing

import pydantic
from ..core.pydantic_utilities import IS_PYDANTIC_V2, UniversalBaseModel
from .v3list_envelope_provider_package_price_object import V3ListEnvelopeProviderPackagePriceObject
from .v3no_data_reason import V3NoDataReason
from .v3page_meta import V3PageMeta
from .v3provider_package_price import V3ProviderPackagePrice
from .v3response_meta import V3ResponseMeta


class V3ListEnvelopeProviderPackagePrice(UniversalBaseModel):
    object: typing.Optional[V3ListEnvelopeProviderPackagePriceObject] = None
    items: typing.List[V3ProviderPackagePrice]
    page: V3PageMeta
    no_data_reason: typing.Optional[V3NoDataReason] = pydantic.Field(default=None)
    """
    Set when `items` is empty. `no_data` means no matching records exist; `permission_denied` means matching records exist but are excluded by your data permissions.
    """

    disclosures: typing.Optional[typing.List[str]] = pydantic.Field(default=None)
    """
    Human-readable caveats about what this result does and does not imply.
    """

    meta: typing.Optional[V3ResponseMeta] = None

    if IS_PYDANTIC_V2:
        model_config: typing.ClassVar[pydantic.ConfigDict] = pydantic.ConfigDict(extra="allow", frozen=True)  # type: ignore # Pydantic v2
    else:

        class Config:
            frozen = True
            smart_union = True
            extra = pydantic.Extra.allow
