# This file was auto-generated by Fern from our API Definition.

import typing

import pydantic
from ..core.pydantic_utilities import IS_PYDANTIC_V2, UniversalBaseModel
from .v3location_near import V3LocationNear
from .v3location_within import V3LocationWithin


class V3Location(UniversalBaseModel):
    """
    Structured location intent: exactly one of the three modes.
    """

    near: typing.Optional[V3LocationNear] = None
    within: typing.Optional[V3LocationWithin] = None
    zip: typing.Optional[str] = pydantic.Field(default=None)
    """
    Resolves the ZIP to its centroid, then runs `near`.
    """

    if IS_PYDANTIC_V2:
        model_config: typing.ClassVar[pydantic.ConfigDict] = pydantic.ConfigDict(extra="allow", frozen=True)  # type: ignore # Pydantic v2
    else:

        class Config:
            frozen = True
            smart_union = True
            extra = pydantic.Extra.allow
