# This file was auto-generated by Fern from our API Definition.

import typing

import pydantic
from ..core.pydantic_utilities import IS_PYDANTIC_V2, UniversalBaseModel


class V3PageMeta(UniversalBaseModel):
    size: int = pydantic.Field()
    """
    Number of items in this page.
    """

    total: int = pydantic.Field()
    """
    Count of the full filtered set, not just this page.
    """

    next_cursor: typing.Optional[str] = pydantic.Field(default=None)
    """
    Opaque cursor for the next page; null when exhausted.
    """

    if IS_PYDANTIC_V2:
        model_config: typing.ClassVar[pydantic.ConfigDict] = pydantic.ConfigDict(extra="allow", frozen=True)  # type: ignore # Pydantic v2
    else:

        class Config:
            frozen = True
            smart_union = True
            extra = pydantic.Extra.allow
