# This file was auto-generated by Fern from our API Definition.

import typing

import pydantic
from ..core.pydantic_utilities import IS_PYDANTIC_V2, UniversalBaseModel
from .v3match_context import V3MatchContext
from .v3payer_object import V3PayerObject


class V3Payer(UniversalBaseModel):
    object: typing.Optional[V3PayerObject] = None
    id: str = pydantic.Field()
    """
    Payer identifier. Upstream-derived from the dataset and may change as the dataset is rebuilt. Re-resolve via search rather than persisting long-term.
    """

    name: typing.Optional[str] = pydantic.Field(default=None)
    """
    Display name; null when reference data is missing.
    """

    context: typing.Optional[V3MatchContext] = pydantic.Field(default=None)
    """
    Query-relative metadata (search only).
    """

    if IS_PYDANTIC_V2:
        model_config: typing.ClassVar[pydantic.ConfigDict] = pydantic.ConfigDict(extra="allow", frozen=True)  # type: ignore # Pydantic v2
    else:

        class Config:
            frozen = True
            smart_union = True
            extra = pydantic.Extra.allow
