# This file was auto-generated by Fern from our API Definition.

import typing

import pydantic
from ..core.pydantic_utilities import IS_PYDANTIC_V2, UniversalBaseModel
from .v3match_context import V3MatchContext
from .v3provider_address import V3ProviderAddress
from .v3provider_object import V3ProviderObject


class V3Provider(UniversalBaseModel):
    object: typing.Optional[V3ProviderObject] = None
    id: str = pydantic.Field()
    """
    Provider identifier. Upstream-derived from the dataset and may change as the dataset is rebuilt. Re-resolve via search rather than persisting long-term.
    """

    name: str = pydantic.Field()
    """
    Provider facility or organization name.
    """

    type: typing.Optional[str] = pydantic.Field(default=None)
    """
    Provider type as reported in the dataset.
    """

    npi: typing.Optional[str] = pydantic.Field(default=None)
    """
    National Provider Identifier.
    """

    address: V3ProviderAddress
    context: typing.Optional[V3MatchContext] = pydantic.Field(default=None)
    """
    Query-relative metadata (near/zip mode only).
    """

    if IS_PYDANTIC_V2:
        model_config: typing.ClassVar[pydantic.ConfigDict] = pydantic.ConfigDict(extra="allow", frozen=True)  # type: ignore # Pydantic v2
    else:

        class Config:
            frozen = True
            smart_union = True
            extra = pydantic.Extra.allow
