// This file was auto-generated by Fern from our API Definition.

import type * as TurquoiseHealthApi from "../../../../index.js";

/**
 * @example
 *     {
 *         package_id: "GA003",
 *         pricing: {
 *             type: "negotiated",
 *             network_id: "-3776001016975145508"
 *         },
 *         member_eligibility: {
 *             first_name: "test123",
 *             last_name: "test123",
 *             date_of_birth: "2001-01-01",
 *             member_id: "test123",
 *             consent_attested: "consent_attested"
 *         },
 *         location: {
 *             zip: "80218"
 *         }
 *     }
 */
export interface ConsumerSitePriceComparisonInput {
    package_id: string;
    provider_id?: string | null;
    pricing: TurquoiseHealthApi.ConsumerSitePricingNegotiated;
    member_eligibility: TurquoiseHealthApi.ConsumerSiteMemberEligibilityInput;
    location?: TurquoiseHealthApi.ConsumerSiteLocation | null;
}
