// This file was auto-generated by Fern from our API Definition.

import type * as TurquoiseHealthApi from "../../../../index.js";

/**
 * @example
 *     {
 *         package_id: "GA003",
 *         provider_id: "5756",
 *         pricing: {
 *             type: "negotiated",
 *             network_id: "-3776001016975145508"
 *         },
 *         member_eligibility: {
 *             first_name: "test123",
 *             last_name: "test123",
 *             date_of_birth: "2001-01-01",
 *             member_id: "test123",
 *             consent_attested: "consent_attested"
 *         },
 *         sort_direction: "asc",
 *         page_size: 25
 *     }
 */
export interface ConsumerSitePersonalizedEstimatesQueryRequest {
    /** Optional items to expand on */
    expand?:
        | TurquoiseHealthApi.V3ListPersonalizedEstimatesRequestExpandItem
        | TurquoiseHealthApi.V3ListPersonalizedEstimatesRequestExpandItem[];
    package_id: string;
    provider_id?: string | null;
    pricing: TurquoiseHealthApi.ConsumerSitePricingNegotiated;
    member_eligibility: TurquoiseHealthApi.ConsumerSiteMemberEligibilityInput;
    location?: TurquoiseHealthApi.ConsumerSiteLocation | null;
    sort?: TurquoiseHealthApi.ConsumerSitePriceSort | null;
    sort_direction?: ConsumerSitePersonalizedEstimatesQueryRequest.SortDirection;
    page_size?: number;
    cursor?: string | null;
}

export namespace ConsumerSitePersonalizedEstimatesQueryRequest {
    export const SortDirection = {
        Asc: "asc",
        Desc: "desc",
    } as const;
    export type SortDirection = (typeof SortDirection)[keyof typeof SortDirection];
}
