// This file was auto-generated by Fern from our API Definition.

/**
 * @example
 *     {}
 */
export interface GetInsuranceNetworksRequest {
    /** Limit networks to a specific SSP */
    ssp_id?: string | null;
    /** Filter by payer name */
    payer_name?: string | null;
    /** Page number */
    page?: number;
    /** Page size */
    page_size?: number;
}
