// This file was auto-generated by Fern from our API Definition.

/**
 * @example
 *     {}
 */
export interface GetProvidersRequest {
    /** Match provider name (case-insensitive) */
    provider_name?: string | null;
    /** Exact provider NPI */
    npi?: string | null;
    /** Exact provider city */
    city?: string | null;
    /** Two-letter state abbreviation */
    state?: string | null;
    /** Exact ZIP code */
    zip_code?: string | null;
    /** Page number */
    page?: number;
    /** Page size */
    page_size?: number;
}
