// This file was auto-generated by Fern from our API Definition.

import type * as TurquoisehealthApi from "../../../../index.js";

/**
 * @example
 *     {
 *         ssp_id: "GA002",
 *         network_id: "8361580493441765265",
 *         location: {
 *             zip_anchor: "80202"
 *         }
 *     }
 *
 * @example
 *     {
 *         ssp_id: "GA002",
 *         location: {
 *             within_state: "CO"
 *         }
 *     }
 *
 * @example
 *     {
 *         ssp_id: "RA005",
 *         location: {
 *             near_lat: 39.625533,
 *             near_lng: -104.898823,
 *             near_radius_m: 25000
 *         },
 *         page_size: 50
 *     }
 *
 * @example
 *     {
 *         provider_id: "21929"
 *     }
 */
export interface PricesRequest {
    /** Filter to a single SSP. Upstream-derived from the dataset and may change as the dataset is rebuilt. Do not bake into URLs, bookmarks, or persistent storage. */
    ssp_id?: string | null;
    /** Filter to a single provider. Upstream-derived from the dataset and may change as the dataset is rebuilt. Do not bake into URLs, bookmarks, or persistent storage. */
    provider_id?: string | null;
    /** Filter to a single insurance network. Omit (or pass null) to get cash prices. Int64String — JSON string-wrapped 64-bit integer, because JSON cannot safely represent values above 2^53. Upstream-derived from the dataset and may change as the dataset is rebuilt. Do not bake into URLs, bookmarks, or persistent storage. */
    network_id?: string | null;
    /** Optional location scope. Exactly zero or one of `near`, `within`, or `zip_anchor` modes. */
    location?: TurquoisehealthApi.RateCompareLocation | null;
    /** Page size, 1-250. */
    page_size?: number;
    /** Opaque cursor from a previous response's `page.next_cursor`. */
    cursor?: string | null;
}
