// This file was auto-generated by Fern from our API Definition.

/**
 * @example
 *     {
 *         ssp_id: "DE000",
 *         provider_id: "provider_id"
 *     }
 *
 * @example
 *     {
 *         ssp_id: "DE000",
 *         provider_id: "provider_id",
 *         network_id: "8361580493441765265"
 *     }
 */
export interface ProviderPackageBreakdownRequest {
    /** Standard service package identifier */
    ssp_id: string;
    /** Provider identifier */
    provider_id: string;
    /** Insurance network identifier */
    network_id?: string | null;
}
