// This file was auto-generated by Fern from our API Definition.

/**
 * @example
 *     {
 *         provider_id: "21929"
 *     }
 */
export interface V2GetProviderRequest {
    /** Provider identifier. */
    provider_id: string;
}
