// This file was auto-generated by Fern from our API Definition.

/**
 * @example
 *     {}
 */
export interface V2ListSspsRequest {
    /** Case-insensitive substring match on SSP name. */
    name?: string | null;
    /** Case-insensitive substring match on SSP patient description. */
    description?: string | null;
    /** Case-insensitive substring match across name OR patient description. */
    search?: string | null;
    /** Page size. */
    page_size?: number;
    /** Opaque cursor from a previous response's page.next_cursor. */
    cursor?: string | null;
}
