// This file was auto-generated by Fern from our API Definition.

/**
 * @example
 *     {
 *         network_id: "-3776001016975145508"
 *     }
 */
export interface V3GetNetworkRequest {
    /** Network identifier (string-wrapped 64-bit integer). */
    network_id: string;
}
