// This file was auto-generated by Fern from our API Definition.

/**
 * @example
 *     {
 *         payer_id: "7001"
 *     }
 */
export interface V3GetPayerRequest {
    /** Payer identifier. */
    payer_id: string;
}
