// This file was auto-generated by Fern from our API Definition.

import type * as TurquoiseHealthApi from "../../../../index.js";

/**
 * @example
 *     {
 *         price_id: "prc_2751.RA007.8361580493441765265"
 *     }
 */
export interface V3GetPriceRequest {
    /** Price identifier. */
    price_id: string;
    /** Relations to inline. Repeat the param to request several. */
    expand?: TurquoiseHealthApi.V3PriceExpand[] | null;
}
