// This file was auto-generated by Fern from our API Definition.

/**
 * @example
 *     {}
 */
export interface V3ListPayersRequest {
    /** Case-insensitive substring match on payer name. */
    name?: string | null;
    /** Payers with at least one price at this provider. */
    provider_id?: string | null;
    /** Payers with at least one price for this package. */
    package_id?: string | null;
    page_size?: number;
    /** Opaque cursor from a previous page.next_cursor. */
    cursor?: string | null;
    "location.near.lat"?: number | null;
    "location.near.lng"?: number | null;
    "location.near.radius_m"?: number | null;
    "location.within.state"?: string | null;
    "location.within.cbsa"?: string | null;
    /** Comma-separated ZIP codes (exact match, any-of). */
    "location.within.zip_codes"?: string | null;
    /** Resolves the ZIP to its centroid, then runs `near` with the default radius. */
    "location.zip"?: string | null;
}
