// This file was auto-generated by Fern from our API Definition.

/**
 * @example
 *     {
 *         package_id: "OB002"
 *     }
 */
export interface V3ListPackageLineItemsRequest {
    /** Package identifier. */
    package_id: string;
}
