// This file was auto-generated by Fern from our API Definition.

import type * as TurquoiseHealthApi from "../../../../index.js";

/**
 * @example
 *     {
 *         package_id: "RA007",
 *         provider_id: "2751",
 *         pricing: {
 *             type: "negotiated",
 *             network_id: "network_id"
 *         }
 *     }
 *
 * @example
 *     {
 *         package_id: "RA007",
 *         pricing: {
 *             type: "cash"
 *         },
 *         location: {
 *             within: {
 *                 state: "IL"
 *             }
 *         }
 *     }
 *
 * @example
 *     {
 *         package_id: "RA007",
 *         pricing: {
 *             type: "cash"
 *         },
 *         location: {
 *             near: {
 *                 lat: 41.8781,
 *                 lng: -87.6298,
 *                 radius_m: 40000
 *             }
 *         }
 *     }
 */
export interface V3PricesCompareRequest {
    package_id: string;
    provider_id?: string | null;
    pricing: TurquoiseHealthApi.V3PricesCompareRequestPricing;
    location?: TurquoiseHealthApi.V3Location | null;
}
