# This file was auto-generated by Fern from our API Definition.

import typing

from ..core.api_error import ApiError
from ..types.v3error_response import V3ErrorResponse


class TooManyRequestsError(ApiError):
    def __init__(self, body: V3ErrorResponse, headers: typing.Optional[typing.Dict[str, str]] = None):
        super().__init__(status_code=429, headers=headers, body=body)
