name: ci

on: [push]

env:
  DOTNET_SKIP_FIRST_TIME_EXPERIENCE: true
  DOTNET_NOLOGO: true

jobs:
  compile:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v5

      - uses: actions/checkout@master

      - name: Setup .NET
        uses: actions/setup-dotnet@v5
        with:
          dotnet-version: 8.x

      - name: Print .NET info
        run: dotnet --info

      - name: Install tools
        run: dotnet tool restore
        working-directory: csharp

      - name: Restore dependencies
        run: dotnet restore src/TurquoiseHealth.Api/TurquoiseHealth.Api.csproj
        working-directory: csharp

      - name: Build Release
        run: dotnet build src/TurquoiseHealth.Api/TurquoiseHealth.Api.csproj -c Release --no-restore
        working-directory: csharp

  csharp-unit-tests:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v5

      - name: Setup .NET
        uses: actions/setup-dotnet@v5
        with:
          dotnet-version: 8.x

      - name: Print .NET info
        run: dotnet --info

      - name: Install tools
        run: |
          dotnet tool restore
        working-directory: csharp

      - name: Restore dependencies
        run: dotnet restore src/TurquoiseHealth.Api.Test/TurquoiseHealth.Api.Test.csproj
        working-directory: csharp

      - name: Build Release
        run: dotnet build src/TurquoiseHealth.Api.Test/TurquoiseHealth.Api.Test.csproj -c Release --no-restore
        working-directory: csharp

      - name: Run Tests
        run: dotnet test src/TurquoiseHealth.Api.Test/TurquoiseHealth.Api.Test.csproj -c Release --no-build --no-restore
        working-directory: csharp

  python-unit-tests:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v5

      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Install dependencies
        run: |
          pip install -e ./python
          pip install -r python/tests/requirements-test.txt

      - name: Run Tests
        run: pytest python/tests/test_integration.py -v

  typescript-unit-tests:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v5

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '18'

      - name: Install parent package dependencies
        run: npm install
        working-directory: typescript

      - name: Install test dependencies
        run: npm install
        working-directory: typescript/tests

      - name: Run Tests
        run: npm test
        working-directory: typescript/tests


