name: ci

on: [pull_request]

env:
  DOTNET_SKIP_FIRST_TIME_EXPERIENCE: true
  DOTNET_NOLOGO: true

jobs:
  compile:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v5

      - uses: actions/checkout@master

      - name: Setup .NET
        uses: actions/setup-dotnet@v5
        with:
          dotnet-version: 8.x

      - name: Print .NET info
        run: dotnet --info

      - name: Install tools
        run: dotnet tool restore
        working-directory: csharp

      - name: Restore dependencies
        run: dotnet restore src/TurquoiseHealth.Api/TurquoiseHealth.Api.csproj
        working-directory: csharp

      - name: Build Release
        run: dotnet build src/TurquoiseHealth.Api/TurquoiseHealth.Api.csproj -c Release --no-restore
        working-directory: csharp

  unit-tests:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v5

      - name: Setup .NET
        uses: actions/setup-dotnet@v5
        with:
          dotnet-version: 8.x

      - name: Print .NET info
        run: dotnet --info

      - name: Install tools
        run: |
          dotnet tool restore
        working-directory: csharp

      - name: Restore dependencies
        run: dotnet restore src/TurquoiseHealth.Api.Test/TurquoiseHealth.Api.Test.csproj
        working-directory: csharp

      - name: Build Release
        run: dotnet build src/TurquoiseHealth.Api.Test/TurquoiseHealth.Api.Test.csproj -c Release --no-restore
        working-directory: csharp

      - name: Run Tests
        run: dotnet test src/TurquoiseHealth.Api.Test/TurquoiseHealth.Api.Test.csproj -c Release --no-build --no-restore
        working-directory: csharp


